### ISSUE TITLE
The rating prompt is not displayed when Firefox is set as default browser.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10012]
## Steps to reproduce
1. Clean install app from app store v97.0 (7635)
2. Launch app 
3. Go Settings -> Tap on "Set default browse" -> Change default browser to Firefox
4. Go to iOS settings -> Change date from 14.02 to 15.02
5. Open the app -> Open tabs tray -> Close the app
6. Go to iOS settings -> Change date from 15.02 to 16.02
7. Open the app -> Open tabs tray -> Close the app
8. Go to iOS settings -> Change date from 16.02 to 17.02
9. Open the app -> Open tabs tray -> Close the app
10. Go to iOS settings -> Change date from 17.02 to 18.02
11. Open the app -> Open tabs tray -> Close the app
12. Go to iOS settings -> Change date from 18.02 to 19.02
13. Open the app -> Open tabs tray -> Close the app
14. Go to iOS settings -> Change date from 19.02 to 20.02
15. Open the app -> Open tabs tray -> Close the app
16. Go to iOS settings -> Change date from 19.02 to 21.02
17. Open the app -> Open tabs tray -> Close the app
### Expected behavior
- The rating prompt should be displayed after step 17)
### Actual behavior
- The rating prompt is not displayed when Firefox is set as default browser.
### Device & build information
* Device: iPhone 13 (15.1.1)
* Build version: 96.0 (7635)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3760)

**Comment by SimonBasca** [comment]
Note that this issue also reproducible for the cases when 
- bookmarking 5 pages and following the STR
- pinning 2 sites to top sites and following the STR

**Comment by lmarceau** [comment]
We only detect the default browser if a link was opened previously with the app. There's no other way to know otherwise if it's default or not (the user could click on the default browser banner but don't change it in it's settings). So between step 3 and 4 there should be a step "open link from gmail" or something.

**Comment by SimonBasca** [comment]
@lmarceau I tried re-testing by opening a link from notes in Firefox set as default browser between steps 3 and 4 and was unable to get the prompt to be displayed.

**Comment by lmarceau** [comment]
@SimonBasca Apple has some specific constraints in regards to the in-app prompt. It could affect yes if it's on the same device. The ideal way to test is to have a debug build, to be certain that the prompt will show when it is asked to show. Otherwise with a Prod build we rely on Apple deciding or not to show the prompt even if we asked for it.
