### ISSUE TITLE
The keyboard is displayed when on boarding is visible.

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10096]
## Steps to reproduce
1. Clean install 98.0 (8184)
### Expected behavior
- The keyboard should be hidden when on boarding is displayed.
### Actual behavior
- The keyboard is displayed when on boarding is visible.
### Device & build information
* Device: iPad Pro (15.2)
* Build version: 98.0 (8184)
### Notes
Attachments: 

![screenshot](https://user-images.githubusercontent.com/32130829/155685602-aa694319-026c-47cb-8ca6-fa18b14168ad.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3813)

**Comment by data-sync-user** [comment]
➤ Raluca Iordan commented:

Tested on iPad with the current version of code and the issue does not reproduce anymore. I assume it was solved in the meantime since it was first opened like 3 months ago.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Tested on iPad Pro (15.4) on v9000 (9738)

Confirming that the issue is not reproducible anymore. The keyboard is not displayed when first running the app but the URL bar is still focused. After dismissing the onboading the keyboard will be displayed.

Raluca Iordan Daniela Arcese since on iPhone we don’t focus the URL bar on the first run could we have the same behavior for iPad or should we leave it as it is?

See video of current behavior.

!Video.mp4|width=1920,height=1342!

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Simion Basca Ya that’s a good idea for consistency. Could you create a new issue to fix that?

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

New issue logged at https://github.com/mozilla-mobile/firefox-ios/issues/10850 ( https://github.com/mozilla-mobile/firefox-ios/issues/10850|smart-link ) .
