### ISSUE TITLE
Constrain Customize Homepage button to the bottom of homepage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#10131]
If you don’t have any homescreen sections enabled, then the ‘Customize Homepage’ button shows in the middle of the screen and looks out of place.

Expected Behaviour

The Customize Homepage button should be constrained to the bottom of the screen

!image-20220301-224942.png|width=503,height=1040!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3837)

**Comment by finebel** [comment]
Since the `FirefoxHomeViewController` uses a Collection View, I think it's quite complicated to add a view which sticks to the bottom, because unlike `UITableView` a Collection View doesn't have something like `tableFooterView`.
One possible solution would be to decrease the space between the last "normal" section and the "Customize Homepage" Button. This would look like the following:

![sample_customize_btn](https://user-images.githubusercontent.com/46824694/157617395-ddd89771-cf12-4454-9d56-f3ab2626c98b.jpg)

@data-sync-user What do you think? Should I open a PR?

**Comment by lmarceau** [comment]
@finebel We want to remove that parent collection view at one point. It makes it indeed more complicated to manage sections and spaces, and doesn't add much value since child sections have collection views as well when they need it. Until we do that, I believe we should wait for that button repositioning. It will be easier to handle at that point (so we do it once only).
