### ISSUE TITLE
[iPad] Unable to move the text cursor to the beginning of the first word with spacebar

### ISSUE THREAD

**Issue by brangpd** [mozilla-mobile/firefox-ios#10166]
## Steps to reproduce
1. Go to google.com
2. In the search bar, type some words
3. Tap and hold the spacebar, try to move the text cursor to the beginning of the first word
### Expected behavior
The text cursor stops at the beginning of the first word (before the first letter).
### Actual behavior
The text cursor always stops after the first letter.
### Device & build information
* Device: iPad Air 3 (iPadOS 15.3)
* Build version: Firefox Daylight 97.0 (7635)
### Notes
Attachments: 

https://user-images.githubusercontent.com/40844407/156928662-269f221a-e8ed-4e20-89ce-216ccd22b3f4.MP4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3863)

**Comment by SimonBasca** [comment]
This issue is also reproducible in Safari following the STR. This seems to be a Google issue and not a Firefox one. Note that the issue is only reproducible on Google and not on other search engine (e.g Duck Duck Go) and only for certain characters.

Unfortunately there is nothing actionable on our side.
