### ISSUE TITLE
The keyboard is displayed in tabs tray when New Tab is set as blank page

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10351]
## Steps to reproduce
1. Set New Tab as Blank page
2. Have multiple tabs opened
2. Open Tabs Tray
3. Close a tab

OR

1. Set New Tab as Blank page
2. Open Tabs Tray
3. Switch between Normal Browsing and Private Browsing

### Expected behavior
- Keyboard should not be displayed in tabs tray.
### Actual behavior
- The keyboard is displayed in tabs tray.
### Device & build information
* Device: iPhone 13 mini (15.4)
* Build version: 99.0 (8615)
### Notes
Attachments:

https://user-images.githubusercontent.com/32130829/160808703-dc282f7f-7f20-4f96-89e8-3aff908f095a.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4018)

**Comment by SimonBasca** [comment]
Regressed from https://github.com/mozilla-mobile/firefox-ios/issues/6774

**Comment by iMostfa** [comment]
i've been looking at this, from what i can see
this happens when tabs is [selected](https://github.com/mozilla-mobile/firefox-ios/blob/b2a58f2561520a0be63756fe0acc342fe9478254/Client/Frontend/Browser/TabDisplayManager.swift#L317), which triggers  [didGainFocus](https://github.com/mozilla-mobile/firefox-ios/blob/f114d3e4af6dee8db1696163113eee04260e7a02/Client/Frontend/Browser/TabManager.swift#L283)

removing `self.tabManager.selectTab(tab)` from `togglePrivateMode(isOn:createTabOnEmptyPrivateMode:)`
doesn't appear to be breaking any tests, but i'm not sure if this's the right direction, 

i'm still investigating if something else should be done here, but i would like to know your opinion 
@SimonBasca 

Thank you

**Comment by SimonBasca** [comment]
@iMostfa Thanks for taking a look at this. I think @lmarceau could have some advice to point you in the right direction. @lmarceau could you please share your opinion on  https://github.com/mozilla-mobile/firefox-ios/issues/10351#issuecomment-1086480537? Thanks!

**Comment by lmarceau** [comment]
@iMostfa yes this happens when private mode is toggled, but I don't think we should remove this call. I had a cursory look and it relates to didSelectedTabChange in BVC when we're on a .blankPage. I don't see any obvious solution as of now, I'll try to think of something.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 804720df41008d6c1adea8d11a3f05af1aef7c01
