### ISSUE TITLE
The deleted entry from the history panel is not deleted from the recently visited section

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#10745]
## Steps to reproduce
1. Visit a page so the recently visited section is populated.
2. Go to history.
3. Swipe to delete on the entry.
4. Check the recently visited section.
### Expected behavior
The deleted entry from the history panel should be deleted from the recently visited section.
### Actual behavior
The deleted entry from the history panel is not deleted from the recently visited section.
### Device & build information
* Device: iPhone 12 Pro (15.4).
* Build version: 9000 (9536).
### Notes
The recently visited list is only cleared when clearing data via the trash can icon or via clearing all data from data management 
After the homepage is refreshed the visited tab will no longer be displayed in the jump back section
Attachments: 

https://user-images.githubusercontent.com/42831109/168288183-1ec81936-8353-460f-b36e-a4c53e974d59.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4235)

**Comment by J4RF** [comment]
Seeing this issue as well. It doesn’t just apply to deleted history items, sites visited while in private browsing mode are also showing up in Recently Visited, days/weeks after closing those private sessions and returning to normal browsing.

**Comment by SimonBasca** [comment]
This issue is still reproducible on v102.0 (10804). It's also reproducible when clearing "Today" and "Today & Yesterday" from the history panel.

**Comment by jr-johnson-support** [comment]
We have a user impacted on V106 noting this issue. Wondering if we need more informaiton prior to addressing this or if/when a fix for this might make it into release.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (29966) with iPhone 13 Pro (15.7.1).
This issue will also be checked when an official RC build is created for the fix version.

I’m pretty sure this one was fixed by https://mozilla-hub.atlassian.net/jira/software/c/projects/FXIOS/boards/200?modal=detail&selectedIssue=FXIOS-5728 ( https://mozilla-hub.atlassian.net/jira/software/c/projects/FXIOS/boards/200?modal=detail&selectedIssue=FXIOS-5728|smart-link ).
