### ISSUE TITLE
.experimenter.yaml keeps getting modified. 

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#10741]
I notice in my own builds that .experimenter.yaml often gets modified by something (not me), usually to swap these two lines around:

```
        - show-none
        - show-next-message
```

As such I either have to discard the change so as not to commit to git, or accept the change, only for it to swap back at some future point.

I see in a recent commit from @lmarceau (4808378f) that the file was also modified by swapping some other lines around. I don't know if this was intentional or the same issue I have.

BTW - I haven't looked into what exactly is modifying the file. Seems if its meant to be modified then it must be autogenerated by something else and so it should be in gitignore.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4233)

**Comment by lmarceau** [comment]
Yes, .experimenter.yaml is generated deterministically it seems. The enum properties change place, which is quite annoying. There's a ticket open on the nimbus side to fix this issue. For now you can ignore those changes. Closing this ticket since it's tracked with: https://github.com/mozilla/experimenter/issues/7284
