### ISSUE TITLE
“Recently visited” features activity in private tabs

### ISSUE THREAD

**Issue by hyphen-four** [mozilla-mobile/firefox-ios#10764]
## Steps to reproduce
Visit some websites in private mode, close the tabs afterwards

### Expected behavior
no trace is left behind on my device

### Actual behavior
Mixed in with my other internet activity on the Home Screen, some of my privately viewed pages show up

### Device & build information
* Device: iPhone 7
* Build version: Firefox Daylight 100.1 (9384)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4244)

**Comment by Encrepuise** [comment]
I am also seeing this problem as well. It was kinda shocking when I first encounter with it. Websites that I've visited while in private browsing mode are also can be seen in "Recently Visited" section of homepage.

Device: iPhone 12 Pro (15.4)
Build version: Firefox Daylight 100.1 (9384)

**Comment by lmarceau** [comment]
Hello, thanks for opening this ticket! We had a bug related to this problem here that was fixed: https://github.com/mozilla-mobile/firefox-ios/issues/10659 new private tabs shouldn't be recorded. The private tabs you see are were in theory recorded before we made this bugfix. It would be helpful for us to confirm new private tabs aren't recorded for you?

As for the private information showing up, we're very sorry this bug happened. Your data should be removed automatically after 2 weeks, or if you clear all data in the data management settings.
