### ISSUE TITLE
No password autofill on paypal.com/signin

### ISSUE THREAD

**Issue by meaou** [mozilla-mobile/firefox-ios#10856]
## Steps to reproduce
1. Navigate to [Paypal|paypal.com/signin] after having visited it as a logged-in user just a few hours before. 
1. Firefox will display a login form with an auto-filled login. 

### Expected behavior
Password is auto-filled alongside the login without any additional interactions.

### Actual behavior
The password is not auto-filled in, although it has been successfully stored - when attempting to enter a password and making a typo in it, "update password dialogue" is displayed. 

### Device & build information
* Device: iPhone 12 Pro, iOS 15.3.1
* Build version: Daylight 98.2
  1. Notes
Attachments: 
![no password prefill](https://user-images.githubusercontent.com/3293941/170370637-d0d974a0-437e-4fa9-80a0-f37df45bdd60.jpg)
![password update](https://user-images.githubusercontent.com/3293941/170370643-563476d5-0e5f-4bd4-aa8f-e80ce44bdea9.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4297)

**Comment by SimonBasca** [comment]
Confirming the issue is reproducible on v 101.0 (9723) and latest main 42bb8dc61447541b984f21b33c8ae72e996899ea. After attempting to visit Pay Pall with the login saved, only the email was auto filled. Tapping on the password field does not auto fill the password. After tapping once on the email and tapping again on the password field, the password was also auto filled.
