### ISSUE TITLE
Tab screen doesn’t scroll to show the current tab tile (when tab groups are enabled)

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#10857]
## Steps to reproduce
1. Make sure tab groups are enabled in Settings > Tabs > Tab Groups. 
1. Open a bunch of new tabs, enough that their tab tiles don’t all fit on the tab screen. 
1. Switch to the bottom-most tab. 
1. Open the tab screen. 

### Expected behavior
The current tab should be visible on the tab screen. 

### Actual behavior
The current tab is not on screen in the tab screen. You must scroll down to find it. 

### Device & build information
* Device: iPhone 12
* Build version: 101.0 (9723)

### Notes

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4298)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Simion Basca can you investigate this to find some reliable STR?

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Sorin Paraipan When you have tab groups enabled on Firefox Settings then below is how you make groups

a) Open a tab
b) Search for anything (PS 5) 
c) Long press on a couple of links and tap on open in new tab from the context menu
d) You need minimum 2 links from the same google page for a group to form otherwise there will be no groups. So I suggest opening atleast 3 links from your google search on the tab
e) Now opening on Tab Tray will show you tab groups. 

Next part is to open a few tabs (regular ones) 
Now in TabDisplayManager.swift and GridTabsViewController we have scrollToItem code which is where you can start digging into why the scrolling to the proper tab isn’t working

Let me know if you need more information
