### ISSUE TITLE
Reader View button no longer shown in versions >= 99.0

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#10868]
This bug is a regression in Firefox version 99.0 (8544).

### Steps to reproduce

1. In TestFlight, install Firefox version 98 (8233).
2. Open https://karimjedda.com/lessons-learned-developer-to-project-manager/
3. See the Reader View button in the address bar. 
4. Install Firefox version >= 99.0 (8544).
5. Open the page from step 2 again.

### Expected behavior

The Reader View button should be shown in the address bar. 

### Actual behavior

The Reader View button is not shown in the address bar. 

### Device & build information
* Device: iPhone 12 and iOS 15.5
* Build version: Firefox version 101.0 (9723)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4304)

**Comment by cpeterso** [comment]
I was upgrading and downgrading in the TestFlight app. I just uninstalled and reinstalled v101 fresh from TestFlight and now I see the Reader View icon.

**Comment by SimonBasca** [comment]
In my case the issue is reproducible after these STR:
1. Install v101.0 (9723)
2. Open https://karimjedda.com/lessons-learned-developer-to-project-manager/ via external link in Firefox as default browser.(in my case via Skype or notes)
3. Tap the reader mode icon to enable reader mode
4.  Tap the reader mode icon  to disable reader mode

Actual :
- The reader mode icon will not be displayed. 

https://user-images.githubusercontent.com/32130829/170663050-84727313-4a86-4caa-be5a-2d66c92fb0da.mp4

**Comment by SimonBasca** [comment]
Also reproducible after these STR on v102.0 (11005)

## Steps to reproduce
1. Go to BBC and tap on an article
2. Observe the reader mode icon
3. Tap the refresh button
4. Observe the reader mode icon

- The reader mode icon will no longer be displayed.

**Comment by cpeterso** [comment]
I still see this bug where the reader mode button is missing. It doesn’t happen all the time. When the button does appear, it seems to happen when loading a page for the first time, so this bug is probably a race condition between page loading and the code that displays the reader mode button.

**Comment by nishant2718** [comment]
On further investigation, this doesn’t occur as frequently as we thought, and unfortunately it depends on the site. 

What’s happening is a site is evaluated for whether it can be viewed in reader mode with a JS injected script. Typically, the script is run on each page load and `Tab.swift`'s `@objc func userContentController(_ userContentController: WKUserContentController, didReceive message: WKScriptMessage) `. The issue is occasionally, this doesn't get triggered. You can go to a site, trigger reader mode, trigger it back to the original site, and at that point, you may see that the button doesn't appear. I'm not sure why it doesn't get triggered - I'll ask for a bit of help to figure that out. 

In this case, the reader mode state is incorrectly left as "active." So if we force the button to show, it'll be untoggleable (to get back INTO reader mode). The reason it doesn't display is because there's a bit of logic sort of handling the case where if the state of reader mode is stale, the button won't show. Which is what's happening in this ticket.

**Comment by cpeterso** [comment]
I’m no longer able to reproduce this bug in v108. I used to see it all the time, so I’m going to optimistically close this bug. 🙏🏻
