### ISSUE TITLE
Firefox crashes when changing device orientation to landscape and back to portrait

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#10949]
## Steps to reproduce
1. sing in to FxA
2. Change device orientation to landscape
3. Change device orientation to portrait
### Actual behavior
- Firefox crashes.
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: 28f94f7484c41d148b6c188ca5c446f2f045d1f2
### Notes
- The crash is not reproducible if Shortcuts are disabled on homepage
Attachments: 

https://user-images.githubusercontent.com/32130829/172616802-28f8467d-aaed-4263-a4a2-3313cdb294d9.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4353)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v102.0 (10804)

**Comment by do7msm** [comment]
Same problem with iPhone 14: Firefox crashes everytime the phone is rotated to landscape mode.
Any solution in sight? Uninstall and re-install does not solve the problem.

**Comment by lmarceau** [comment]
@do7msm Hello! This is an older issue that is normally fixed. Could you tell us on which version you are? The latest should be 109.0. You can check that through our app settings and scrolling at the bottom.

**Comment by do7msm** [comment]
Hello,thank you for your reaction to my crash problem with Firefox on my iPhone 14. You are right, the current version number is up to date and since I changed the settings as described above Firefox was stable. According to your mail I re-activated Shortcuts in the settings for the Homepage - and tada! Firefox NO LONGER CRASHES!Meanwhile I rebooted my phone several times due to installation of other apps - so possibly this contributed to the successful reset? However, let’s hope the topic can be considered as solved. Thanx again for your work, I really appreciate it!Cheers,Sebastian Von meinem iPhone 14 gesendetOn 23. Jan 2023, at 15:24, lmarceau ***@***.***> wrote:﻿
@do7msm Hello! This is an older issue that is normally fixed. Could you tell us on which version you are? The latest should be 109.0. You can check that through our app settings and scrolling at the bottom.
