### ISSUE TITLE
Start at home always opens normal tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11079]
## Steps to reproduce
1. Launch Firefox 
2. Switch to private browsing
3. Close Firefox
4. Change time to +4 hours
5. Open Firefox
### Expected behavior
- A new homepage tabs should be displayed in Private browsing
### Actual behavior
- A new homepage tabs should be displayed in Normal browsing
### Device & build information
* Device: iPhone 13 mini
* Build version: 102.0 (11005)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/174568258-64353d3e-227b-43c0-8195-45cb5ff82be8.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4440)

**Comment by nbhasin2** [comment]
@SimonBasca Is this also happening on main and on iPad?

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

This issue was not reproducible on iPad.

Verifying as fix on v102.0 (11255). This issue is no longer reproducible but please note that there was a behavior change see https://mozilla-hub.atlassian.net/browse/FXIOS-4447 ( https://mozilla-hub.atlassian.net/browse/FXIOS-4447|smart-link )
