### ISSUE TITLE
Pocket section is not displayed on the Home page after enabling the "Recommended by Pocket" option

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#11084]
v102.0 (11005)

1. Set the device region to France or any other region where Pocket is not enabled by default.
1. Go to Firefox settings -> Homepage and enable the "Recommended by Pocket" option.
1. Go back to the Firefox Homepage.

Expected: The Pocket section should be displayed on the Homepage.

Actual: The section is not displayed. It will show up only for regions where Pocked is enabled by default (e.g CA)

Last good build: v9000 (9450)
First bad build: v9000 (9505) (may 11)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4443)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Code wise, it seems like this has been happening since at least before Nov 2021. Not sure how it was working in v9000.9450 - I just tested it and it’s not working in there either for me, so I’m a bit confused. Nevertheless, I fixed the immediate issue; but if there’s steps to make this work is v9000.9450 outside of the steps listed in this ticket, please write them down as I wasn’t able to reproduce the good build results. Maybe this problem is more than the simple fix I implemented.

**Comment by csuciu** [comment]
I've just re-tested v9000.9450 vs v9000.9505 and I got the same result. 9450 is showing the Pocket section after enabling the option and 9505 it's not. Both builds are clean installed. 
The region was set to Romania and the language to English(UK).

https://user-images.githubusercontent.com/1866605/174792929-db9d011f-4a43-4d03-920c-666d353da352.mp4


Anyway, on build v102.0 (11255) the "Recommended by Pocket" options is no longer available in settings for the regions where Pocket is not enabled by default.
