### ISSUE TITLE
Homepage is displayed in the same tab as "github.com" after +4 hours

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11095]
## Steps to reproduce
1. Open a page (e.g "github.com")
2. Close the app from app switcher
3. Change time to +4 hours
### Expected behavior
- When the app is opened for the first time in 4 hours after visiting a page, it opens it should create a new tab to the homepage. If last tab was the homepage, it should not create a new tab. 
### Actual behavior
- Homepage is displayed in the same tab as "github.com"
### Device & build information
* Device: iPad Pro (15.4)
* Build version: 102.0 (11255)
### Notes
- This issue is also reproducible on iPhone
- See : https://mozilla-hub.atlassian.net/browse/FXIOS-1739
Attachments: 

https://user-images.githubusercontent.com/32130829/174771555-60d56e77-5398-430f-a074-8610a5e79bfe.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4447)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

After some investigation, it’s become clear that issue has been happening (in prod) since the StartAtHome feature was released. The decision was taken for it to not be a release blocker for v102.

**Comment by nbhasin2** [comment]
@SimonBasca can you try in v103 / v104 and lmk if this is still happening on iPhone 

If you can reproduce this on Simulator then that would be really helpful as well

**Comment by SimonBasca** [comment]
This issue is still reproducible on v103.0 (13910) and v104 (14880). On simulator I wasn't able to reproduce since I have to change the time and restart the sim for the new time to apply.

**Comment by yoanarios** [comment]
I couldn't reproduce either following the STR, I tried on iPhone and iPad on main and v104 (14880). If you can reproduce still @SimonBasca we might need to sync because it seems we are missing some configuration or step

**Comment by SimonBasca** [comment]
The issue is 100% reproducible on my side. Just note that if Firefox is left in background (without closing it from app switcher) before changing the time, the issue will not be reproducible. 

https://user-images.githubusercontent.com/32130829/183071431-c97c34bc-241d-496f-a8b0-21206699e36f.mp4

Just ping me on slack if you still have issues reproducing and we can sync.

**Comment by csuciu** [comment]
I’m able to reproduce this issue constantly when following this steps:
1. Have only one Homepage tab open.
2. Visit github.com in that tab.
3. Force close the app.
4. Go to iOS Settings and move the time fwd 4 hrs +
5. Open Firefox.

Expected: Two tabs are open. One with Github and one with the Homepage.

Result: The Homepage opens in the same tab where github.com was instead of a new tab. The back button in the tab is active but tapping on it doesn't do anything. Long pressing on the back button shows the tab history as shown bellow.

![Skype_Picture_2022_08_23T10_15_39_856Z](https://user-images.githubusercontent.com/1866605/186133778-8827d813-d688-4950-92ad-3aab89fe8ef7.jpeg)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Winnie Teichmann try it out and let me know if you have better luck reproducing this and we can even pair to fix this bug.

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Here are the log values of isFxAHomeTab where because we are only comparing it against internal:// there is a an issue where some urls always hit home even though they are not. 

TODO FIX: The fix is to account for the urls which are actually homepage  urls and not just a prefix for internal://

default	11:54:05.298363-0400	Client	NB -- url 1 -- internal://local/sessionrestore?history=%7B%0A%20%20%22history%22%20:%20%5B%0A%20%20%20%20%22internal:%5C/%5C/local%5C/about%5C/home%23panel%3D0%22,%0A%20%20%20%20%22https:%5C/%5C/github.com%5C/%22%0A%20%20%5D,%0A%20%20%22currentPage%22%20:%200%0A%7D

default	11:54:05.493810-0400	Client	NB -- url 1 -- internal://local/sessionrestore?url=https://github.com/

default	11:54:05.591276-0400	Client	NB -- url 1 -- internal://local/about/home!Screen Shot 2022-10-17 at 2.55.38 AM.png|width=976,height=333!

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

This issue is no longer reproducible. Tested on v9000 (20761).
