### ISSUE TITLE
make a seperate fork with gecko engine

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [mozilla-mobile/firefox-ios#11129]
### User Problem
use firefox addons for ios

### Ideas for Solution
make a seperate fork with gecko engine

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4463)

**Comment by lmarceau** [comment]
Gecko engine cannot be used on Apple platform at the moment. We can reopen if this changes at one point. Thanks.

**Comment by chrisvire** [comment]
@lmarceau with DMA being approved in EU, Gecko engine should be able to be used.

https://www.macrumors.com/2022/07/05/eu-approves-landmark-legislation-to-regulate-apple/

If this was done, would there be a separate GeckoView for iOS so that other apps could use Gecko in their own apps?

have an app that requires complex scripts that are supported by Gecko via GeckoView in Android. Here is a [slimmed down repo](https://github.com/chrisvire/GeckoViewTestAwami) that demonstrates it. I would love to be able to use something like GeckoView in my iOS apps.

**Comment by CuriousCodingCanadian** [comment]
The EU changes happened a while ago, and a lot of people would love to see this. Is this on the roadmap?

**Comment by Jecobe** [comment]
reopen plz

**Comment by CuriousCodingCanadian** [comment]
This issue should be reopened, and gecko can now be used. I'd appreciate if @lmarceau could reopen this as this is now possible. This would enable firefox addons on iOS, and also allow developers working on apps in other languages to get around [this crippling webkit bug](https://bugs.webkit.org/show_bug.cgi?id=6148) which makes text render horribly wrong in certain circumstances, and stops several web apps from working on iOS

**Comment by TyDraniu** [comment]
Aren't they doing it on bugzilla under https://bugzilla.mozilla.org/show_bug.cgi?id=1882872 ?
