### ISSUE TITLE
Firefox randomly queries my location when not being used

### ISSUE THREAD

**Issue by nasiralamreeki** [mozilla-mobile/firefox-ios#11228]
## Steps to reproduce

Use Firefox on iOS and check app privacy report 

### Expected behavior

Firefox doesn't do background location calls when it's not being used 

### Actual behavior

Firefox gathers my location data even when it's not being used both not respecting my privacy and also draining battery faster 

### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4521)

**Comment by electricRGB** [comment]
Hello. Thanks for this report.

We took a look through the codebase and there are no instances of `CLLocationManager` which is how an iOS application fetches a user's location. However, after some further testing, we discovered that, if you go to a website that asks for your location through WKWebView, and you grant it permission, then Firefox will show up in the App Privacy Report as using your location. This is because Firefox is the application where the request originates from, even though it's not Firefox itself doing it. Unfortunately, we don't have control over the behaviours of websites.

If you wish to disable this behaviour, you'll have to go and disable Background App Refresh for Firefox. Furthermore, when a website asks for your location, you can decline in the prompt that comes up.
