### ISSUE TITLE
Normal Tab switches to private browsing after closing the app

### ISSUE THREAD

**Issue by Oshawott22** [mozilla-mobile/firefox-ios#11292]
## Steps to reproduce
Have a tab open in normal browsing and one in private browsing open a new tab in normal browsing and close the app
### Expected behavior
When opening the app it should load into normal browsing
### Actual behavior
When opening the app it will always open in private browsing
### Device & build information
* Device: iPhone 12 Pro Max
* Build version: iso 15.5, Firefox daylight version 102.1
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4557)

**Comment by SimonBasca** [comment]
@Oshawott22 could you please share a video of the issue?

**Comment by jr-johnson-support** [comment]
The Customer Experience team has been tracking inbound for this issue and have seen 12 users noting this over the iOS reviews. https://trello.com/c/6wA6Iamb. 

Something to note though is that we have not seen additional inbound since August 4th for this issue. Myself and Dayana our Frontline agent have not been able to reproduce this on V103

**Comment by PSalant726** [comment]
Can confirm this issue is still present in the latest stable version of Firefox for iOS.

**Comment by data-sync-user** [comment]
➤ JR Johnson commented:

Odd.  It seems like this is not happening in every instance. Can confirm that both myself and our forntline agent Dayana cannot reproduce this any longer. Also we are on Daylight 103.1 as well.  So it seems like it maybe still present re: Phil’s comment. but potentially not affecting as many users as before?

**Comment by dnarcese** [comment]
https://user-images.githubusercontent.com/11432165/185482304-293067fd-3181-4609-b837-d97c90513866.MP4

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v105.0 (16844)

**Comment by PSalant726** [comment]
This issue is not completely resolved. It's true that when launching Firefox from the home screen, if the last viewed tab was not a private tab, then Firefox is launched in normal browsing mode. If, however, Firefox is launched via tapping a link in another app, the tab is still always opened in private browsing mode.

**Comment by SimonBasca** [comment]
@PSalant726 I am not reproducing the case you mentioned. If I follow the steps:
1. Go to Private browsing
2. Open tab
3. Switch to Normal browsing
4. Select a normal tab
5. Close the app
6. Open a link from notes

The link is opened in Normal Browsing. Could you please share your STR?

**Comment by SimonBasca** [comment]
I've retried the steps and I was able to reproduce the issue. Issue was logged at https://github.com/mozilla-mobile/firefox-ios/issues/11983. Thanks @PSalant726
