### ISSUE TITLE
Homepage is displayed instead of visited page after restoring from background

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11416]
## Steps to reproduce
1. Clean install
2. Visit amazon. com
3. Background the app
4. Restore the app 
### Expected behavior
- Homepage is displayed
### Actual behavior
- Amazon.com should be displayed.
### Device & build information
* Device: iPhone 13 mini (15.5)
* Build version: 104.0 (14172)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/181250171-8c38528a-58f9-42f9-8c9f-8cec087af090.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4637)

**Comment by lmarceau** [comment]
Note that if we kill the app, then the proper page is restored but we still see a "flash" of the homepage (which relates to issue #10892). 

In the current case when we background the app (and not killing the app) it's not just a flash anymore. When we background the app the navigation to the website doesn't happen. This bug is a side effect of the changes made for #11317.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, we can make sure on top of what https://mozilla-hub.atlassian.net/browse/FXIOS-4578 ( https://mozilla-hub.atlassian.net/browse/FXIOS-4578|smart-link )  needed to be tested, that private mode hides webview/information properly when going to background.

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Verifying as fixed on v104.0 (14834).
