### ISSUE TITLE
"Save" and "Done" have the same functionality

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11414]
## Steps to reproduce
1. Go to bookmark panel
2. Tap "Edit"
3. Tap on a bookmark
4. Edit the name 
5. Tap "Save" or "Done" button from the bottom of the screen
### Actual behavior
- "Save" and "Done" have the same functionality
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: 104.0 (14172)
### Notes
Attachments: 

![Picture](https://user-images.githubusercontent.com/32130829/181245398-c5df6e7e-18d9-4882-8fed-991f77afaaf3.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4635)

**Comment by SimonBasca** [comment]
In my opinion when the user taps save, the button should grey out and the screen should not be dismissed. Tapping "Done" should save and dismiss the screen.

**Comment by lmarceau** [comment]
@SimonBasca We had that behavior before right? So this would be a feature improvement?

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

the “done” is appearing b/c you are in ‘edit’ mode. pressing ‘done’ exits the edit mode while pressing ‘save” only saves edits to the bookmark and remains in edit mode.  Nicole Weber what do you want to do?

**Comment by data-sync-user** [comment]
➤ Nicole Weber commented:

Ok, I don’t think this is a big issue since “Save” is a better descriptor than “Done” here and I’d assume that most of the time people have the keyboard up and don’t see the bottom “Done” button. The bookmark editing flow as a whole might benefit from a more indepth review but this is not part of the scope here. So I’m in favor of making this a wont-fix.

Emily Wachowiak do you agree or do you want to revisit this?

**Comment by data-sync-user** [comment]
➤ Emily Wachowiak commented:

I agree with Nicole Weber - doesn’t seem worth fixing since the keyboard is almost always covering this option and that there isn’t really a negative path for the user to take or harm they can cause by choosing one over the other.

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

closing as ‘won’t fix'
