### ISSUE TITLE
The "X" icon is not displayed after changing device orientation

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11413]
## Steps to reproduce
1. Go to bookmarks
2. Tap on "Edit"
3. Tap on the Folder or bookmark
4. Change device orientation to landscape
5. Change device orientation to portrait
### Expected behavior
- The "X" icon should be displayed.
### Actual behavior
- The "X" icon is not displayed after changing device orientation
### Device & build information
* Device: iPhone 12 Pro (15.4)
* Build version: 104.0 (14172)
### Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/181241107-2ba20f9f-b3b6-44a0-91c9-1d66bb0e2019.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4634)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Laurie Marceau Note that after changing the device orientation the “X” icon is not displayed and the “Done” button changes to “Edit”

We should fix this issue as this is causing bad user experience. If the “X” icon is not displayed and the “Edit” button is displayed at the bottom, the user has to restart the app in order to dismiss edit mode.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on 104.0 (14377).
