### ISSUE TITLE
Toolbar Message telemetry is not captured

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11533]
## Steps to reproduce
1. Clean install v9000 (15189)
2. Launch Firefox
3. Wait for the toolbar message to be dispalyed
4. Tap on "Toolbar Settings" or tap on the "X" icon or tap elsewhere on the screen that close the message
### Expected behavior
The following telemetry is captured:
- Impression counts 
- Click counts on the settings link
- Click counts on the X
- Clicks elsewhere on the screen that close the message are counted
### Actual behavior
None of the following telemetry is displayed in glean:
- Impression counts 
- Click counts on the settings link
- Click counts on the X
- Clicks elsewhere on the screen that close the message are counted
### Device & build information
* Device: iPhone 13 mini (15.4)
* Build version: v9000 (15189)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4717)

**Comment by dnarcese** [comment]
@SimonBasca I am seeing data in this query https://mozilla.cloud.looker.com/explore/firefox_ios/event_counts?toggle=fil,vis&qid=YYta5orGNKQ5PM8f5xslXZ . Is there something else you are expecting?

**Comment by nishant2718** [comment]
This is really strange. Do you see Telemetry issues for the other CFRs? 

I see all codepaths leading to telemetry execute the ping, and this telemetry isn't near expiration either. I'll check with Proxyman as well. 

Also, CFRs won't report an impression count. Since CFRs can only be shown once ever, it should be enough to report telemetry of those other actions you can do with them. If you have telemetry from one of those others, a CFR had to appear for that to happen. 

It would make sense to record impression counts when we decide to show CFRs more than once.

**Comment by SimonBasca** [comment]
@dnarcese the query seems to be OK in the looker app but I am still not seeing the events in Glean. Feel free to close this if you don't consider it an issue.
