### ISSUE TITLE
Title not being filled in for synced tabs

### ISSUE THREAD

**Issue by skhamis** [mozilla-mobile/firefox-ios#11742]
## Steps to reproduce
1. Enable tab syncing on account
2. Sync some tabs
### Expected behavior

1. Tabs to have titles in the new "Firefox View" on desktop
### Actual behavior
1. title entry is empty majority of the time: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1786977

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4836)

**Comment by lougeniaC64** [comment]
I think the source of the problem might be the [Tab.displayTitle property](https://github.com/mozilla-mobile/firefox-ios/blob/main/Client/Frontend/Browser/Tab.swift#L177), as it's used to set the title property in the [toRemoteTab call](https://github.com/mozilla-mobile/firefox-ios/blob/main/Client/Frontend/Browser/Tab.swift#L386) that occurs before tabs are saved.

**Comment by nishant2718** [comment]
@skhamis @lougeniaC64 👋 !!

Quick question - there can be (edge) cases where s page wouldn't have a title, or won't have a title that's reflective of the content being shown. It could be a restaurant's menu page ([PDF](https://media-cdn.getbento.com/accounts/2f9a5949ac10f668443d4e18b37daba2/media/PjpCfRvdQ9t2uz383paP_NA_BEV_8.5x14_NYC02.pdf)), image links ([like this](https://www.jerseycityarchery.com/wp-content/uploads/2019/03/cropped-mg_0798_32555346603_o2.jpg)).

In these cases, sometimes it's more informative to use the URL. Is it possible that this can be handled by the Sync or Firefox View team?

**Comment by lougeniaC64** [comment]
@nishant2718 I'm assuming that this would be a Firefox View product call. You might want to ask in the Bugzilla ticket and maybe needinfo Gijs.

**Comment by nishant2718** [comment]
Hey @sarah-clements quick question for you, or if you can point me to the right person that'd be great too! 

Given the cases in my comment above, if I viewed those in desktop, what shows in the title in Firefox View? And is FxView able to handle cases where the title is `null`? If yes, what shows in its place?

**Comment by mhammond** [comment]
> In these cases, sometimes it's more informative to use the URL. Is it possible that if we stick to using URLs when no title exists, this can be handled by the Sync or Firefox View team?

I think this is confusing 2 different issues:

* The *source* of a tab (ie, for this bug, the iOS device) should populate the title (and iconUrl) if it is available. It's very rare that a tab will have no title and no favicon, but if it does, the device should not populate it.
* The *displayer* of the tab (ie, Firefox View on Desktop in this case) does need a policy about what to do if there's no title. It already *does* fall back to the URL - which is why this bug was reported - the user expected to see a title but did not, because the source iOS device was not providing it.

So the only action needed in this bug is to ensure that Firefox iOS is *populating* the title and icon URL when it exists, which it will in the vast majority of cases. This bug doesn't have anything to do with Firefox for iOS's "Firefox View" page, just about the synced tabs it supplies to other devices.

**Comment by mhammond** [comment]
sorry - but to be extra clear, this bug has nothing at all to do with desktop. No changes or policy decisions are required for desktop at all. I'm going to close https://bugzilla.mozilla.org/show_bug.cgi?id=1786977 and point it at this.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as verified fix on main 5c2f2081bf6d170903a6b92d63d0e592e6844d2e. Tabs to have titles in the new "Firefox View" on desktop.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Marking as fixed on v106.0 (19763)
