### ISSUE TITLE
The theme only changes after the homepage is refreshed

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#11885]
## Steps to reproduce
1. Open hamburger menu
2. Tap on "Turn on Night Mode"
3. Check the jump back in , pocket stories, recently visited
### Expected behavior
- The theme should change instantly 
### Actual behavior
- The theme only changes after the homepage is refreshed
### Device & build information
* Device: iPhone 12 Pro
* Build version: 5c2f2081bf6d170903a6b92d63d0e592e6844d2e
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/189694320-200a2946-179c-4ee9-9f6e-3e54a94544db.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4920)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Since we’re changing the theming system, I think this can be looked at as part of https://mozilla-hub.atlassian.net/browse/FXIOS-4882 ( https://mozilla-hub.atlassian.net/browse/FXIOS-4882|smart-link ) , since the currently implemented solution to update theme it will be refactored during this task.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v106.0 (19379)
