### ISSUE TITLE
Selected text menu’s “Search Firefox” don’t search for text selected in a PDF

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#11956]
# Steps to reproduce
1. Load a PDF, such as https://www.irs.gov/pub/irs-pdf/f1040.pdf
1. Select some text in the rendered PDF.
1. Select “Search Firefox” in the selected text menu. 

# Expected result 
A new tab should open with search results for the selected text.

In contrast, neither Safari’s nor Chrome’s selected text menu offers to search for the selected text. 

# Actual result
A new tab opens with my default search engine’s homepage without any search query. 

I’ve reproduce this bug in Firefox Beta version 9000 (16288) and 102.0 (11255) on my iPhone 12 running iOS 16.0.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4958)

**Comment by dicarobinho** [comment]
@lmarceau 

Sorry for the PR from above, it was a mistake.

Related to your question, after investigation: it will be not quite easy to disable/hide "Search with Firefox" feature for PDF. (from my perspective)

More exactly... menu that contains "Search with Firefox" button, is initialized in PreLaunchDependencies method, called from AppDelegate.

In order to disable/hide the button, will be necessary to change UIMenuController.shared.menuItems values.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (40029), with iPhone 15 (17.0).

As confirmed with Sorin Paraipan , “find in page” and “search with firefox” options have been removed.

!original-2A562E7E-7765-45AD-9DE2-424E7429C770.mp4|width=444,height=960!
