### ISSUE TITLE
The "Pick up where you left" CFR is incorrectly displayed on a visited page instead of the Homepage

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#11967]
## Steps to reproduce
1. Clean install the app
2. Sign in to FxA from the Onbording screen using the QR code
3. After signing in, wait for the "Pick up where you left" CFR to be displayed
4. Open the sync'ed tab by pressing on it in the "Jump Back In" section
### Expected behavior
After step 3, the active tab from desktop is sync'ed and appears correctly in the "Jump Back In" section and the "Pick up where you left" CFR is displayed
### Actual behavior
After step 3, the active tab from desktop is sync'ed and appears correctly in the "Jump Back In" section but the "Pick up where you left" CFR is NOT displayed on the Homepage.
After step 4, the CFR is displayed in the visited page
### Device & build information
* Device: iPhone 12 Pro (15.6.1)
* Build version: v9000 (19122)
### Notes
The issue is not 100% reproducible.
Attachments: 

![08_33_914Z](https://user-images.githubusercontent.com/1866605/191295539-6846fb3c-bf6b-42c4-98f6-ef5720f9a074.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4965)

**Comment by lmarceau** [comment]
Note: The sync tab CFR was added to show from BVC, triggered from the sync tab cell and not the homepage view controller. Since the homepage has no control over this CFR, no check can be added easily at the moment to make sure the CFR is shown on the homepage and not anywhere else. Hacky solution can be implemented to fix this, but I would not recommend since in the long run it would make things worst. Homepage VC should be the owner of this CFR, as it's the owner of the jump back in one.

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Verifying as fixed on v9000(19634)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v106 (19763)
