### ISSUE TITLE
FF asks for fingerprint to access passwords on iPhone that does not have touch-ID capability

### ISSUE THREAD

**Issue by mhoye** [mozilla-mobile/firefox-ios#12094]
## Steps to reproduce
Unlocking the password manager while wearing a mask asks me for a fingerprint, on a device that doesn't have a fingerprint reader. (I think most iOS devices don't now?)

![image](https://user-images.githubusercontent.com/1714458/194603166-7fac2726-a29b-4604-b44f-e326d79dcc76.png)

### Expected behavior
A more generic sentence here is probably the right thing.

### Device & build information
* Device: iPhone X, updated to current. Firefox Focus, current.
* Build version: ?
    1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5056)

**Comment by InfiniteCookie** [comment]
Since I posted the other report about this issue, I deleted the app and re-download it. When I first clicked to go to the password area, I got a request to allow face ID to be used. If I clicked past that request, then I would see the touch ID, or enter code option. I think someone clicking too quickly, as I was, may miss that first button and end up in the endless loop of impossible request for touch ID. It would be great if the app simply included someway to request that setting be reset if it goes wrong.
