### ISSUE TITLE
Nimbus FML breaks a-s local swift package manager flow

### ISSUE THREAD

**Issue by skhamis** [mozilla-mobile/firefox-ios#12243]
## Steps to reproduce
1. Follow the steps in [locally publishing a SPM from application-services](https://github.com/mozilla/application-services/blob/main/docs/howtos/locally-published-components-in-firefox-ios.md#using-the-automated-flow)
2. Build via XCode to run the app

### Expected behavior

App builds successfully 

### Actual behavior

Error in the `nimbus-fml.sh` script
```
Error: No https://github.com/mozilla/rust-components-swift package was detected.
The package must be added as a project dependency.
Command PhaseScriptExecution failed with a nonzero exit code
```
Script in question: https://github.com/mozilla-mobile/firefox-ios/blob/main/bin/nimbus-fml.sh#L79-L86

### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5163)

**Comment by travis79** [comment]
This is breaking because when using the local testing workflow for A-S/rust-components-swift it updates the Xcode project file to use a local path (`file:///`) to the `rust-components-swift` checkout. Since the script you linked only ever looks for https://github.com/mozilla/rust-components-swift, it would always hit the failure case and report that it wasn't added as a dependency, even though it is.
