### ISSUE TITLE
Empty top bar shown when it should be hidden due to scrolling

### ISSUE THREAD

**Issue by tirw** [mozilla-mobile/firefox-ios#12262]
Steps to reproduce:
- open a tab
- scroll down a bit, top bar gets hidden
- scroll up a bit, it appears
- open the keyboard by tapping on the address bar
- scroll down while the keyboard is open
- top bar should be hidden but stays open while the address bar becomes blank

https://user-images.githubusercontent.com/8298517/198751943-23392fe9-f9b8-4344-802c-20f284c75e9a.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5173)

**Comment by avijeetpandey** [comment]
Hey i want to work on this issue

**Comment by dnarcese** [comment]
@avijeetpandey feel free to open a PR if you find a fix, thanks!

**Comment by dnarcese** [comment]
note that your homepage setting needs to be set to custom URL.
@SimonBasca are you able to reproduce this?

**Comment by SimonBasca** [comment]
@dnarcese I was able to reproduce the issue on latest main v9000 (21972) by following the STR but only when New Tab is set to "Blank Page" (Settings -> New Tab -> Blank Page).

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

Bumping this ticket to a 5 due to investigation to understand all moving pieces, manual test and adding unit test to TabScrollingController

This bug is related to the rebuild constraints for BVC, TabScrollingController, URLBar and keyboard containers important part of the app. I found a fix but I want to manually test the following cases to make sure the fix doesn't cause side effects:

  * Bottom and Top URLBar on iPhone
  * Bottom and Top URLBar on iPad

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed in v9000 (29966) with iPhone 14 Plus (16.0.3).

Not able to reproduce this issue anymore, however I observed the following behavior when the toolbar is set to be display at the bottom of the page: Scrolling  down when the with the keyboard in focus will trigger the toolbar to be disappear for a few seconds and after that it is displayed (note the link is visible). Please see the attached video. 

!Video1.mp4|width=888,height=1920!

The correct behavior will be that if scrolling down the toolbar should not be visible, if scrolling up the toolbar should be visible.     

Yoana Rios Diaz do you want me to open a new issue for the above scenario or we can reopen this one.

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

yes Alina Moldovan I found a similar issue when testing this fix but I was able to reproduce in Prod (v111) that’s why I didn’t tackle as part of this ticket because this changes were already touching an important of the code so I wanted to reduce the side effects. Would you mind opening a separate ticket for this issue and I assigned to me I can take a look in the next sprint I’m already familiar with this part of the code.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Logged a different bug for the issue scrolling down issue: https://mozilla-hub.atlassian.net/browse/FXIOS-6159 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6159|smart-link )
