### ISSUE TITLE
The tab list always jumps to the beginning after closing the final tab

### ISSUE THREAD

**Issue by tirw** [mozilla-mobile/firefox-ios#12261]
Related: https://github.com/mozilla-mobile/firefox-ios/issues/7441

When most of the tabs have been inactive for a while, closing the last active tab will open the first tab, scrolling all the way to the left. The rightmost tab should be opened, as new tabs are added to the right and so the rightmost tab can be regarded as the most recent one.

Possible reproduction steps:
- Open 20 tabs, open the rightmost one
- Force-close the app
- Open the app, it will open on the rightmost one
- close the rightmost tab
- app will scroll to the leftmost tab

Possible fix:
change this line to `.last`:
https://github.com/mozilla-mobile/firefox-ios/blob/1d5fda734c6349ae2735def7715c19edfc806701/Client/Frontend/Browser/Tab%20Management/Tab.swift#L14

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5172)

**Comment by adudenamedruby** [comment]
Unable to reproduce. See video:
![4A29AA15-DC73-4CF7-8935-6D4EAB33BBD6_1_102_o](https://user-images.githubusercontent.com/11182210/206504258-561bc517-707d-4997-a73f-a2f8d7532fb0.jpeg)

**Comment by adudenamedruby** [comment]
Heya, so I took a look again and I can't seem to reproduce the issue at all, even given new steps (see video). I'm gonna close the ticket until we have exact steps. Logic wise, the code is doing what it's supposed to be doing, and tests exist here.

The proposed solution of changing `var recent = tabs.first` to `tabs.last` is not really viable as that's not the behavior we want and is arbitrary. Ideally, if you close a tab at any position, you should be going to the most recent tab, which can be in any position, rather than the last tab. In other words, if you have 90 tabs, and you close the second tab, it shouldn't be going to the 89th tab (unless that's the last tab that you most recently used).

As for the rendering lag... that's out of our hands: you're taxing the CPU with 128 threads at 100%. We can't really do anything about that.


https://user-images.githubusercontent.com/11182210/209687400-e439bbbd-8527-4684-a024-47cdcb2060dc.MP4
