### ISSUE TITLE
can't build with xcode 13.4.1.

### ISSUE THREAD

**Issue by dong2dong3** [mozilla-mobile/firefox-ios#12328]
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/13480371/200179083-4f6bc927-1944-4a66-a40e-4f84c9814467.png">

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/13480371/200178620-79cd2737-c64a-43f1-b54c-5452252aa1d9.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5215)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FXIOS-5215

**Comment by lmarceau** [comment]
Hello @dong2dong3, have you tried:
- Making sure you ran `bootstrap.sh` and that it runs successfully (no errors appearing in the logs).
- Reset package caches
![Screen Shot 2022-11-07 at 10 35 27 AM](https://user-images.githubusercontent.com/11338480/200350581-f94407a2-496d-461a-a56e-435d3e74fcba.png)

I'll close this ticket since this should be more of a [discussion](https://github.com/mozilla-mobile/firefox-ios/discussions). Thanks!
