### ISSUE TITLE
Keyboard is dismissed by the Jump back in CFR and also dismisses the CFR

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#12406]
## Steps to reproduce
1. Visit a page
1. Open a new tab
    1. Expected behavior

* A new tab is opened with the keyboard displayed.
    1. Actual behavior
* Keyboard is dismissed by the Jump back in CFR and also dismisses the CFR
    1. Device & build information
* Device: iPhone 12 Pro
* Build version: 108 (22078)
    1. Notes
Attachments: 

https://user-images.githubusercontent.com/32130829/202163015-a59c29a1-df89-48ff-a743-3f55f3df3d69.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5275)

**Comment by nishant2718** [comment]
I believe the expected behavior should be that the keyboard is dismissed, and the JumpBackIn CFR remains displayed. 

Do you have any additional setup steps to repro this? Were you logged into sync? Private browse recently? Do we have to make Sure Recently Visited displays first, for this issue to appear? Do we need to be on the latest iOS version?

**Comment by nishant2718** [comment]
@SimonBasca besides the iOS version, I've played around with the other variables and can't repro. Could you provide STR when you get the chance?
