### ISSUE TITLE
Haptic feedback is always given, ignoring the system setting

### ISSUE THREAD

**Issue by varjolintu** [mozilla-mobile/firefox-ios#12402]
## Steps to reproduce
* Disable any haptic feedback from iOS (Keyboard Feedback, System Haptics etc.)
* Try opening a new link to background in Firefox by long pressing the link to get the options list open

### Expected behavior
Firefox doesn't give any haptic feedback if system has disabled it.

### Actual behavior
Firefox gives haptic feedback with sound, or a physical feedback if in silent mode. It overrides the system setting.

### Device & build information
* Device: iPhone 12 Mini
* Build version: Firefox 107.0 (21907)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5271)

**Comment by varjolintu** [comment]
Hopefully there's some progress with this :) It's an annoying bug, especially if you are in a silent space (and phone in silent mode) and the browser still gives you a silent feedback that can be heard.

**Comment by lmarceau** [comment]
Hello! I had a look and this is interesting. With the following settings:
![IMG_1474](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/2e61959f-4b1a-4af4-b0e6-740b2b7fd1e0)

I get all of our custom haptic feedback OFF in the application (since we use the built-in [`UIFeedbackGenerator`](https://developer.apple.com/documentation/uikit/uifeedbackgenerator) and this check is done automatically for us by Apple) **apart from long pressing on a webpage**. We're not overriding this behavior for the webpage haptics. We rely on Webkit for our web engine, and that setting doesn't seem to have effect there. You can double-check by trying the same long press action with Safari. With those same settings I get haptic feedback on text selection and long presses in a webpage in Safari.

Anyhow, you can turn off the haptic feedback on webpages by going to `Settings → Accessibility → Touch → and turn off Vibration`. I am not sure if there's another way to turn this off, but at least our behavior is consistent with Safari. It doesn't seem we can do anything more about this.

**Comment by varjolintu** [comment]
Thanks for the feedback. It really seems this is a bug in the Webkit engine itself, and I can reproduce the behavior also in Safari.

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

Closing as this seems to be a bug in WebKit and therefor beyond our control.
