### ISSUE TITLE
Pinned Tabs are not showing on new tab page

### ISSUE THREAD

**Issue by u1traviolet** [mozilla-mobile/firefox-ios#12461]
## Steps to reproduce
go to a webpage, click on the hamburger menu, and press 'Add to Shortcuts'

### Expected behavior
pinned tab should appear on new tab page

### Actual behavior
no pinned tab on new tab page

### Device & build information
* Device: iPhone SE 3  iOS 16.1.1
* Build version: Firefox 107.1 (22302)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5304)

**Comment by u1traviolet** [comment]
> @u1traviolet Does the tab ever show up on your homepage? Is this only happening when you open an existing homepage or also when you open a new tab?

Hi, a tab I use a lot will turn up on my homepage, I can then pin it as normal by long pressing the icon. This about pinning a page I don't have on my homepage yet

**Comment by dnarcese** [comment]
@u1traviolet sorry thats what I meant. After you click 'Add to Shortcuts' does it ever show up, maybe the next time you open the app?

**Comment by lmarceau** [comment]
I can reproduce in both production and developer version of the app. Once it's not showing, it's never showing in the shortcuts (restarting the app has no effect). Haven't looked into the cause of this yet, but it's easily reproducible at least.

**Comment by u1traviolet** [comment]
> @u1traviolet sorry thats what I meant. After you click 'Add to Shortcuts' does it ever show up, maybe the next time you open the app?

no it does not. i've even uninstalled the app and re-downloaded it, it still happens. What happens when you try it?

**Comment by tarikeshaq** [comment]
The problem is that in https://github.com/mozilla-mobile/firefox-ios/blob/16e748497f0e337e19ef5ff670e34bd2b7816d6a/Client/Frontend/Browser/MainMenuActionHelper.swift#L746-L752

We `sql.getSites()` - which in https://github.com/mozilla-mobile/firefox-ios/blob/16e748497f0e337e19ef5ff670e34bd2b7816d6a/Storage/SQL/SQLiteHistory.swift#L158-L161

Tries to join with the old favicon table - but since we no longer use that table, there is a good chance the site doesn't exist in the favicon table and the call returns an empty list of sites. 

We should probably remove the call to `getSites` altogether since we already have the URL and title at that point, and it seems to me the call was purely used to get favicon data - in #12420 I do that, but that's not gonna land for a bit - I'll create another PR for this because it's easy enough 😄

**Comment by u1traviolet** [comment]
Excellent, glad to know it's going to be addressed.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on 109 (24441)
