### ISSUE TITLE
Fix warnings @Sendable in ExtensionUtils

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12506]
!Screen Shot 2022-11-25 at 11.20.46 AM.png|width=531,height=138!

![Screen Shot 2022-11-25 at 11 20 46 AM](https://user-images.githubusercontent.com/11338480/204025654-1b5a30bd-afd2-492d-82e3-bfbf614ec973.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5331)

**Comment by palayemre** [comment]
`NSExtensionItem` is a reference type so, not `Sendable` by default.

However, there is an unavailable conformance of `NSExtensionItem` to `Sendable` in Foundation library, I guess it hasn't been implemented yet.

<img width="724" alt="Screenshot 2022-12-29 at 18 50 56" src="https://user-images.githubusercontent.com/17731451/209977809-ea06412d-8e6d-473a-8763-0465ee6ede76.png">

Same conformance can be added to the project without any availability condition, this would remove the warning but I don't think it would be smart to do, in some places where NSExtensionItem send as closure parameter, we may want to get warnings to detect possible race conditions

`extension NSExtensionItem: @unchecked Sendable { }`

Feel free to suggest anything to remove the warning please.
Thanks!

**Comment by lmarceau** [comment]
Well, it seems it would be that we have to make sure there's no race condition happening ourselves so we can mark it as `@unchecked`. I read a bit [here](https://www.avanderlee.com/swift/sendable-protocol-closures/) about @Sendable but would require more time to have a great way of solving this. If you're up for the challenge you can propose a way to make this thread safe, otherwise we can also check what are the risks of making this @unchecked without thread safety in mind to highlight our decision better about those warnings.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Laurie Marceau We’ve logged this https://github.com/mozilla-mobile/firefox-ios/issues/13209 ( https://github.com/mozilla-mobile/firefox-ios/issues/13209|smart-link )  while testing. It seems that on my side send tab is not working correctly when sent from desktop to iOS.
