### ISSUE TITLE
[Intermittent][Beta] Search suggestions not showing history results

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#12530]
## Steps to reproduce
1. Visit 7 articles from the same news site (I used www.ziare.com)
2. Bookmark two of them.
3. Restart the app
4. Right after the app starts start typing in the URL bar to get the bookmarks and history search suggestions (I typed "zia")
5. Check the search suggestion list.
### Expected behavior
The list should show two bookmarks and three history search suggestions .
### Actual behavior
The list shows no history search suggestion.
### Device & build information
* Device: iPhone 12 Pro 
* Build version: Beta 108.0 (22972)
### Notes 
1. This issue reproduces intermittently. 
2. It reproduces way easier on an older build (22410)
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5344)

**Comment by badboy** [comment]
For me this started with 108.0
I did run a small experiment, flipping `search-highlights` to `false` ([this `search-highlights`](https://github.com/mozilla-mobile/firefox-ios/blob/a1e85352bd164afc1695842ef5f4fc0abeace89f/nimbus.fml.yaml#L173-L176)) and that seems to have "fixed" it.
This triggers this code path: https://github.com/mozilla-mobile/firefox-ios/blob/a1e85352bd164afc1695842ef5f4fc0abeace89f/Client/Frontend/Browser/SearchLoader.swift#L124-L126

I'm not really sure why though. That code has been around for a bit longer I think.

**Comment by badboy** [comment]
> This relates to epic [mozilla-hub.atlassian.net/browse/FXIOS-2903](https://mozilla-hub.atlassian.net/browse/FXIOS-2903). If search highlights feature is enabled, we fill in the search view with 3 search highlights instead of history sites. I guess with some changes there's a bug that was introduced and search highlights are sometimes not filled in (like in your case).

Yeah, I don't have a clue _why_ just disabling that feature makes this work again, given it has been around for a while.
Looking in the commit log between 107 and 108 there's one other change touching code around it: e4400e9d5a0180d6ad4cb08e879b4d9ce836820b
Maybe that's causing some of the problems, but I'm not familiar enough with it (nor have the time to dig deeper) to figure it out.

**Comment by tarikeshaq** [comment]
OK so I figured it out, and it's related to https://github.com/mozilla-mobile/firefox-ios/commit/e4400e9d5a0180d6ad4cb08e879b4d9ce836820b

Some context, I'll have a PR up shortly. This isn't  urgent because the feature is disabled in release builds but:

- History Highlights are stored in the `places.db` managed by application services
- Whenever we get a new tab, we note history metadata observations
- **If the nimbus feature is enabled**, we go and:
    - [retrieve the history metadata we have](https://github.com/mozilla-mobile/firefox-ios/blob/16e748497f0e337e19ef5ff670e34bd2b7816d6a/Client/Frontend/Home/HistoryHighlights/HistoryHighlightsManager.swift#L142-L150)
    -  [filter to make sure we don't show any open tabs or sponsored content that are already in the suggestions](https://github.com/mozilla-mobile/firefox-ios/blob/16e748497f0e337e19ef5ff670e34bd2b7816d6a/Client/Frontend/Home/HistoryHighlights/HistoryHighlightsManager.swift#L104-L133)
    -  [Filter to only include highlights that include within the URL or title the search term](https://github.com/mozilla-mobile/firefox-ios/blob/16e748497f0e337e19ef5ff670e34bd2b7816d6a/Client/Frontend/Home/HistoryHighlights/HistoryHighlightsManager.swift#L85)
- If the feature is enabled, we do **not** append the "normal" history suggestions from the browserdb.
- in https://github.com/mozilla-mobile/firefox-ios/blob/16e748497f0e337e19ef5ff670e34bd2b7816d6a/Client/Frontend/Browser/SearchLoader.swift#LL98C18-L98C18 I added an `interruptReader` as a mechanism to interrupt **previous** searches not to overwhelm the places.db. However, since in iOS we only have exactly one places reader that is shared between bookmarks, search highlights and **soon** history. That ends up interrupting the search for history highlights. because at that point in time, it's possible the search highlights query started already.
- I'll have a fix up shortly so we only run the `interruptReader` if the search-highlights is not enabled and if the places history is being used

**Comment by csuciu** [comment]
Cannot reproduce this issue on v109 (24441). Verifying as fixed.
