### ISSUE TITLE
Red Caution Symbols in Password Manager

### ISSUE THREAD

**Issue by bigdom1200** [mozilla-mobile/firefox-ios#12824]
These red symbols are showing up next to passwords in my password manager. It does not tell me why they are flagged or what can be done about them. 

![image](https://user-images.githubusercontent.com/121684976/210092244-c848a515-22af-4fe4-a221-50f5be3104d4.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5510)

**Comment by lmarceau** [comment]
Hello @bigdom1200, thanks for opening this issue.

This icon appears when there's a potential breach on this password domain. Here's how it works:
- Let's say I have a login password for Twitter in Firefox for iOS that I created on December 1st 2022. 
- In my example scenario, let's say there's a breach on Twitter on January 1st 2023. 
- Using the Firefox monitor `https://monitor.firefox.com/`, Firefox for iOS will be aware of that breach and when it happened.
- Since my Twitter password was filled in before January 1st 2023, this red icon will appear warning me of a potential breach for this password.

So normally when you click on those logins you would see more information in the detail view, but as you noted that information doesn't appear (this is a bug). 

From the code, I see it should appear at the top of the view (where I put a red rectangle).
![Screen Shot 2023-01-03 at 12 41 22 PM](https://user-images.githubusercontent.com/11338480/210411613-0b4129f4-0c9c-4729-9468-30e94d7df591.png)

![Screen Shot 2023-01-03 at 12 41 38 PM](https://user-images.githubusercontent.com/11338480/210411643-94ff8f53-0623-4979-a0ac-0839a2b7ca98.png)

If you want more information on Firefox monitor: https://monitor.firefox.com/about

Note: it seems to be a constraint problem as to why the `BreachAlertsDetailView` isn't showing in the `LoginDetailViewController`.

**Comment by hhhhhhamerica** [comment]
i'm hashing this exact same problem it's so frustrating i can't find a single firefox article talking about it

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v112 (29529) with iPhone 13 Pro (15.7.1).

Please note that verification for this bug is not really easy but with forced code, we generated the following:

!image-20230315-112403.png|width=1170,height=2532!

!image-20230315-112410.png|width=2532,height=1170!

Laurie Marceau based on your example, I’ve tried to manually set the device time to 2022, I added a Twitter account and then I set it to automatically, but it didn’t work and I was not able to generate the above notification. Is there an easy way to test it without waiting in real life for a site to be breached? I can’t really predict that.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

I think having an option like that will help in future testing because we might have other things that will be hand in hand with the monitor and it’s a very good way to test it without spending too much time on it because it’s hard to have a real scenario like that.

I will keep an eye on this maybe I can find a real scenario that can be tested but I’m not too confident.

Thank you Laurie Marceau(*g) 🙇‍♂️
