### ISSUE TITLE
Automate the process to export strings

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#12822]
I would like to bring this up to the dev team so that we can explore how feasible this would be and if it would be helpful for the team.

Similar to the string imports that happen regularly, we could have a github action for the export. It does not have to run automatically, but triggered when needed, like the string import to release branches.

Looking into the current manual process, I came with these stpes, but wanted to double check in case I'm missing some details.

1. From firefox-ios repo create a branch from main

2. First, we need to do a string import
`./import-strings.sh`

3. Then we do the export by running this command:
```
cd LocalizationTools && swift run LocalizationTools \
  		--export \
  		--project-path "../Client.xcodeproj" \
  		--l10n-project-path ../firefoxios-l10n
```
4. From firefoxios-l10n folder run this [script](https://github.com/mozilla-mobile/firefox-ios/wiki/Localization-Process#manual-exports)
This will create a separate commit for each locale’s file that has changed
5. Create a PR with those commits on firefoxios-l10n

Not sure who in the team is more familar with this... ccing @adudenamedruby (since I see a commit from you in LocalizationTools) and @flodolo as the l10n import/export expert... Thank you in advance!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5509)

**Comment by flodolo** [comment]
The process is already automated (in the l10n repository) for both Firefox and Focus, and runs once a week (or can be triggered manually if needed).

e.g. for FIrefox
https://github.com/mozilla-l10n/firefoxios-l10n#string-updates
https://github.com/mozilla-l10n/firefoxios-l10n/blob/main/.github/workflows/import_strings.yml

That wiki page is out of date at this point
https://github.com/mozilla-l10n/firefoxios-l10n/blob/main/.github/workflows/import_strings.yml#L56-L69

**Comment by flodolo** [comment]
For Focus
https://github.com/mozilla-l10n/focusios-l10n/blob/main/.github/workflows/import_strings.yml

The workflows are different, because the extraction logic for en-US lives in the code repository, but the rest is similar:
1. Extract strings (using scripts in the code repo)
2. Update other locales (via Python scripts)
3. If needed, do other changes to locales (e.g. "translate" en-US in Firefox, copy over `es-ES` as `es`)

**Comment by isabelrios** [comment]
Hey @flodolo, I'm a bit confused with this then.. as far as I know devs do the string export manually, at least for iOS, can they run this github action when need instead? 
Also, even though in line [L58](https://github.com/mozilla-l10n/firefoxios-l10n/blob/b76fbcd0f3611f2afa66ea8b08c26583471b9460/.github/workflows/import_strings.yml#L58) it uses export, the github action is called import strings, should it be export?

Thanks!

**Comment by isabelrios** [comment]
If I go to https://github.com/mozilla-l10n/firefoxios-l10n/actions/workflows/import_strings.yml I don't see an option to trigger the workflow, should it be there?
I was expecting something like in the import strings: https://github.com/mozilla-mobile/firefox-ios/actions/workflows/import-strings.yml: 
<img width="1006" alt="Screenshot 2022-12-30 at 16 43 31" src="https://user-images.githubusercontent.com/1897507/210087894-9b8ca070-94fe-418f-aa9f-fa5ffcdba568.png">

Sorry for asking a lot, want to be sure what is automated and how we can use it to save time by removing manual tasks. Thanks!

**Comment by flodolo** [comment]
It's _export_ from the point of view of the code repository, it's _import_ from the point of view of the l10n repository (where it lives). It used to be called "export" there, but it's just confusing, because it doesn't export anything from the l10n repository. It could be called "expose new strings", but that's a matter of semantic, and I'm afraid of breaking workflows and bookmarks at this point.

You don't have permissions to run the action, that's why you don't see the button. l10n PMs have it, and also Roux on the iOS side (maybe we added others, but I don't have access to check at the moment). In case you need it, just let me know and I'll be happy to add you.

We haven't run manual string export from the code repository since last summer. BTW, I [did ask](https://github.com/mozilla-l10n/firefoxios-l10n/pull/143#issuecomment-1217480096) to update the documentation at some point.

The last PR exported manually was https://github.com/mozilla-l10n/firefoxios-l10n/pull/137 (July).

**Comment by isabelrios** [comment]
I see...understood, thanks! No need to change the naming and I don't need access either to run the github action at the moment.

**Comment by lmarceau** [comment]
Thanks @flodolo, the documentation was updated [here](https://github.com/mozilla-mobile/firefox-ios/wiki/Localization-Process) already.

And for @isabelrios, let me know if we need to chat about this. There's other improvements for strings processes we can automate if that's what you're about!

**Comment by isabelrios** [comment]
Thanks! sure @lmarceau let's talk about this... I'm closing this issue then sorry for the noise caused... 🙏
