### ISSUE TITLE
Fix deprecated warning .alert in AppDelegate in iOS 14.0

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#12882]
We’re using deprecated .alert under AppDelegate in UNUserNotificationCenterDelegate which is deprecated in iOS 14.0. We should migrate to using newest API while keeping same behavior, so the day we drop support for iOS 13.0 we’re already using the right API

!List or banner ?.png|width=452,height=62!

![List or banner ?](https://user-images.githubusercontent.com/11338480/211057213-3aedbffe-0753-4755-8535-354bd8078671.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5560)

**Comment by lmarceau** [comment]
@dnarcese This is called when the app is in the foreground. New API states either we use the `.banner` or `.list` instead of `.alert`. This means either we ask the notif to show as a banner or in the notification center ([documentation](https://developer.apple.com/documentation/usernotifications/unnotificationpresentationoptions)). Which one would you prefer?

**Comment by dnarcese** [comment]
@lmarceau sorry, what is an example of a type of notification it would show?

**Comment by lmarceau** [comment]
It's for a case to show for example a tab notification. Right now it shows as a banner and notification center. So I guess we could keep that, or change it if you wish to be one or the other only.

**Comment by dnarcese** [comment]
I don't see a reason to change it now
