### ISSUE TITLE
The reader mode web view doesn't properly reflect the theme change

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#12981]
## Steps to reproduce
1. Open an article in reader mode.
2. Go to FF settings and manually change the theme.
3. Return to the reader mode view.
### Expected behavior
The reader mode web view should show the theme that was previously selected.
### Actual behavior
The reader mode web view doesn't change theme until re-opening the app.
### Device & build information
* Device: iPhone 12 Pro (16.2)
* Build version: 110.0 (26107)
### Notes
The bottom toolbar, URL bar and reader mode toolbar are updated correctly
Attachments: 
![18_00_204Z](https://user-images.githubusercontent.com/1866605/213408138-8ea09153-7c3c-40f8-b37d-0e0be95c04df.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5619)

**Comment by KevinW711** [comment]
The reader mode relationship to the device theme has been an issue for some time now. The biggest issue I've encountered is, when the device and Firefox are set to dark theme, changing the reader mode to light theme (which I prefer all the time) does not stick. When minimizing and going back to the app, changing the font size, etc., the reader mode will revert back to the device theme. A nagging bug that I hope will be fixed in short order.

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Reader mode setting does not persist when you close the app.

Current behaviour is that reader mode will keep the same theme within the same session, and not follow the system theme.

To address this issue, let’s persist the reader mode setting and not change it based on the system theme.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (29966) with iPhone 13 Pro (15.7.1).
This issue will still be checked when an official RC build will be created for the fix version.
