### ISSUE TITLE
IOS app hanging every time I use it within 1 minute of use

### ISSUE THREAD

**Issue by tej** [mozilla-mobile/firefox-ios#13003]
I just switched to IOS from Android and the Firefox app hangs every time I use it.
Browsing a webpage and it hangs.
Signing into Firefox account and it hangs
Google searching it hangs
Sometimes on the main new tab page it hangs

Every time it happens it's within the first 1-2 minutes of me using the app. On some occasions it suddenly closes, but most of the time it just hangs and I have to close out of the app and relaunch it. Relaunching also doesn't fix the issue, it only delays it because after opening it back up and using it for another minute, it hangs again. And it's a constant cycle if I want to keep using it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5627)

**Comment by dnarcese** [comment]
Hi, would you able to send us your Firefox logs following these steps (https://github.com/mozilla-mobile/firefox-ios/wiki/How-to-get-your-device-logs#access-firefox-logs-via-files-app-on-ios-device) so that we have more information as to what is happening here, thanks!

Also, which device, iOS version, and Firefox version are you using?
