### ISSUE TITLE
Shortcuts are pinned 📌 by default  

### ISSUE THREAD

**Issue by clarmso** [mozilla-mobile/firefox-ios#13066]
## Steps to reproduce

1. Open Firefox on iPhone or iPad. (iOS simulator is ok.)
1. Enter "mozilla.org" to the awesome bar from a new tab and hit enter.
1. Tap hamburger menu. Tap "Add to Shortcuts 📌 ".
1. Open tab tray and tap trash can (🗑️). Tap "Close All Tabs".
1. Long press Mozilla's icon. 

### Expected behavior

The menu offers an option for "Pin 📌 ".

### Actual behavior

Mozilla is already pinned. The menu offers an option for "Unpin".

<img width="200" alt="Screenshot 2023-01-30 at 4 04 18 PM" src="https://user-images.githubusercontent.com/1740517/215594843-db848028-77e3-49e3-a609-c331408573b2.png">

### Device & build information
* Device: iOS 14 Pro (iOS simulator)
* Build version: (From main today)
### Notes
From an older test, the steps says that a shortcut is not pinned by default. The test in question require an update. Could someone please confirm if shortcuts and pinned items are the same on iOS?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5659)

**Comment by SimonBasca** [comment]
@clarmso I believe this is expected behavior.  When visiting a site, opening the menu and tapping "Add to Shortcuts 📌 " the site is added to the Website Shortcuts with a 📌  icon. The Website Shortcuts are can be seen on the homepage. When long pressing on a website shortcut that has been pinned, the option to "Unpin" is displayed.

![Sceenshot](https://user-images.githubusercontent.com/32130829/215726992-3ab9d7ef-7772-43a0-8369-eeb592d54348.png)

**Comment by clarmso** [comment]
@SimonBasca Thanks for confirming such a behaviour. Let me close the issue.
