### ISSUE TITLE
Search suggestions not beeing displayed can cause a crash

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#13206]
## Steps to reproduce
1. Open a new tab
2. Type "goo" -> Observe the search suggestions not being displayed.
3. Close app from app switcher
4. Re-launch the app
5. Open a new tab
6. Start typing in the URL bar
### Expected behavior
- Search suggestions should be displayed.
### Actual behavior
- Search suggestions are not displayed and after step 6 the app will sometimes crash.
### Device & build information
* Device: iPhone 13 mini (16.1)
* Build version: latest main c09916f865f49e84ad114f734a06c56d2d1e95c0
### Notes
Attachments: 

![image](https://user-images.githubusercontent.com/32130829/218431240-a7521e54-fc30-4896-829a-1e7a2b4261b1.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5744)

**Comment by isabelrios** [comment]
Expected behaviour:
![Simulator Screen Shot - iPhone 14 - 2023-02-13 at 11 37 15](https://user-images.githubusercontent.com/1897507/218436003-4bcc08da-2d12-4a66-8879-97f3912274a3.png)

On latest main:

![Simulator Screen Shot - iPhone 14 - 2023-02-13 at 10 32 12](https://user-images.githubusercontent.com/1897507/218436140-6896ac86-da0b-485e-9d97-b3fc5fdbc82c.png)


The automated test https://github.com/mozilla-mobile/firefox-ios/blob/c09916f865f49e84ad114f734a06c56d2d1e95c0/Tests/XCUITests/BookmarkingTests.swift#L132 is failing due to this empty suggestion list.

**Comment by abodea** [comment]
Might be related https://github.com/mozilla-mobile/firefox-ios/issues/13211.

**Comment by lmarceau** [comment]
@abodea yes it's the same crash 👍 I have a fix open for this. Thank you!

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v9000 (28110)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on v111 (28148)
