### ISSUE TITLE
Firefox crashes one time after clearing recent history while syncing

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#13266]
## Steps to reproduce
1. Login to FxA on desktop
2. Login to FxA on iOS
3. On iOS go to history
4. Swipe down on the list to sync
5. While the list is syncing, tap the trash can icon
6. While the list is syncing, tap "clear today"
### Expected behavior
- History should be cleared
### Actual behavior
- Firefox crashes one time.
### Device & build information
* Device: v111 (28263)
* Build version: ?
### Notes
Attachments: 

[Client-2023-02-16-061904.ips.zip](https://github.com/mozilla-mobile/firefox-ios/files/10756978/Client-2023-02-16-061904.ips.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5783)

**Comment by lmarceau** [comment]
The stack trace here is very interesting, as this seems to relate to ones we see from Xcode reports. Thank you @SimonBasca this is very helpful, I'll have a look into this.

**Comment by lmarceau** [comment]
@SimonBasca I tried reproducing. I was scrolling in the History panel, then while scrolling clicked on the trash icon to delete my history. Tried with simulator and real device, so far no luck. Is this a bug that is hard to reproduce?

**Comment by SimonBasca** [comment]
@lmarceau this is indeed a hard to reproduce bug. I was able to reproduce by following the STR but only a few times after a clean install and after the first sync with FxA..

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, Laurie Marceauas this issue is not easy to reproduce and I didn’t encounter any issues regarding this, how we should proceed with this bug? 
Should I close it as verified in v111 as we have the last RC and the release will happen soon, or we let it open for the future and keep adding fixed versions? 
I would say closing it now and then if something will appear we can add a new bug or re-open this.

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Let’s open a new bug if we see it again
