### ISSUE TITLE
Shortcuts behaviour is inconsistent

### ISSUE THREAD

**Issue by pseandersson** [mozilla-mobile/firefox-ios#13316]
## Steps to reproduce
1. Have a shortcut list (not pinned one) in Firefox version less than v110 (I don't know which one I had before the upgrade)
1. Upgrade to v110
1. Remove sponsored shortcuts
1. Browse your favorite homepages over days

### Expected behavior
My shortcuts should be kept between the version-upgrade. An additional row may have been added to show the sponsored items, in case it was a change between the versions.

At least a way to sort the shortcuts manually when it becomes so complex.

### Actual behavior
When updated to Firefox iOS v110 on iOS 16.4.1, all my shortcuts has more or less disappeared and also been replaced with sponsored ones.
I start to remove the sponsored etc, to get as close as possible. But instead of filling out with my previous shortcust, empty rounded rects were displayed. After a time of use, all shortcuts were populated again. But then when starting browsing a shortcut, it could disappear as a shortcut. So from having 8 shortcuts it could go to 5 shortcuts, this is very annoying, since I have been used to have my shortcuts and this reveal/disappear confuses me. The pinning feature makes it hard to order them, I have to think twice or thrice in order to get them as I want them, which takes to much effort from me.

### Device & build information
* Device: iPhone 12 Mini
* Build version: 27761
    1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5824)

**Comment by tarikeshaq** [comment]
Thanks a ton for filing this @pseandersson! This most likely has the same underlying bug as [#this one](https://github.com/mozilla-mobile/firefox-ios/issues/13031)

in the meantime, it might help to pin any top sites you'd like to stay put. The top sites could change with your browsing to reflect sites used recently/frequently (Although them changing in the way you're seeing it is most likely caused by the bug linked above)

To pin a top site:
- You can press the hamburger menu when on the site and tap "Add to Shortcuts"
-  You can also hold it while it's in your topsites and tap "Pin"

Unlike regular history-based top sites, Pinned top sites shouldn't move unless you move them!
