### ISSUE TITLE
Remove SwiftyJSON from SyncTelemetryUtils.swift and SyncTelemetry.swift

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#13382]
* Remove SwiftyJSON dependency
* Adjust any unit tests where needed
* Add unit tests to cover code not covered

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5864)

**Comment by Ri-ishi** [comment]
Hi I would like to work on this issue.

**Comment by FilippoZazzeroni** [comment]
Hi i would like to contribute to this issue. I've already removed successfully the SwiftyJSON depencency from the file above but i was wondering if the SyncTelelemetry package is still used inside the application beacuse i see most of the Telemetry is recorded using Glean or Telemetry package. Does this issue is still open ?

**Comment by lmarceau** [comment]
@FilippoZazzeroni The task refers to the files `SyncTelemetryUtils.swift` and `SyncTelemetry.swift`. I see the SwiftyJSON dependency is still used inside those files. [Example 1](https://github.com/mozilla-mobile/firefox-ios/blob/c2ff742d13295806f85c7d949be5febe47bc78c1/Sync/SyncTelemetryUtils.swift#L245), [Example 2](https://github.com/mozilla-mobile/firefox-ios/blob/c2ff742d13295806f85c7d949be5febe47bc78c1/SyncTelemetry/SyncTelemetry.swift#LL61C26-L61C26).

SyncTelemetry is still used yes.

**Comment by FilippoZazzeroni** [comment]
@lmarceau ok thankyou. yes i have removed them locally, i still didn't create a PR for that, i'm going to do it.

**Comment by lmarceau** [comment]
Closing as those files don't exists anymore
