### ISSUE TITLE
Unable to access Nordstrom

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/firefox-ios#13547]
## Steps to reproduce
1. Open up Firefox beta
1. Type Nordstrom to search for it
1. Click on the serp link
1. Shown weird webpage telling me I can’t use the website

### Expected behavior
I can shop for shoes on Nordstrom

### Actual behavior
Something is prevent the site from loading. Works fine in safari. TP on or off doesn’t help. 

### Device & build information
* Device : ? 
* Build version: ? 
* First seen version: ? 
    1. Notes
Attachments: 

![47E23932-B9D4-4380-8A54-90D795150AFE](https://user-images.githubusercontent.com/287322/224501260-9dde0de8-8381-4d22-a6cb-409b38f7f93d.png)
![41B5BA52-3100-4A08-A6CB-8CEAA2639E1F](https://user-images.githubusercontent.com/287322/224501265-dffc2e1b-a156-4ae3-9423-b67775bb05f9.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-5961)

**Comment by Tomatoshadow2** [comment]
I was able to reproduce the issue, with the steps above, no difference in using a different IP address through my VPN.

**Comment by OrlaM** [comment]
Can you specify if it is nordstrom.com or nordstrom.ca you are trying to access?
The Canadian Nordstrom site has been shut down because they are ceasing operations in Canada, so if the screenshot above is from the Canadian site then it's likely they just had a bug while shutting things down. The site now shows a message about the shutdown.

**Comment by Tomatoshadow2** [comment]
@OrlaM for me AFAIK, it was Nordstrom.com at the time, that was displaying this message, as I would load it from Firefox suggest.
