### ISSUE TITLE
Review CredentialWelcomeViewController delegate to be weak 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#13692]
Noticed we have some delegates that aren't marked as weak in the code. Delegates should normally be weak to avoid reference cycles. This task is to review CredentialWelcomeViewController delegate to mark it as weak, and add tests for it.

To add tests for leaks in our code, you can use `trackForMemoryLeaks`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6042)

**Comment by cschumake** [comment]
I do not see a pull request for this issue. I will begin working on it.

**Comment by parthv21** [comment]
I am trying to get started with working on open source projects and this seems like a good first task. 

Am I correct in assuming this is the change we want to test? 
```
class CredentialWelcomeViewController: UIViewController {
    weak var delegate: CredentialWelcomeViewControllerDelegate?
```

Which would avoid a retain cycle here: 
```
    func showWelcome() {
        let welcomeVC = CredentialWelcomeViewController() <-- strong instance of CredentialWelcomeViewController
        welcomeVC.delegate = self
        self.currentViewController = welcomeVC
    }
```

I was trying to find if there were any existing tests for `CredentialWelcomeViewController`. But could not find any under the `Tests` folder. Can someone help me find current tests or guide me w.r.t the test organization of tests? Thanks!

**Comment by lmarceau** [comment]
Hello @parthv21, yes this is the change we want to test. Indeed there's no existing tests for `CredentialWelcomeViewController` so we would need to create the file for it. Since there's also no unit tests at all for this target, we need to add the possibility to do so. I opened a draft PR so our team can start discussion on adding them. Once that's done we can do this task. 

In the meantime, you could maybe look into https://github.com/mozilla-mobile/firefox-ios/issues/13690? And here are some example of other delegate PRs equivalent you can look into for inspiration https://github.com/mozilla-mobile/firefox-ios/pull/13634, https://github.com/mozilla-mobile/firefox-ios/pull/13463. Hope this helps, let us know if you have any questions.

**Comment by parthv21** [comment]
Took a look at your PR. Thanks for setting it up. 

Locally I wrote a test but it is failing to build due to these errors. 

```
Undefined symbol: _$s18CredentialProvider0A29WelcomeViewControllerDelegateMp
Undefined symbol: _$s18CredentialProvider0A21WelcomeViewControllerCMa
```

**Comment by lmarceau** [comment]
Yes, as explained in the description of the PR, it's not working yet and not ready to be used, hence why it's a draft.

**Comment by parthv21** [comment]
I see. Do you get the same errors? I did not checkout your PR.

**Comment by lmarceau** [comment]
It's better to leave this one off until https://github.com/mozilla-mobile/firefox-ios/issues/14320 is resolved
