### ISSUE TITLE
Don't Allow Paste Infinite Prompt

### ISSUE THREAD

**Issue by mattlikespie** [mozilla-mobile/firefox-ios#13700]
## Steps to reproduce
Copy URL from another browser, open Firefox iOS, click Don't Allow Paste.

### Expected behavior
Don't Allow Paste (and Allow Paste) eventually stops being offered

### Actual behavior
Don't Allow Paste (and Allow Paste) are repeatedly prompted

### Device & build information
* Device : iPhone 13, iOS version 13.3.1 (20D67)
* Build version: 111.1 (29556)
* First seen version:N/A
### Notes
Attachments: 

https://user-images.githubusercontent.com/113533724/227079474-dacc4b58-2082-4508-869c-e6337d57157d.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6047)

**Comment by data-sync-user** [comment]
➤ Matt Reagan commented:

QA/testing note: the change that has been made here is to the UI itself. Rather than show the iOS permissions dialog (to allow the URL copied to the pasteboard to be read), users will now see a toast as before but the button will say Paste. Tapping it will have the same action as the ‘Go’ button previously did, however. Please LMK if any questions.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (43268) with iPhone 15 Pro (17.5.1).

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v129 (43869) with iPhone 15 Pro (17.5.1).
