### ISSUE TITLE
[Experiment] The Viewpoint survey message is not displayed on the homepage

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-mobile/firefox-ios#13818]
## Prerequisites:
- Have the Firefox Release 112.0 (29771) TestFlight build installed.
- Enroll the profile in the treatment branch of the "Viewpoint Mobile Messaging Experiment" study.
## Steps to reproduce
1. Close the Firefox app.
2. Change the system time to 24h in the future.
3. Reopen the app and observe the Homepage.
### Expected behavior
- The Viewpoint survey is displayed on the homepage.
### Actual behavior
- The "Set as Default" message is displayed instead.
### Device & build information
* Device:
  - iPhone 11 (iOS 16.2)
  - iPhone 13 mini (iOS 15.6)
* Build version: Firefox for iOS Release 112.0 (29771)
### Notes
- The message is not displayed after dismissing the "Set as Default" message and restarting the app.
- Attached a screen recording of the issue:
Attachments: 

https://user-images.githubusercontent.com/40393891/229146819-ca19b87a-f4b7-4f7e-9685-e571dfdefae9.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6108)

**Comment by dnarcese** [comment]
Thanks, we will look into it.

**Comment by adudenamedruby** [comment]
Heya, so, I just tested locally (from xcode) with the experiment triggers, and it works. The problem is the steps actually needed, given the triggers. For a fresh install, they are as follows.

1. App install & go through onboarding
2. Close the app
3. Change the time to two days in the future (or 1 day and 1 minute, I'm not sure if Nimbus considers 1 day to be 24hours or > 24 hours)
4. Open the app, and go to a site (this is the foreground action)
5. Close the app.
6. Change the time to THE FUTURE!
7. Open the app - the way the trigger is written, it won't open this first time.
8. Close the app.
9. Open the app - the surface should show at this time.

Here's the configuration for the message that I used:
<img width="874" alt="Screenshot 2023-03-31 at 12 13 19 PM" src="https://user-images.githubusercontent.com/11182210/229174859-d8b8e2f3-dc69-4527-82db-ec82ee820da5.png">

Here's the video of the process:
https://user-images.githubusercontent.com/11182210/229175136-e786b82e-c5f4-45af-901c-71aaf6bf21ea.MP4

It seems like the fix is the timing of the foregrounding.

**Comment by dnarcese** [comment]
We have fixed this issue and updated  the experiment.

**Comment by Softvision-PatriciuPop** [comment]
Hi @dnarcese @adudenamedruby 

I've retested the issue with the steps mentioned above and the surface is not displayed using the latest Release 112.0 (29885), latest Beta 112.0 and latest Beta 112.1 TestFlight builds. I've attached a screen recording following the same steps.

https://user-images.githubusercontent.com/40393891/229540583-79c8276d-1801-483f-9f93-42a136d3132e.mp4

However, it seems that the surface is triggered using the original steps from the issue on the latest Beta 9000 (29872) and I've added a recording.

https://user-images.githubusercontent.com/40393891/229540640-8a05e9b1-e355-466b-abfc-89ab7518490f.mp4

Given this there seems to be a difference between the way the code handles the surface on release vs dev builds. Could you please have another look at this?

**Comment by adudenamedruby** [comment]
> Given this there seems to be a difference between the way the code handles the surface on release vs dev builds.

This should **absolutely not** be the case.

I don't understand what's happening here. :/

Taking a closer look.

**Comment by adudenamedruby** [comment]
I HAVE FOUND THE ISSUE! This should be fixed in 112.29913 when its out. :D

I'm a dang genius!

**Comment by Softvision-PatriciuPop** [comment]
I've verified that this issue is no longer reproducible, the survey is correctly displayed after 24h. Tested using Firefox Release Version 112.0 (29913), iPhone 11 (iOS 16.2). Marking this as resolved.
