### ISSUE TITLE
Tab loss after iPhone powered down

### ISSUE THREAD

**Issue by lougeniaC64** [mozilla-mobile/firefox-ios#13844]
## Logs
Will add logs shortly

## Steps to reproduce
1. Device shuts down
2. Device is charged
3. Device is turned back on
4. Firefox iOS is opened

### Expected behavior
- All tabs are restored
- Tab syncing functions as normal

### Actual behavior
- All tabs are gone
- Device's tabs are removed from sync

### Device & build information
* Device: iPhone 7
* Build version: Firefox 11.1 (29556) 

### Notes
I'm submitting this report for David Durst as he's out on PTO.

Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6121)

**Comment by ddurst** [comment]
To clarify on the STR: I shut the phone down because the battery was at 10% and in low power mode. I was subsequently unable to turn it back on until I recharged it for a few minutes.

I have not been able to find anything indicating a crash registered by iOS, so advice welcome if there are useful logs to add to this ticket.

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

For QA the nimbus feature “tab-storage-refactor-feature” needs to be enabled to verify the fix for this.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, Orla Mitchellis this something I can enroll in the Settings (secret settings) or do we need to set up something in order to test it? In that case, we must have to contact the QA Nimbus team. 

I checked the Experiments section but there is no tab-storage-refactor-feature.

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

Andrei Bodea I think I need to add the feature flag to experimenter. I’m going to figure out how to do that today and I will get back to you.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, Orla Mitchellany chance to help with this one? 👀

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

Andrei Bodea There is a bug with experimenter at the moment so I created a special build with the flag enabled. It’s the build listed in this ticket https://mozilla-hub.atlassian.net/browse/FXIOS-6395 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6395|smart-link )

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (#31207 ( https://app.bitrise.io/build/cf2ac836-6ec7-4315-bcfb-1a736b43dc23 )) with iPhone 13 Pro (15.7.1).
