### ISSUE TITLE
Homepage settings state doesn't get updated and remains `Firefox Home`

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#14157]
## Steps to reproduce
* Open Firefox -> Settings -> Home Page -> Last Tab
* Go back to Settings page

### Expected behavior
* The Homepage settings description should state correct state `Last Tab or Homepage` 

### Actual behavior
* The Homepage settings description will stay `Firefox Home`

### Device & build information
* Device: iPhone 14 pro or any other iOS device
* Build version: v112.2 (30158)
* First seen version: ? 
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/8919439/234701068-75d7e475-a7fb-4f19-8664-77a426104f23.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6291)

**Comment by esraaeiid** [comment]
Hi @nbhasin2 

I believe the inconvenience comes from the fact that there are two different selections—one for the home page and the other for the opening screen—and it updates on the home page rather than the opening screen when I choose a custom URL. 

https://user-images.githubusercontent.com/38051115/234911217-cdf2ed49-3f01-46cf-9029-ff4cbf14ae65.MP4

**Comment by dnarcese** [comment]
This is confusing because there are multiple selections within that menu. It is pulling the selection from 'Current Homepage' not 'Opening Screen'. Looking for UX help on what we should display.
