### ISSUE TITLE
[Intermittent] Quick View Widget redirects to Home Screen for a few seconds, before loading the selected web page

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#14530]
## Steps to reproduce
1. Add Quick View (medium) on the Home Screen Widgets
1. Make sure you already have a few web pages loaded 
1. From the widget choose a web page 

### Expected behavior
The webpage opens 

### Actual behavior
Home Screen is loaded for a few seconds, before loading the selected web page

### Device & build information
* Device: iPhone 14 Plus (16.0.3) 
* Build version: 114 (31138) 
* First seen version: ? 
### Notes

1. Issue reproduces when Night mode is Off, also
1. Issue doesn't reproduce when trying to access a webpage from an external app, having the FF browser set as default

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/b87c4d3d-c91e-49b1-9d25-6fd605261fbc

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6460)

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

In testing so far what I’ve observed is that you can sometimes see the homepage briefly before the URL (linked to by the widget) is opened (which is also what the reporter’s video appears to show), but I’m not 100% clear on if this is actually a defect. I would expect the app UI (in this case the home screen) to be visible briefly as we handle the incoming deeplink before it’s opened. 

Andrei Bodea (cc Orla Mitchell) Can you possibly provide some further clarification on this (or LMK if I may be misunderstanding the ticket). At least at an initial glance I’m not sure that hooking the related code up to the Event Queue will have an impact on the Actual vs. Expected behavior listed

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Thank you, Matthew Reagancan you also please set the fix version for this issue?

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

Andrei Bodea I was hoping to get some add’tl clarification on this ticket before closing so I’m not sure what the fix version will be yet but will update asap.

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

Moving to QA for now, as I’m not fully clear on what actions are required; offhand I don’t believe the event queue would impact the Actual vs Expected behavior noted in the ticket, and I’m not certain whether that is a defect. If anyone can provide some additional information as to what changes are needed here please LMK. Thank you

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v123 (37946), with iPhone 15 (17.0).
