### ISSUE TITLE
Handle showClearRecentHistory from library coordinator

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#14786]
showClearRecentHistory is shown from history panel VC, let’s show it from coordinator instead

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6610)

**Comment by FilippoZazzeroni** [comment]
Solving PR #15863

**Comment by lmarceau** [comment]
One thing left related to clear recent history:

There's a keyboard shortcut called `openClearHistoryPanelKeyCommand` that checks if the `libraryViewController` exists on BVC. Since with coordinator we are moving the ownership of `libraryViewController` to the `LibraryCoordinator`, we should adjust this `openClearHistoryPanelKeyCommand` function to use the coordinator (with the flag). We can still use the notification center if it's convenient to open the clear recent history view

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, it can be tested that the Command+shift+backspace (or delete) keyboard shortcut opens the clear recent history menu.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (34498) with iPad Air (15.7).

Cmd+shift+delete redirected me to the clear recent history menu.
