### ISSUE TITLE
Line break in label "Lesezeichen"

### ISSUE THREAD

**Issue by franztv82** [mozilla-mobile/firefox-ios#15121]
## Steps to reproduce
1. Open for example https://de.m.wikipedia.org/wiki/Wikipedia:Hauptseite
1. ![image](https://github.com/mozilla-mobile/firefox-ios/assets/93776391/7d70c1d2-7b26-49e0-a127-d16880ba4c07)

### Expected behavior
1. Open for example https://www.jw.org/de/
1. ![image](https://github.com/mozilla-mobile/firefox-ios/assets/93776391/6a77d7c0-8d89-4784-ad50-69d15585fbdd)

### Actual behavior
See "Steps to reproduce"

### Device & build information
* Device: iphone SE 2020, iOS 16.5
* Build version: Firefox 114.3 (31916)
* First seen version: I've seen  it some versions before but thought the line break was "normal" in german translation. I didn't realize that it depends on the visited website.
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6787)

**Comment by ryoooooory** [comment]
From what I can see, the reason is that the width constraint of the AutoLayout of the displayed component (TableView of the PhotonActionSheet) is fixed. So, it seems that changing the width would eliminate the line breaks in German, but it may be Mozira's design policy, and in some countries the "bookmark" (=Lesezeichen) may be very long, so the line breaks may not be avoidable. thanks
