### ISSUE TITLE
The thumbnails of the opened tabs are not leaded correctly for a specific scenario  

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#15166]
## Steps to reproduce

1. Have multiple tabs opened 
2. Force close the FF app
3. Open the FF app trough widgets or 3d touch Menu 
4. Open the tab tray and check the thumbnails 

### Expected behavior
The thumbnails of the open tabs are correctly loaded 

### Actual behavior
The thumbnails are not loaded 

### Device & build information
* Device: 14+ (16.0.3) 
* Build version: v115 (32059) 
* First seen version: ? 
### Notes

- Issue reproduces for both cases when Coordinator is On and when coordinator is OFF
- Issue doesn't reproduce if user opens the app by tapping the FF icon 
- Issue doesn't reproduce if the application was previously in background not force closed  

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/57a3ad08-5025-4b5c-959e-b778161c26be

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6814)

**Comment by lmarceau** [comment]
I think this potentially relates to the tab refactor. When I turn the feature flag OFF I can't reproduce this issue anymore.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated this issue using FF v115 (23333) and iPhone 14+ (16.0.3). 

Most of the thumbnails are no correctly loaded so I will mark this issue as QA verified. 

Another issue with lower severity was logged because not all thumbnails are loaded correctly (Some thumbnails of the opened tabs are not leaded correctly for a specific scenario · Issue #15240 · mozilla-mobile/firefox-ios (github.com) ( https://github.com/mozilla-mobile/firefox-ios/issues/15240 )) .
