### ISSUE TITLE
Product detail pages should not be reader mode eligible if the shopping icon from Fakespot is visible

### ISSUE THREAD

**Issue by Verdi** [mozilla-mobile/firefox-ios#15223]
IF a website has Fakespot functionality, we should no be showing reader mode.

### Expected behavior
Reader mode should not be offered as an option if shopping icon is visible.

### Actual behavior
Reader mode is offered as an option.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6832)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Since this will be an issue for fakespot integration, we can fix it at that point by ‘preferring’ the shopping icon over reader mode. Then they will never show at the same time.

**Comment by Verdi** [comment]
I guess that's one way of fixing it but it's still terrible on target.com for example.

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Michael Verdi Can you post a video of what you mean by “We don't try to enable reader mode on these types of pages on desktop or Android.” I’m confused because I just went on Firefox and I went to your example, target.com ( http://target.com ), and reader mode is there? I even went back from the product page to a previous page and it was still there.

!Screen Recording 2023-07-26 at 10.06.53 AM.mov|width=2882,height=2094!

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Michael Verdi nvm. I found out why it’s not working on target from a slack thread.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, Roux BuciuDaniela Arcese as we cannot really check fakespot yet, I think this ticket fix version should be changed, Fakespot is planned to be tested later when the implementation is done, but for now nothing in v118. Can you help me and set other fix version for future releases? I’m not really sure if v120 or v121 as a lot of things change to Fakespot.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (34959) with iPhone 13 Pro (15.7.1).
