### ISSUE TITLE
Small space between URL bar and status bar overlay

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#15567]
!Screenshot 2023-07-13 at 1.03.10 PM.png|width=457,height=223!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXIOS-7013)

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

Dynamic island is causing this issue

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

I don’t think that’s necessary

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For 116 is ok thought? Daniela Arcese

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

yes

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA it can be tested that both with iPhone 14 Pro, and on any other device than that one the use case where:

  * Coordinators are enabled
  * Wallpaper is set
  * URL bar is at the bottom
  * We’re on the homepage

There’s no UI issue

**Comment by Jogge** [comment]
I think this issue is related to my issue.

When I have the address bar in the bottom, I cannot view the top of many websites. Here’s an example:

![IMG_9157](https://github.com/mozilla-mobile/firefox-ios/assets/15981279/cb2fd150-7a70-463b-a4fb-c078182ebd67)

If I drag/scroll, I am able to see the top:

![IMG_9158](https://github.com/mozilla-mobile/firefox-ios/assets/15981279/49a167a1-458f-4d69-ae54-652ffcb4b5a8)

But I cannot click any links or logins buttons. It’s very frustrating.

I have temporary fixed this by placing the address bar in the top. I also experience the same issue as describe in here.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using v116 (32745) and iPhone 6s (15.7), iPhone 14+ (16.0.3) and iPad 3rd Gen (16.3.1)

Catalin Suciu please validate this issue using iPhone 14 Pro before closing it

**Comment by Jogge** [comment]
@lmarceau In production build from App Store. Yes, you are right, it's the same issue as #15116. Sadly yesterdays release 115.1 (32781) did not fix it.

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

I cannot reproduce these issues using the latest v9000 build running on an iPhone 14 Pro.
