### ISSUE TITLE
cc autofill not working on nintendo website

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/firefox-ios#15619]
## Steps to reproduce
Pre-condition - have a credit card saved in firefox

1. Go to nintendo account page and log in to account: https://accounts.nintendo.com/login?post_login_redirect_uri=https%3A%2F%2Faccounts.nintendo.com%2F
2. Go into Setting -> Shop menu to find credit card spot
3. Change or update a credit card

https://ec.paymentweb.nintendo.com/v2/transactions/CZ230717161146616296/methods?checkout_id=a7345d25e72a4edc9bdc320b1adf2d7d&lang=en_US

### Actual behavior
There is not button to autofill the saved credit card number. 
![IMG_5389FCD9DC8E-1](https://github.com/mozilla-mobile/firefox-ios/assets/287322/a4842f00-a39e-43d0-824c-68b160ea0752)

### Device & build information
* Device: ? 
* Build version: ? 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7029)

**Comment by danielnguyen-mozilla** [comment]
Given that this is potentially a Site/Web Compatibility issue (whereby adjustments and enhancements to the Fathom model responsible for Credit Card field detection are required due to differing implementations of sites), here is the relevant Bugzilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1843897

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed with v9000 (33574), iPhone SE (16.4).
