### ISSUE TITLE
Orientation API bug with OrientationLockUtility

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#15687]
In console

```
[Orientation] BUG IN CLIENT OF UIKIT: Setting UIDevice.orientation is not supported. Please use UIWindowScene.requestGeometryUpdate(_:)
```

`OrientationLockUtility` is using a private API. Either we solve this by using [`override var supportedInterfaceOrientations: UIInterfaceOrientationMask`](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621435-supportedinterfaceorientations) or by asking [`UIWindowScene.requestGeometryUpdate(_:)`](https://developer.apple.com/documentation/uikit/uiwindowscene/3975944-requestgeometryupdate).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7057)

**Comment by nwaliaez** [comment]
Is it ok to lock it to portrait orientation ?
`    struct OrientationLockUtility {
        static func lockOrientation(_ orientation: UIInterfaceOrientationMask) {
            if let delegate = UIApplication.shared.delegate as? AppDelegate {
                delegate.orientationLock = orientation
            }
        }

        static func lockOrientation(_ orientation: UIInterfaceOrientationMask,
                                    andRotateTo rotateOrientation: UIInterfaceOrientation) {
           
            self.supportedInterfaceOrientations
            UIDevice.current.setValue(rotateOrientation.rawValue, forKey: "orientation")
        }
        
        override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
            return .portrait
        }

    }
`

**Comment by lmarceau** [comment]
So from what I understand, in some places in the app by design it was wanted to lock the orientation to portrait yes. This task is that we do this by avoid using the `UIDevice.current.setValue(rotateOrientation.rawValue, forKey: "orientation")` which isn't a public API.

If I remember well, the proper API to lock orientation can only work on a fullscreen page (so we can't lock orientation for a modally presented view for example). So the first step of this task would be to enable this new method of locking orientation for the SurveySurface (which currently uses the faulty `OrientationLockUtility`). One thing to note is that our IntroViewController and the UpdateViewController use proper APIs to lock the screen orientation. So SurveySurface could have the same and that would be a good start.

**Comment by imsanchit** [comment]
@lmarceau can this issue be picked to work on?

**Comment by lmarceau** [comment]
@imsanchit yes 👍 It's marked as contributor OK, so if there's no open PR for it then it's safe to be worked on!

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA, it can be tested the Survey (shown at launch of the app when there’s a survey experiment going on) is not rotating on iPhone

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Test case created for this ticket. 

To be tested once we have a survey experiment enabled.
