### ISSUE TITLE
App has crashed when trying to load up a tab

### ISSUE THREAD

**Issue by fierytortilla** [mozilla-mobile/firefox-ios#15922]
## Steps to reproduce
As described in this post (https://support.mozilla.org/bm/questions/1419978) I had a number of tabs open on my Firefox iOS app, and some of them did not work. Not only would they not open, the URL bar wouldn't even open, so I could not reload the page. When I tried to click on the page longer in the tab view, the whole app would crash. I eventually tried to unload the app from my phone, and this also did not work. It seems I have now lost all my tabs after trying to get them all back after numerous crashes.  Attached to this post are the logs of the app as well as the crash logs (note: the Firefox.log file was split up into four files: xaa, xab, xac, and xad. Otherwise, the crash log is Client-2023-08-01-123132.log).

## Logs
[xaa.log](https://github.com/mozilla-mobile/firefox-ios/files/12268193/xaa.log)
[xab.log](https://github.com/mozilla-mobile/firefox-ios/files/12268212/xab.log)
[xac.log](https://github.com/mozilla-mobile/firefox-ios/files/12268197/xac.log)
[xad.log](https://github.com/mozilla-mobile/firefox-ios/files/12268198/xad.log)
[Client-2023-08-01-123132.log](https://github.com/mozilla-mobile/firefox-ios/files/12268199/Client-2023-08-01-123132.log)

### Device & build information
* Device: iphone 11 Pro
* Build version: iOS Version 16.5.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7164)

**Comment by lmarceau** [comment]
Hello! Thank you for opening this issue and describing it. Some part of this problem seems to relate to https://github.com/mozilla-mobile/firefox-ios/issues/15989, although you experienced beforehand your tabs partly working (not loading) which is a different problem. We are working on investigating this problem and will keep you posted when we know more, thank you!

**Comment by jpufferfish** [comment]
> If you could potentially tell us on which version of the application you were when this happened it would be helpful as well. Thanks!

I just experienced the same issue today wth ios ver. 116.1. Unable to recover the tabs via synced-tabs.db on my macbook, probably because it had been a few-several hours by the time of bug discovery. Lost at least 50 tabs, maybe 80. Didn't have any private tabs. I'll soon try finding an older .db file via time machine backup, but it wasn't that recent. Other users may have had it worse, and some might not even have mac or time machine methods. 

History->recently closed tabs is greyed out. Relevant settings include: "set to open with home page", and inactive tabs toggled off.
