### ISSUE TITLE
Firefox app crashing on iphone since latest update

### ISSUE THREAD

**Issue by Brianable** [mozilla-mobile/firefox-ios#16143]
## Logs
You can help us by sending us either your crash logs or Firefox logs. Instructions on how to do this [here](https://github.com/mozilla-mobile/firefox-ios/wiki/How-to-get-your-device-logs).

## Steps to reproduce
[Firefox.log](https://github.com/mozilla-mobile/firefox-ios/files/12387763/Firefox.log)

### Expected behavior
Normal

### Actual behavior
Since a few weeks (since the app update) 
[Firefox.log](https://github.com/mozilla-mobile/firefox-ios/files/12387771/Firefox.log)
Firefox keeps crashing. I have removed the app a couple of times - but problem persists. 

### Device & build information
* Device: iPhone 11
* Build version: iOS 16.6

### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7272)

**Comment by Brianable** [comment]
Hi, Sorry for the delay. There was no 'client' log made before the 23rd. If the log has another name (such as 'analytics') I could look for that. Anyway - here is the only 'client' log that was made. Hope it helps. PS: the ips file would not load so I changed it to a text file. 
[Client-2023-08-23-215546.txt](https://github.com/mozilla-mobile/firefox-ios/files/12429021/Client-2023-08-23-215546.txt)

**Comment by Brianable** [comment]
I would if I hd more specifics on the 'name' of the crash log! In the online example it's given as 'client' - this I have sent, and it was the only 'client' file that was there. Do you mean the 'analytics.ips' file?

**Comment by lmarceau** [comment]
@Brianable Thank you for the crash log! I just asked some questions to my colleagues on the content of the log you said 🙏

**Comment by tarikeshaq** [comment]
@lmarceau from the crash logs looks like the crash is a `SIGKILL` because of a deadlock, although, iOS's definition of a deadlock sigkill is that [the operating system killed the process because the process was holding on to a file lock while the app was backgrounded/closed](https://developer.apple.com/documentation/xcode/understanding-the-exception-types-in-a-crash-report#EXCCRASH-SIGKILL)

From the logs this is happening during an `fsync` in sqlite, implying that the app was writing to disc when the operating system killed it.

This is a little tricky to track down but one thing that did change recently that could be the culprit is in 116, when introducing the sync manager. Before, a [history/bookmarks/logins sync operation would occur in the same dispatch queue regular writes occur](https://github.com/mozilla-mobile/firefox-ios/blob/0c9cc303e0011f11477a9c272251491f784e9646/Storage/Rust/RustPlaces.swift#L23-L24). But with 116, the sync operation would run in [the global default dispatch queue](https://github.com/mozilla-mobile/firefox-ios/blob/0c9cc303e0011f11477a9c272251491f784e9646/Sync/RustSyncManagerAPI.swift#L37).

Before 116, when the app is background, [we blocked the main thread waiting for ongoing operations to conclude](https://github.com/mozilla-mobile/firefox-ios/blob/0c9cc303e0011f11477a9c272251491f784e9646/Providers/Profile.swift#L361-L370) And since sync operations ran with regular operations, we wouldn't terminate the app until the sync operations are done. But now, it's quite possible a sync operation in the global default queue is still running, holding on the sqlite file lock.

I'm looking into how we can make the sync operations closable in a reasonable way but wanted to braindump where I'm at. We might also be able to use [`beginBackgroundTask`](https://developer.apple.com/documentation/uikit/uiapplication/1623051-beginbackgroundtask) like the docs suggest too.
