### ISSUE TITLE
Many bugs and malfunctions lately, what's going on?

### ISSUE THREAD

**Issue by not-available-username** [mozilla-mobile/firefox-ios#16152]
I've noticed that in the last months there is always a new bug, glitch or site that doesn't work properly and is difficult to track them all, what is going on with the development of the iOS app?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7276)

**Comment by servusdei2018** [comment]
@not-available-username please avoid creating an issue to discuss something. [Discussions](https://github.com/mozilla-mobile/firefox-ios/discussions) exists separately for that purpose.

**Comment by LeoniePhiline** [comment]
+1 
I experience the same and believe that this should not be a discussion, but a meta bug. 

Firefox iOS has gotten considerably worse in the last few months.

**Comment by lmarceau** [comment]
There's no good answer to this apart from "we're working to fix the different issues that are raised to us - we're aware of the problems". If you want to have broader discussion/ask questions about the different development project currently ongoing, feel free to drop in [Element chat](https://chat.mozilla.org/#/room/#fx-ios:mozilla.org) or open a [discussion](https://github.com/mozilla-mobile/firefox-ios/discussions) as it was stated (for some reason discussion are rarely opened - but can assure that we'll see if one is opened). We keep GitHub issues for specific problems rather than general conversations about the direction of the app. So for now I'll close this one, thanks!
