### ISSUE TITLE
Replace RoundedButton in HomepageMessageCardCell

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#16395]
Replace ctaButton in HomepageMessageCardCell with primary button from the component library

PR will be similar to [https://github.com/mozilla-mobile/firefox-ios/pull/16417](https://github.com/mozilla-mobile/firefox-ios/pull/16417|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7398)

**Comment by JOELPOG** [comment]
do i keep the name of the button as ctabutton (which used Primary rounded button instead of the action button) or change the name of the ctabutton to primaryRoundedButton or something...

As for the accessibility argument of the model should i set the a11yIdentifier the same as mentioned in the ctabutton code (its assigned as a11y.ctaButton)

**Comment by lmarceau** [comment]
@JOELPOG The name of the button can stay the same, that's fine to me. And yes a11y identifier should stay the same.

**Comment by data-sync-user** [comment]
➤ Laurie Marceau commented:

For QA it can be tested that the button in the Homepage default browser card (that appears when we have a fresh install of the app) works as expected

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (35049), with iPhone SE (16.6.1).

To be rechecked once the v120 build is officially released.
