### ISSUE TITLE
address bar bottom in landscape view makes the top area of the screen not clickable iOS

### ISSUE THREAD

**Issue by EvanetaI** [mozilla-mobile/firefox-ios#16611]
## Steps to reproduce
Open web page with buttons as close as possible to the top end of the screen. Try to tap it. 

### Expected behavior 
The top area should be clickable. 

### Actual behavior
The top area is not clickable.

* Device:  iOS 15.X / 16.X devices. Probably will happen on others too.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXIOS-7481)

**Comment by cpeterso** [comment]
### Steps to reproduce:

1. Set Firefox Settings > Toolbar to "Bottom".
2. Load https://news.ycombinator.com/
3. Rotate your device to landscape orientation.
4. Try to tap the "new" link at the top of the page.

### Expected behavior

Tapping "new" should to the "new" page like it does in:

* Firefox with toolbar at bottom when in landscape orientation
* Firefox with toolbar at top or bottom when in portrait orientation
* Safari and Chrome when in either landscape or portrait orientation. AFAICT you can't move Safari's or Chrome's toolbar to the bottom in landscape orientation, but that shouldn't be a factor for tapping the link.

### Actual behavior

Nothing happens in Firefox.
7. Rotate your device to portrait orientation.
8. Tap the "new" link at the top of the page. Firefox navigates to the "new" page, as expected.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using v9000 (39649) using iPhone 15+ (17.4).

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v125 (39935), with iPhone 15 (17.0)

**Comment by cpeterso** [comment]
It works! This fix makes me so happy! 🤩
