### ISSUE TITLE
Fakespot - Retry Shopping API after 500 errors doesn't work 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#16883]
## Steps to reproduce
1. Setup Fiddler (or other proxy that allows you to change the response status code before the response hits the app client)
2. Simulate a 500 response status for all requests to https://mozilla-ohttp-fakespot 
3. From the app client open the drawer for a product 
4. Check the number of the requests the client sends when 500 status code is received 

### Expected behavior
The client app retries the call 3 times 

### Actual behavior
The client app doesn't retry 

### Device & build information
* Device: iOS simulator, iPhone 14+ 
* Build version: V9000 (35002) 
* First seen version: V9000 (35002)  
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/1bba9622-7c20-47c2-9d79-7293f5a07b98

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7584)

**Comment by data-sync-user** [comment]
➤ Razvan Litianu commented:

Upon investigation OHTTPManager from Mozilla Rust Components never forwards the 500 error, instead we get RelayFailed custom error. 
After discussing with Ted Campbell, we agreed we’re going to retry if we get RelayFailed.

Notice we will retry on possible other errors including 500 because on the client side there’s no way to filter by error code.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Verified as fixed using V9000 (35575) and iPhone 14+ (16.0.3)

!f145acfd-8c9d-4ce5-8d95-3ecdd525b035.jpg|width=1600,height=864!
