### ISSUE TITLE
Resolve all warnings of Xcode 15 to pass Bitrise Pipeline

### ISSUE THREAD

**Issue by AakifNadeem** [mozilla-mobile/firefox-ios#16942]
### Expected behavior
Should not have warnings above the threshold limit

### Actual behavior
Warnings are more than threshold limits.

### Device & build information
Xcode 15

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7613)

**Comment by lmarceau** [comment]
Hello @AakifNadeem, we normally have specific tasks to track the warnings like https://github.com/mozilla-mobile/firefox-ios/issues/11378 rather than one task to track them all. This makes it easier to know what was done and what's left. I'll close this task here for now as it's too generic. Thanks!
