### ISSUE TITLE
No CFR for "Jump back in" section displayed on Home screen

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#16985]
**Steps to reproduce**

1. Clean install FF, sign in and sync with an existing FxA account
2. Visit a webpage
3. Open a new tab and observe the "Jump back in" section

**Expected behavior**
The CFR for "Jump back in" section is displayed on Home screen.

**Actual behavior**
No CFR for "Jump back in" section is displayed on Home screen.

**Device & build information**

* Device: iPhone SE (16.6.1)
* Build version: v120(35427)
* First seen version: v120(35427)

**Notes**
**Attachments:** 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/03f04c20-9655-4379-9bf8-0301865b30a1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7622)

**Comment by data-sync-user** [comment]
➤ Yoana Rios Diaz commented:

This bug is related to https://mozilla-hub.atlassian.net/browse/FXIOS-7621 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7621|smart-link ) 

The logic to show JumpBack CFR is to show after the Toolbar CFR is shown so the fact that the Toolbar is not showing is blocking JumpBackIn CFR.
