### ISSUE TITLE
Fakespot - Incorrect card is displayed in case the 'Check review Quality' is in progress but it was started from a different device

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#16988]
## Steps to reproduce

1. Check for a product having 'No info about these reviews yet' card displayed in review drawer  
2. Start analyze from desktop 
3. Check the product on desktop -> analyzing card is displayed 
4. Check the product on iOS -> analyzing card is displayed 
5. Wait for analyze to be finished on desktop
6. Check the desktop -> No enough reviews card is displayed 
7. Wait for analyze to be finished on iOS
8. Check the iOS 

### Expected behavior
No enough reviews card must be displayed  

### Actual behavior
'No info about these reviews yet' is displayed 

### Device & build information
* Device: iPhone (16.0.3) 
* First seen version: ? 
### Notes
Attachments: 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7624)

**Comment by razvanlitianu** [comment]
In my opinion this is expected behaviour. We have a rule first show 'No info about these reviews yet' card, if the user taps the button to check for reviews we now register that this action was done, and if the state comes back the same, we then show the not enough reviews card.

The problem in this case is that the user never tapped on the check for review button on iOS since the call is made for desktop, the state comes back the same and because we have no registered action we show the 'No info about these reviews yet' card. If you at this point you tap the button on iOS, you will most likely see the not enough reviews card.

cc: @thatswinnie

**Comment by data-sync-user** [comment]
➤ Winnie Teichmann commented:

I agree with Razvan Litianu: it behaves as expected - so this is not a bug.
