### ISSUE TITLE
No "Toolbar settings" CFR displayed on Home screen

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#16982]
**Steps to reproduce**
1. Clean install Firefox iOS
2. Launch Firefox iOS and navigate to the Home screen

**Expected behavior**
"Toolbar settings" CFR is correctly displayed on Home screen.

**Actual behavior**
No "Toolbar settings" CFR is displayed on Home screen.

**Device & build information**

* Device: iPhone SE (16.6.1)
* Build version: v120(35427)
* First seen version: v120(35427)

**Notes**
This issue occurs after fresh install.

**Attachments:**

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/91a798c3-6126-42a7-8483-45910cb95a91

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7621)

**Comment by yoanarios** [comment]
This bug is related to the work done in this [PR](https://github.com/mozilla-mobile/firefox-ios/pull/16738/files) for issue #16102. In this PR we updated the flag that controls if we show or not the CFR the default values for the new flag are set to false in the beta channel but I don't have a good context for this ticket so tagging @nbhasin2 and @jnrahme to check if this is a new intended behaviour or we just should enable by default this flag on Beta

**Comment by yoanarios** [comment]
Setting the flag to true by default shows the CFR correctly so we need confirmation if this is new intended behaviour or if we should change the default value for develop and beta channels

![Simulator Screenshot - iPhone 15 - 2023-10-26 at 16 12 37](https://github.com/mozilla-mobile/firefox-ios/assets/18538058/9cda87f9-4078-4e66-b50f-89dbd4974715)
![Screenshot 2023-10-26 at 4 12 34 PM](https://github.com/mozilla-mobile/firefox-ios/assets/18538058/1fac516d-b71c-4c7f-a48d-04321af69196)

**Comment by nbhasin2** [comment]
According to the discussion, toolbar CFR shouldn't show as that's what the discussion around this was.

Wouldn't consider this as a bug unless we want to start showing CFR around it
