### ISSUE TITLE
Incorrect behavior of "Learn how" button on Home screen banner

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#17009]
**Steps to reproduce**
1. Clean install FF app
2. Complete the on boarding card flow without setting Firefox as your default browser
3. Relaunch FF 4 times until the homepage banner "Switch your default browser" is displayed
4. Tap on "Learn how"

**Expected behavior**
"Switch Your Default Browser" pop-up is displayed.
The user can either proceed to iOS settings in order to set FF as default browser or close the pop-up.

**Actual behavior**
"Switch Your Default Browser" pop up is displayed for only a couple of seconds and then it disappears.

**Device & build information**
* Device: iPhone SE (16.6.1)
* Build version: v120 (35504)
* First seen version: v120 (35504)

Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/133357955/7e572f3a-5b16-4ad8-acdb-f97040a93292

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7631)

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

Quick update: the tutorial getting dismissed is happening as a result of the changes from https://mozilla-hub.atlassian.net/browse/FXIOS-7537 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7537|smart-link ) so we’ll need to be careful about addressing this to be sure it doesn’t regress the fix for FXIOS-7537.

I have two potential fixes we can use to address this, though if time permits it sounds like the team wants to discuss the architecture around the coordinator/dismissal code in more depth.

Moving this back to Open in the meantime until we have a chance to sync up about the best path forward.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v120 (35673) with iPhone 13 Pro (15.7.1).
Note that I’ve tried 5 times and had no issues after pressing on Learn how.
