### ISSUE TITLE
[regression] FxA send tab error when trying to send substack.com link to Firefox iOS

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#17313]
## Steps to reproduce

1. In Firefox on desktop, right-click the following Substack URL and "Send Link to Device" to an synced Firefox on iOS: https://substack.com/app-link/post?publication_id=458709&post_id=138864253&utm_source=post-email-title&utm_campaign=email-post-title&isFreemail=false&r=foie0&token=eyJ1c2VyX2lkIjoyNjMzNzgxNiwicG9zdF9pZCI6MTM4ODY0MjUzLCJpYXQiOjE2OTk5NzY2NjMsImV4cCI6MTcwMjU2ODY2MywiaXNzIjoicHViLTQ1ODcwOSIsInN1YiI6InBvc3QtcmVhY3Rpb24ifQ.lRf_afO7v7birmksnJZlW__JUF7swxmVCWJW5ieKUGM
2. Switch to Firefox on iOS and wait for the sent tab.

### Expected behavior

The blog post tab should open in Firefox on iOS.

### Actual behavior

Substack instead returns a page displaying this JSON error: `{"errors":[{"location":"query","param":"post_id","msg":"Invalid value"}]}`

This error only happens in Firefox iOS. The same substack.com URL loads correctly went send to Firefox on Windows, macOS, or Android.

### Device & build information

* Device: iPhone 15 Plus running iOS 17.1.1
* Build version: build 9000 (35991)
* First seen version: build 9000 (35105)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7760)

**Comment by cpeterso** [comment]
The JSON error:

![image](https://github.com/mozilla-mobile/firefox-ios/assets/629193/d3cf3da4-4081-4207-8574-aa5799a096f8)

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

Note: I can reproduce this using Firefox Mac 119.1 and an iOS 17 Sim running the latest dev branch.

!Screenshot 2023-11-14 at 1.35.34 PM.png|width=430,height=101!

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

Part of the problem appears to be that some of the additional params in the URL are removed; in the provided example (the substack URL), the URL which is actually opened on the device only partially matches the original full URL that was right-clicked. The device instead tries to open:
https://substack.com/app-link/post?publication_id=458709

But opening this URL shows that the substack website will instead show an error message, presumably due to missing some of the necessary params.

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

It looks like RouteBuilder.makeRoute(url:) is stripping off the parameters from the URL. The URL which is sent to the app (at least in testing so far) includes the full parameters but after processing the URL in makeRoute() most of the params are removed:

(lldb) po url
▿ fennec://open-url?url=https://substack.com/app-link/post?publication_id=458709&post_id=138864253&utm_source=post-email-title&utm_campaign=email-post-title&isFreemail=false&r=foie0&token=eyJ1c2VyX2lkIjoyNjMzNzgxNiwicG9zdF9pZCI6MTM4ODY0MjUzLCJpYXQiOjE2OTk5NzY2NjMsImV4cCI6MTcwMjU2ODY2MywiaXNzIjoicHViLTQ1ODcwOSIsInN1YiI6InBvc3QtcmVhY3Rpb24ifQ.lRf_afO7v7birmksnJZlW__JUF7swxmVCWJW5ieKUGM
  - _url : fennec://open-url?url=https://substack.com/app-link/post?publication_id=458709&post_id=138864253&utm_source=post-email-title&utm_campaign=email-post-title&isFreemail=false&r=foie0&token=eyJ1c2VyX2lkIjoyNjMzNzgxNiwicG9zdF9pZCI6MTM4ODY0MjUzLCJpYXQiOjE2OTk5NzY2NjMsImV4cCI6MTcwMjU2ODY2MywiaXNzIjoicHViLTQ1ODcwOSIsInN1YiI6InBvc3QtcmVhY3Rpb24ifQ.lRf_afO7v7birmksnJZlW__JUF7swxmVCWJW5ieKUGM
(lldb) po route 
▿ Route
  ▿ search : 3 elements
    ▿ url : Optional<URL>
      ▿ some : https://substack.com/app-link/post?publication_id=458709
        - _url : https://substack.com/app-link/post?publication_id=458709
    - isPrivate : true
    - options : nil

**Comment by cpeterso** [comment]
The messageIncomplete error is a regression in build 9000 (35974) about 4 days ago. The previous build, 9000 (35936), correctly shows a notification with the sent URL.

The JSON error bug is a regression in build 9000 (35105) about 32 days ago. The previous build, 9000 (35049), loads the blog post page correctly.

**Comment by data-sync-user** [comment]
➤ Matthew Reagan commented:

I believe there are two separate issues in this ticket, one of them looks like it should be fixed by https://mozilla-hub.atlassian.net/browse/FXIOS-7761 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7761|smart-link ) 

And the other is an issue with deeplinked URLs with multiple query items, which is tracked here: https://mozilla-hub.atlassian.net/browse/FXIOS-7766 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7766|smart-link )

**Comment by cpeterso** [comment]
This works for me with Firefox iOS build 9000 (36759).
