### ISSUE TITLE
Opening a link in external app leaves a "loading" about:blank page behind

### ISSUE THREAD

**Issue by vsanjay85** [mozilla-mobile/firefox-ios#17571]
## Steps to reproduce
1. Open a website that might potentially redirect you to a locally installed app.  An example is a deals website or a social media website that might redirect you to Youtube, Instagram, etc
1. Click on a link that would redirect you to a locally installed app, such as an Amazon or Walmart URL or any other application you currently have installed.

### Expected behavior
1. Redirect user to the external app and load the copied URL

### Actual behavior
1. Redirect user to the external app and load the copied URL
1. Firefox leaves an "about:blank" page behind that stays stuck in 'loading' state

### Device & build information
* Device: Tested on iPhone XR (IOS 16.7.1) and iPhone 15 Pro (IOS 17.x)
* Build version: 120.1 (36298)
* First seen version: Been this way for as long as I've used an iPhone, about 4-5 months now. 
### Notes
This behavior is not limited to one or two apps. This happens regardless of the app I'm redirected to, Youtube, Costco, Target, etc.

I do NOT see this in Safari. 
I DO see a similar behavior in Chrome

It appears that the browser is opening the link in a browser tab first, and then checking if a locally installed app exists. If this check could happen without opening the link in another tab, that would likely fix it. 

Attachments: 
![image](https://github.com/mozilla-mobile/firefox-ios/assets/18194044/e5ad39c7-79a6-460d-85ea-ef1df9e58a05)
![image](https://github.com/mozilla-mobile/firefox-ios/assets/18194044/b176172b-70e2-42c9-8ee3-c73dd66d8b51)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-7871)

**Comment by brendanjones** [comment]
I'm also seeing this bug.

**Comment by PraveenJP** [comment]
Me as well

**Comment by Cpt-KeksMonster** [comment]
Since the recent versions of Firefox for iPadOS many links just open to about:blank. Especially PayPal links on checkout, e.g. trying to start (to pay for) a Tidal subscription. Also "download image" at imgflip.com shows this behavior. Gotten worse the last weeks. 😢

**Comment by dicarobinho** [comment]
@lmarceau 

Investigated this issue for a while, and...

Based on the current code version, that "about:blank" page was/is intended and also someone left an important comment related to this behaviour.

"
// If the page uses `window.open()` or `[target="_blank"]`, open the page in a new tab.
// IMPORTANT!!: WebKit will perform the `URLRequest` automatically!! Attempting to do
// the request here manually leads to incorrect results!!
"

BUT

In order to open a link for example via Youtube (native app), currently Firefox open Youtube app but also a empty page (blank page). To avoid this behaviour, we can check first if the app (e.g. Youtube) is installed, using "UIApplication.shared.canOpenURL" method.

If "Yes" we can open the native app using "UIApplication.shared.open" else continue to the current implementation. (which is working fine if no native app is installed)

A short mention here: every native app (e.g. Youtube, Instagram) that we want to be covered by this approach should be added to the "LSApplicationQueriesSchemes" list. 

"LSApplicationQueriesSchemes" list already have apps like: googlegmail and whatsapp.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Alina Moldovan Andrei Bodea I changed the priority of this issue. We have a lot of reports from users about this happening more frequently on 124 than on previous versions and I want to make sure we are fixing it for the next weekly release.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hi, thank you Norberto Andres Furlan on what version is this issue fixed? I understand the Fix version: weekly release there but might be worth mentioning in a comment what version was this issue fixed first.

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

I tested on the main branch that contain this fix too.

As Alina Moldovan , I can reproduce this issue but also I removed from the code, the implementation for this ticket and the problem still be there. That means, something else, changed that behaviour and is not related to code added for this ticket.

I will get the answer as soon as possible and I will come here with an update.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Nishant Bhasin maybe the fixes we pushed on v124 also affected this behavior.

**Comment by data-sync-user** [comment]
➤ Alexandru Farcasanu commented:

Norberto Andres Furlan 

After more investigations, this behaviour is related to this ticket: https://mozilla-hub.atlassian.net/browse/FXIOS-7586 ( https://mozilla-hub.atlassian.net/browse/FXIOS-7586|smart-link ) 

Sorin Paraipan is taking a look on it.

**Comment by Cpt-KeksMonster** [comment]
For me: fixed for virtually all websites. Exception found: PayPal payment after a Steam purchase. Still opens blank tabs, 3-5 tries necessary before the PP website opens and payment can be completed.
