### ISSUE TITLE
The navigation bar has become very thick

### ISSUE THREAD

**Issue by arnavbhate** [mozilla-mobile/firefox-ios#18097]
## Steps to reproduce
Open Firefox

### Expected behavior
Normal size navigation bar

### Actual behavior
Thick navigation bar with extra spacing

### Device & build information
* Device: iPad Air (5th generation), iPadOS 17.2
* Build version: 121.2 (37524)
* First seen version: New to this version

### Notes
Reinstalled firefox from app store and issue still persists.
Attachments: 
![Screenshot](https://github.com/mozilla-mobile/firefox-ios/assets/86760472/98741cdb-90db-49f2-a047-383ba406e98f)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8131)

**Comment by afurlan-firefox** [comment]
From the screenshot, I can see the regular padding on the navigation bar. Have you noticed any change compared with previous versions? If so, can you attach the screenshots. Thanks!

**Comment by arnavbhate** [comment]
> From the screenshot, I can see the regular padding on the navigation bar. Have you noticed any change compared with previous versions? If so, can you attach the screenshots. Thanks!

I don't have any prior screen shots, but compare with the iPad screenshots on the app store. That is what it looked like.

**Comment by rajparad** [comment]
For this issue, I think it's not only in iPad. I also checked for Mobile, after comparing it App store it seems like there is more padding. I am attaching screenshots below. For the issue `LocationHeight=40` in `URLBarViewUX` in URLBarView class can be cause. I am not sure LocationHeight has been changes recently, or we use specific values for this var. After changing it to higher number it works fine, but please suggest @lmarceau 

Appstore Image:
<img width="219" alt="image" src="https://github.com/mozilla-mobile/firefox-ios/assets/59967463/b225ef3e-7abd-4f0d-970a-68d77aecadda">


Current Simulator Image:
<img width="357" alt="image" src="https://github.com/mozilla-mobile/firefox-ios/assets/59967463/211cf1ce-b894-4f5f-b42e-8b192691d54e">

**Comment by tisumi99** [comment]
Did some research and found an old PR from @adudenamedruby that had fixed this 3 years ago.  Here's the old [issue](https://github.com/mozilla-mobile/firefox-ios/issues/7956) and [PR](https://github.com/mozilla-mobile/firefox-ios/pull/8145).  The old issue also points to the URL bar being too tall (too much bottom padding).  The explanation was that the added height was needed to to accomodate the larger text sizes that a user can set in the iOS accessibility settings.  The fix was to make the URL bar height dynamic.

The odd thing is the code to make the URL bar dynamic is no longer in the code base.  When I copy the dynamic code from the old PR into my sandbox branch, it solves this issue.  So not sure why the code was removed and not sure if I should put it back in.

Couple of screenshots from my sandbox branch with the restored code.
![Screenshot 2024-05-01 at 4 05 09 PM](https://github.com/mozilla-mobile/firefox-ios/assets/98071325/a91a532a-135d-4741-b8c1-98e8e4831e23)

**Comment by adudenamedruby** [comment]
o wow, I did fix this. Go me! lol

@tisumi99 thanks for looking into this. Before fixing, would you mind looking to see what PR it was removed in, so we can try to understand why it was removed in the first place. It may have been accidental, or intentional.

**Comment by tisumi99** [comment]
@adudenamedruby
I found the [PR](https://github.com/mozilla-mobile/firefox-ios/pull/16660) and [Issue](https://github.com/mozilla-mobile/firefox-ios/issues/16340) that removed the dynamic URL bar code.  There was an issue with the on screen keyboard overlapping the bottom part of the URL bar when the bar is set at the bottom.  Removing the dynamic code fixed the overlapping issue since having a fixed taller URL bar avoided the overlap.  But now we are back at having a too tall URL bar when the bar is set at the top.  So I'll restore the dynamic code but only activate it when the URL bar is at the top.
