### ISSUE TITLE
[Experiment] - Night Mode

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#18644]
We want to run an experiment to analyze if we should decommission night mode. We need a feature flag to control night mode.

**Two branches:**

* **Control:** User has the ability to set the night mode on (Keep the option inside Menu IA)
* **Treatment A:** Night mode disabled - No option inside Menu IA

Context: As part of the Menu IA project, we need to decide whether we are keeping night mode.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8413)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

This experiment will go on 123.1

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Testable on 900 and 124 (any build after Feb 22). Also available in 123, but not yet landed as it’s tagged weekly-release

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Hello, Roux Buciu Norberto Andres FurlanI’m trying to verify this one for the dot releases but I can’t find any experiment related to Night Mode I did try with 3 fresh installs and nothing, can you please check as today I need to verify this one before the sign-off. 

Also, this issue was not present in the weekly release before this draft for 123.2 was created, usually, we like to check the bugs ahead of time at least on v9000 like we discussed before but this was missing from the list 😞.

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

Andrei Bodea I don’t see an experiment created with this. Norberto Andres Furlan will have to create the experiment, I believe.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Thank you Roux Buciu I discussed with Norberto Andres Furlanand he told me we gonna verify this when the experiment will be created so for now we can let it like this. 
Andy if you can tag us when it’s ready so we can verify it, thank you!

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v124 (39709) with iPhone 15 Pro (17.3.1).

**Comment by MarkTheUnruly** [comment]
As a programmer and user, can I say what an incredibly bad idea this was.  For a lot of users (me included), this isn't a theme issue, it's an accessability issue.  I would NEVER remove an existing accessability feature without warning the users.

I am a diabetic with vision issues.  A dark background is a requirement for me to use a device without strain and most websites don't support a dark mode, (including support.mozilla.org). This will affect everyone with cataracts, photophobia and various other conditions.  Having diabetes makes you 2 to 5 times more likely to develop cataracts. It also makes you more likely to get them at a younger age.  This means that the number of people is growing along with the rise in Type 2 diabetes.

One of Firefox's missions is supposed to be to make the web more accessible to people.  I dont have night mode, so for me, Firefox for IOS is currently failing that misssion.  

Removing this feature would force me to switch browsers on my iPad, probably to Safari, which I hate, since I can use the Dark Reader add-in.  I have been using Firefox since 2004 when the committee advising the US government said IE6 was a security concern and I love the features and ease of use.

**Comment by afurlan-firefox** [comment]
Hi @MarkTheUnruly 

Thank you for taking the time to share your concerns with us. We truly understand the importance of accessibility features and your feedback is really valuable for us. We are actively reviewing the impact of these changes and exploring ways to address them effectively. We apologize for any inconvenience caused by the experiment.

In response, I have requested the termination of the experiment. The nightmode option will be reinstated soon. Please feel free to reach out to us if you have any further questions or concerns. I appreciate your continued support as a Firefox user.

Best regards,
Andy
