### ISSUE TITLE
The “Turn off Night Mode” feature does not work as expected and remains on after being changed to off and the app was relaunched

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#18950]
**[Affected versions]**:

* Firefox Release 124.0 (39313).
* Firefox Release 123.2 (39233).

**[Affected Platforms]**:

* iOS 16.4 - iPhone 12 Pro.
* iOS 17.0 – iPhone XR
* iOS 17.3 – iPhone SE

**[Steps to reproduce]**:

1. Open the Firefox app;
1. From the Hamburger menu, select the “Turn on Night Mode” option;
1. Force close the app;
1. Relaunch the app;
1. From the Hamburger menu, select the “Turn off Night Mode” option;
1. Observe the behavior.

**[Expected result]:**

* The “Night Mode” feature is correctly turned off.

**[Actual result]:**

* The browser is still displayed in Night Mode.

**[Notes]:**

* The option has no effect no matter how many times it is selected. The workaround after setting Night Mode off is to background and then foreground the app. After a force close, the issue will begin occurring again and the workaround needs to be used again each time.
* If the browser theme is set to Light manually (from Settings > Theme), after turning on the Night Mode feature then force closing the application, the theme will remain set to Dark regardless of the Night Mode feature being on or off. Due to this behavior we have noticed that the Night Mode setting is not reflected in the browser Settings > Theme section (if Night Mode is off the Light theme should be preselected, but it isn’t). The only workaround for this is for the user to go to Settings > Theme again and manually change it back to Light.
* This issue also affects the testing of [+QA-2325+](https://mozilla-hub.atlassian.net/browse/QA-2325) iOS Night Mode [+Experiment+](https://experimenter.services.mozilla.com/nimbus/ios-night-mode/summary):
  * If the user enrolls in the Control branch of the experiment (which enables the feature to continue to be displayed in the Hamburger menu), the same behavior as in this ticket will occur.
  * If the user enrolls in the Treatment A branch (which disables the feature entirely), the option is removed from the menu, but the browser will remain in Night Mode until the above mentioned workaround is used (background then foreground the app).

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXIOS-8532)

**Comment by darkCavalier11** [comment]
I want a confirmation here that the is the **Dark Theme** and **Night mode on** are same in the sense of their end results. This issue is happening cause we are using two keys one for keeping theme and other is for night mode inside `UserDefault`, and both keys are not on same page sometime, like night mode is off but theme is dark.

**Comment by adudenamedruby** [comment]
@darkCavalier11 Heya. Night Mode is problematic and we're trying to figure out what to do with it. The old implementation was working for what we used to have, but is no longer what we want. I'll confirm that, right now, when you turn turn mode on, dark theme should also be on. However, there should only be one user default (whether night mode is on or not) and the theme manager should return dark theme based on that, rather than having night mode manage themes itself.

I'm looking into this bug right now.

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v124 (39464) with iPhone 15 Pro (17.3).
