### ISSUE TITLE
[Enhanced FF suggest settings] - "Show in private session" toggle disappears after a specific scenario

### ISSUE THREAD

**Issue by DianaBarladeanu** [mozilla-mobile/firefox-ios#19002]
Prerequisites
Go to FF secret settings ---> Experiments ---> enable Enhanced Cross-Platform Suggest [iOS] experiment.

**Steps to reproduce**
1. Go to FF settings --> Search--> disable "Show suggestions from the Web" toggle.
2. Exit settings menu, return and observe.

**Expected behavior**
The search settings toggles are updated accordingly, "Show in private sessions" toggle is still visible.

**Actual behavior**
"Show in private session" toggle disappears from the menu (along with "Suggestions from sponsors" toggle).

**Device & build information**
* Device: iPhone 15 (17.0)
* Build version: v124 (39359)
* First seen version: ? 

Notes*
Please see [here](https://github.com/mozilla-mobile/firefox-ios/issues/19000) a related bug ticket.

Attachments: 

![6B52E1E1-DD23-4D77-8CE7-5B58BE6FB74C](https://github.com/mozilla-mobile/firefox-ios/assets/133357955/833f7afe-adf2-498a-a0da-34237cad86bd)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8569)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Diana Andreea Barladeanu Sorin Paraipan I am not sure if I understand the error correctly but I think this is the correct behavior. If you disable all suggestions in FX Suggest, the private suggestion option shouldn’t be available. They act as a global switch for both modes (normal and private)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Diana Andreea Barladeanu Sorin Paraipan I am not sure if I am understanding this error, because I don’t know why the Suggestions from Sponsors is disappearing:

This is the expected behavior: 

  * If the user toggles off the first three options at the same time:
    * Search Browsing History
    * Search Bookmarks
    * Search Synced Tabs

  * The private option became obsolete, so we should hide it. (Because by design, private mode only has those 3 types of suggestions, we are not displaying “Suggestions from the Web” and “Suggestions from Sponsors” in Private mode)

**Comment by DianaBarladeanu** [comment]
Hello,
I've edited the bug, I forgot to do it earlier, I apologize.
 "Show in Private Sessions" toggle  disappears after "Show suggestions from the Web" is disabled (even if the other toggles remain enabled).
