### ISSUE TITLE
The `Use saved password` button is not displayed under certain steps

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#19276]
## Steps to reproduce
1. Access https://63p8v.csb.app/ and tap on the username or password field.
1. Tap on the Use saved password.
1. Close the `Use saved password` prompt (tap on x).
1. Tap on the username or password field.
### Expected behavior
The `Use saved password` button is displayed. 
### Actual behavior
The `Use saved password` button is not displayed under certain steps.
### Device & build information

* Device: iPhone 15 Pro (17.3) 
* Build version: v124 (39709) 
* First seen version: N/A 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/42831109/5c1bf8e4-b72b-4e3a-a5be-07e92cf40526

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8690)

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Andrei Bodea can you check if this is related to this one too? https://mozilla-hub.atlassian.net/browse/FXIOS-8606 ( https://mozilla-hub.atlassian.net/browse/FXIOS-8606|smart-link ) It should follow the same logic. 

Thanks!

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

This issue still reproduces (Validated on v9000 (40044) and iPhone 14+ (16.0.3)). 

Please note that in order to reproduce this issue you have to tap the same field you used when you opened the Use saved password prompt for the first time (e.g. in Step 1 tap on Username for the Step 4 you have to user the username field again).  

Moving this issue back to “In Progress“

**Comment by data-sync-user** [comment]
➤ Dianna Smith commented:

Should this be in “todo” given that this was merged to main, 124, and 125?
