### ISSUE TITLE
[Address Autofill] - US - wish.com - autofill is not working for all fields

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#19432]
## Steps to reproduce
Make sure you are using a US VPN connection
Open wish.com and Navigate to the Address form 
Tap on any of the address's fields
Tap 'Use Saved address' 
Tap to select an address on the list 

### Expected behavior
All fields are autocompleted 

### Actual behavior
Name and Address line 1 & 2 fields are not autocompleted 

### Device & build information
* Device: iPhone 15+ (17.4) 
* Build version:  v125 (40129) 
* First seen version: ? 
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/1d80fa05-eb6c-4b54-99a1-3fcc85d3d00c

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8761)

**Comment by data-sync-user** [comment]
➤ Issam Mani commented:

This is now fixed. Rechecked and I can see the name, address and address level2 are filled.

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified on version v9000(40626) using iPhone 14 Pro Max (16.2). The State/Province field remains unfilled.

!wish.com.jpeg|width=430,height=932,alt="wish.com.jpeg"!

**Comment by data-sync-user** [comment]
➤ Issam Mani commented:

Aha sorry I should have been more specific. The PR fixed the issues for iOS. For the  state field, it’s a known issue. It’s captured here:  https://mozilla-hub.atlassian.net/browse/FXCM-445 ( https://mozilla-hub.atlassian.net/browse/FXCM-445|smart-link ). We decided to not fix this due to the nature of the bug. Norberto Andres Furlando you think we can close this as cancelled as well ?

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Closed! I linked the ticket so we can track it later if something changes on the other side. Thanks!
