### ISSUE TITLE
iPad - Tab tray in private mode shows the tab from regular mode

### ISSUE THREAD

**Issue by dragosb01** [mozilla-mobile/firefox-ios#19621]
## Steps to reproduce
1. Open a new tab in private mode and open a website
2. Go back to tab tray
### Expected behavior
Private mode should be in focus with the tab/tabs opened in private mode.
See recording
### Actual behavior
The private mode has the focus, but the tab opened in regular mode is visible
Switching back from regular to private will show eventually the right tabs
### Device & build information
* Device: iPad Air(5th generation) iOS 17.2 simulator
* Build version: 126.0
* First seen version: Yes
### Notes
Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/134391433/c7495063-4cd9-471a-b13c-e4832ccfb6f1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8893)

**Comment by mattreaganmozilla** [comment]
Thanks @AhmedFitoh for being willing to pick this up; typically external contributors are assigned tickets that have been triaged and labeled with `Contributor OK`. This ticket is probably going to be picked up by someone internally soon since it is impacting our automated tests, but please feel free to take a look at the other issues with `Contributor OK`

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000(40522), with iPad Air 3rd Gen (17.3).
