### ISSUE TITLE
testVisitTypes test is flaky

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#19659]
The test is disabled for now. This may be failing due to a real client issue.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8904)

**Comment by skhamis** [comment]
Looks like the test was failing at the line:
https://github.com/mozilla-mobile/firefox-ios/blob/22c9c1bae2a9bd1bbb2de7daf09b20cec93ba051/firefox-ios/firefox-ios-tests/Tests/ClientTests/TestHistory.swift#L217

with the cursor returning (sometimes) the visits out-of-order. This actually looks like a timestamping issue since site 2 and 3 are interchangeably being the last visit returned. Refactoring this to ensure that we can manually pass in a timestamp and/or adding some delay to ensure they are consistently in order.

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Can I close this ticket Sammy Khamis ?
