### ISSUE TITLE
Deeplinks are incorrectly opened in normal mode when the last visited tab was in private mode

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla-mobile/firefox-ios#20832]
## Steps to reproduce
1. Make sure FF is set as the default browser
1. Open a tab in Private Mode
1. While using Private Mode put the app in the background 
1. Open a webpage from an external app, using the widget (Go to the copied link) or using the context menu (open the last bookmark)

### Expected behavior
When the user opens a link from an external app, FF should open the webpage using the latest navigation mode the user used (Private/Normal navigation mode)
Step4: The link should be open in Private Mode

### Actual behavior
Step4: The link opens in Normal Mode

### Device & build information
* Device:  iPhone 14+ (16.0.3) 
* Build version: 128 (43061) 
* First seen version: ? 
### Notes
* issue reproduces for both cases when tab tray refactor is on/off 

Attachments: 

https://github.com/mozilla-mobile/firefox-ios/assets/124251579/1faf3f86-1c8e-47c2-b559-408d512ea674

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9407)

**Comment by data-sync-user** [comment]
➤ Matt Lichtenstein commented:

Tested on v127 (using steps 1-3 to reproduce)

  * Using “Open last bookmark” context menu option → New tab opens in regular browsing
  * Using the “Go to copied link” widget → New tab opens in private browsing

Norberto Andres Furlan can you confirm that the expected behavior for both scenarios is that the new tab should be opened in private browsing (or whatever browsing mode they were in before the app was backgrounded)?

**Comment by data-sync-user** [comment]
➤ Norberto Andres Furlan commented:

Yes. In both cases it should open in whatever browsing mode they were in before the app was backgrounded.

**Comment by data-sync-user** [comment]
➤ Adina Petridean commented:

Verified as fixed on v9000( 46355) with iPhone 14 Pro Max (iOS 16.2)

!private.mp4|width=886,height=1920,alt="private.mp4"!

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v133 (47434), with iPhone 15 (17.6) and iPhone 16 (18.1).
