### ISSUE TITLE
[regression] Scrolling session restored pages no longer closes the toolbar

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#21473]
## Steps to reproduce
1. Open a long web page.
1. Scroll the page. The toolbar bar should close.
1. Force-quit Firefox.
1. Reopen Firefox.
1. When the long web page is restored, scroll the page again.

### Expected behavior
The toolbar should close.

### Actual behavior
The toolbar does not close. This only happens on pages that are restored from the previous session. If you open new page in a new tab, scrolling will close the toolbar as expected.

### Device & build information
* Device: iPhone 15 Plus running iOS 17.5.1
* Build version: **This bug is a regression in TestFlight Nightly 9000 (43942).**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9781)

**Comment by data-sync-user** [comment]
➤ ih-codes commented:

For future resolution, see the [ tags in the code from https://github.com/mozilla-mobile/firefox-ios/pull/21486 ( https://github.com/mozilla-mobile/firefox-ios/pull/21486|smart-link ) .

From slack discussion ( https://mozilla.slack.com/archives/C07FK9CL2PR/p1723072073563869?thread_ts=1723069656.228459&cid=C07FK9CL2PR ) (with regards to the changes in the culprit PR https://github.com/mozilla-mobile/firefox-ios/pull/21328/files ( https://github.com/mozilla-mobile/firefox-ios/pull/21328/files|smart-link ) ):

The issue is that the tab session restore finishes and now notifies the delegates with didSelectedTabChange,  whereas before, the async Task with high priority called the selectTabWithSession first before notifying the delegates. It's not until selectTabWithSession is finished that the selected Tab’s webView is available (hence why we can't update the back button or close the toolbar).

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using Firefox iOS v129.1 (44281) and iPhone 15+ (17.5.1)
