### ISSUE TITLE
Request and display favicon.svg

### ISSUE THREAD

**Issue by jacko-png** [mozilla-mobile/firefox-ios#21536]
### User Problem
> Why should we implement this? What is the user benefit?

The web is generally transitioning to `favicon.svg`. For example, Reddit and maybe Linux Journey. Reddit's `favicon.ico` is noticeably different to their `favicon.svg`. The favicon of Linux Journey looks of less quality than on desktop, which suggests improper handling of the favicon. Also, some websites do not serve a `favicon.ico`, such as https://minecraft.wiki.

This benefits the user by ensuring compatibility with all website favicons to clearly communicate which website is open in another tab.

### Ideas for Solution
> Let us know if you have an idea on how to solve this user problem

• Integrate an SVG rendering library

• Request `favicon.svg` in the location where `favicon.ico` is requested with priority given to `favicon.svg`.

### History in FxiOS

There is a stale issue regarding favicon.svg, #11179. It had no discourse. I make this issue to see if devs are interested now.

Previously in 2022, this behaviour was labelled a bug. Today I label it a feature request, because it's not really a bug with the implementation as much as it is a missing feature.

A quick search in the source on GitHub shows that there is no mention of `favicon.svg`. This is not corroborated by #12113 which states that `favicon.svg` is requested. Despite this, no favicons are displayed from sites like https://minecraft.wiki that only have `favicon.svg` in FxiOS 129.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-9807)

**Comment by ih-codes** [comment]
Thanks for opening this ticket @jacko-png and bringing this to our attention. I've been fixing some issues with our current favicon solution, which also uncovered the fact we are not parsing SVG icons.

I am currently working on a fix for that. For example, https://news.ycombinator.com/ will now render their SVG favicon: https://news.ycombinator.com/y18.svg

I just took a look at the https://minecraft.wiki/ link you mentioned. I see they have a valid https://minecraft.wiki/favicon.ico but just get redirected to a page for https://minecraft.wiki/favicon.svg. Do you have a direct link to their SVG favicon? Thanks!

**Comment by jacko-png** [comment]
I seem to have misremembered minecraft.wiki's icon format. I don't think they actually have an svg.

When I stated that minecraft.wiki only has a favicon.svg, I was looking at the behaviour of the search engine selection bar, the suggested websites and the pins on the homepage. minecraft.wiki is missing, and Reddit has the old reddit logo. I assumed that reddit's favicon.ico must be the old logo, and that the new one that I find on desktop Firefox must be an svg. But now I don't think that's correct.

I'll attach some images of what I see

![pins](https://github.com/user-attachments/assets/25a45bdc-8393-4d2d-b557-bf2593b17e5e)
![search engine bar](https://github.com/user-attachments/assets/900ab935-7d17-4447-b8c4-9dc01b03129b)

**Comment by ih-codes** [comment]
> When I stated that minecraft.wiki only has a favicon.svg, I was looking at the behaviour of the search engine selection bar, the suggested websites and the pins on the homepage. minecraft.wiki is missing, and Reddit has the old reddit logo. I assumed that reddit's favicon.ico must be the old logo, and that the new one that I find on desktop Firefox must be an svg. But now I don't think that's correct.

Thanks for clarifying @jacko-png! Much appreciated.

I have seen this happen before, where you get a placeholder letter icon instead of the real favicon.ico. Usually it happens if a network request to download the favicon fails (bad internet connection, etc.). The letter placeholder is then cached. After the cache time expires, there (ideally) should be new attempt to fetch the real image.

**A question for you regarding Firefox for iOS**: Roughly how long have you been stuck with this "M" logo for https://minecraft.wiki/ ? More than a week? A month? Several months? Or did you only just visit the page for the first time yesterday?

Same goes with those other sites there you have a letter favicon instead of a real favicon (assuming a real one exists on the corresponding website at `/favicon.ico`.)

Your answer could potentially point to some caching issues. As for the outdated reddit favicon, we should be getting the new one in a later release. The old one was [previously bundled inside the app](https://github.com/mozilla-mobile/firefox-ios/blob/824550f82c54b2ed324544bc651d68c0e44d5112/firefox-ios/Client/Assets/TopSites/reddit-com.png).

For comparison, here is what I see on a fresh install (which has no cached images) for the minecraft wiki and reddit:

<img width="300" alt="Screenshot 2024-09-04 at 10 16 23 AM" src="https://github.com/user-attachments/assets/23729dfc-b848-481b-87d8-487bec4b2a27">
<img width="300" alt="Screenshot 2024-09-04 at 10 16 29 AM" src="https://github.com/user-attachments/assets/8f1e15f5-7d47-4bf5-a201-6c75b02ac8b0">

**Comment by jacko-png** [comment]
Wow that's interesting.

It's been this way since I started using firefox, maybe 9 months ago?

I wonder if it's an issue with the cache not being reset for websites that you use as a search engine. I'll try removing one and seeing what happens.

**Comment by jacko-png** [comment]
Another weird thing that's happend is crates.io has its favicon in the suggestion area but not the search engine ribbon.

![crates](https://github.com/user-attachments/assets/967c14fb-7588-4073-a999-1c94739d9165)


crates.io has this in their html header: <link rel="icon" href="/assets/cargo.png" type
="image/png">. I wonder if this has to do with this special case?

**Comment by jacko-png** [comment]
> Wow that's interesting.
> 
> It's been this way since I started using firefox, maybe 9 months ago?
> 
> I wonder if it's an issue with the cache not being reset for websites that you use as a search engine. I'll try removing one and seeing what happens.

This worked by the way.

![bulbapedia](https://github.com/user-attachments/assets/8d6b0eaf-16d1-4882-8e1d-386b9ea8c5ee)

**Comment by ih-codes** [comment]
Wow, this is very interesting! Thanks for the extra screenshots and information @jacko-png. I will have to look deeper into this next week.

I recently learned from a senior dev on the team that one of the involved caches never expires items unless the item is not *accessed* for the full duration of the expiry window. So in your case, you're repeatedly accessing certain favicons each time you use the app, refreshing the timer. That could be why the icons aren't getting updated like you'd expect. That's the running hypothesis but it'll need more investigation.

Next week I will make a new bug ticket since this is in fact a whole new issue separate from the initial SVG support request. I'll tag you on it when I create it!

P.S. In other news, SVG support was approved and merged in today, and it is slated to appear in the v131 release pending QA approval.

**Comment by ih-codes** [comment]
@jacko-png Here are the tickets if you want to follow along in the future:

#21874
#21875 

Sorry the images don't render after syncing from JIRA.

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Validated as fixed using v131 (45602) and iPhone 15+ (18.0).
