### ISSUE TITLE
Weird behavior of "close all tabs" button

### ISSUE THREAD

**Issue by DianaABarladeanu** [mozilla-mobile/firefox-ios#22552]
**Steps to reproduce**
1. Install FF.
2. Make sure you have some tabs in tab tray.
3. Go to tab tray and tap on the trashcan button.
4. Choose "cancel".
5. Try to move the position of one of the tabs.
6. Observe.

**Expected behavior**
The tab can be easily moved, no pop up message is displayed.

 **Actual behavior**
Once you try to move a tab, the "close all tabs/cancel" pop up is displayed.
The issue is reproducible on both normal and private tab tray.

**Device & build information**
* Device: iPhone 15 (17.6.1)
* Build version: v131.2 (46395)
* First seen version: ? 
Notes
Attachments: 

https://github.com/user-attachments/assets/5e4019cd-3a81-46fa-ae23-c3be4fa7b39a

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10295)

**Comment by data-sync-user** [comment]
➤ ih-codes commented:

I just checked, and unfortunately that appears to be unrelated to my work.

HOWEVER, I’m pretty sure I know why this is happening though. Just looked and it appears to be the exact same bug I was discussing with Orla yesterday in a different area of Redux.

Line 98 of TabTrayState should return a newly initialized TabTrayState instead of the previous state. And it should set showCloseConfirmation to false.

Someone else can pick this up or I can try to push a fix after my current tab scroll PR is ready. Should be a simple fix.

**Comment by data-sync-user** [comment]
➤ ih-codes commented:

Scratch that. I’m going to have to fix this bug for other things I want to do anyway, so I’ll either do it in my PR or a separate PR. 👍

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v9000 (46854), with iPhone 15 (17.6)

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Verified as fixed on v133(47188), with iPhone 15 (17.6).
