### ISSUE TITLE
[Menu Redesign] Fix the colour of the drag handler at the top of the menu

### ISSUE THREAD

**Issue by Piratesarereal** [mozilla-mobile/firefox-ios#22854]
## Steps to reproduce
-open the new menu.
 
### Expected behavior
The idea is to make sure that the colour being used is the same as the menu when it is at full detent. 

### Actual behavior
When the menu first opens at half detent, the color of the drag handler changes color from a darker color to a lighter one. See the design version below. We are not choosing a color right now, we will update it later.

### Device & build information
* Device: Firefox Beta
* Build version: ? 
* First seen version: ? 
### Notes

When the menu first opens at half detent, the color of the drag handler changes color from the darker color to a lighter one. See the design version below. We are not choosing a color right now, we will update it later. 
The idea is to make sure that the color being used is the same as the menu when it is at full detent. 

Attachments: 

![image](https://github.com/user-attachments/assets/6597d18d-6663-4461-8276-b5e31f984a8d)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10441)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

So, I’ve investigated this. Couple of things:

  * We have no control over the grabber, aside from Apple’s API to show or hide the grabber. It’s colour is dependent on the background behind it.
  * This could be a theming issue of how things reload in the background, but that’s a whole separate investigation in theming, rather than this specific thing or even anything having to do with the menu.

Closing this for now, and
