### ISSUE TITLE
20+ new homepage tabs are opened when I try to open just one new tab

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-ios#23175]
## Steps to reproduce

I don’t have STR, but twice in the last 24 hours Firefox has opened about 20 new homepage tabs. I don’t know what triggers this. It might be when I tap the new toolbar’s Plus button. 

### Expected behavior

Only one new tab should be opened. 

### Actual behavior

About 20 new homepage tabs are opened. I have to closed all the tabs, one by one. 

![IMG_0557](https://github.com/user-attachments/assets/de6c4578-f49d-4a68-a8b8-ebe13427cf5d)

### Device & build information

* Device: iPhone 15 Plus and iOS 18.2
* Build version: Firefox 9000 (47636)
* First seen version: I first saw this problem yesterday (2024-11-15), so I think that was Firefox 9000 (47580).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-10584)

**Comment by cpeterso** [comment]
Today 14 homepage tabs opened unexpectedly.

**Comment by PARAIPAN9** [comment]
@cpeterso, was the app closed over night?

**Comment by PARAIPAN9** [comment]
Hmm, then I incline to believe that maybe it is not related to the Toolbar Redesign and it should occur without it too.

**Comment by data-sync-user** [comment]
➤ Sorin Paraipan commented:

Not able to reproduce this in many attempts. I’ll put it back in TO DO.

**Comment by data-sync-user** [comment]
➤ Diana Andreea Barladeanu commented:

Hi all, we managed to reproduce this issue, here are the steps:

  1. Have the new toolbar redesign enabled.
  2. Go to a webpage.
  3. Turn the device in landscape.
  4. Tap on the + button.
  5. Observe the tab counter.

Expected behaviorOnly one new tab is opened.

Actual behaviorMultiple tabs are opened instead of one.

Notes

!The issue is not reproducible with the old toolbar.

Device & build information
  * Device: iPhone 15 (17.6), iPhone 16+(18.1)
  * Build version: Firefox 9000 (47809)
