### ISSUE TITLE
Find in page is too slow

### ISSUE THREAD

**Issue by trufae** [mozilla-mobile/firefox-ios#2405]
Try opening a large text file like this:

https://api.travis-ci.org/jobs/199987198/log.txt?deansi=true

And find `BR]` in there. it is very slow. I have compared the same operation in other browsers and those are the results:

Safari: option is hidden, but works as expected and fast
Chrome: disables the option when the page is large
Dolphin: performs the operation really fast

I want Firefox to be like Dolphin in this aspect ^^D

**Comment by garvankeeley** [comment]
Can confirm the performance of this on iPhone 5C makes it difficult to use on various sites.

**Comment by garvankeeley** [comment]
This comment explains how Chrome iOS does this much better, and the code is open-source:
https://github.com/brave/browser-ios/issues/421#issuecomment-319779423

**Comment by garvankeeley** [comment]
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1386797

**Comment by garvankeeley** [comment]
I think we close this once they are filed in bugzilla, so closing

**Comment by garrettr** [comment]
Quick note to clarify Chrome iOS's behavior. @trufae said

> Chrome: disables the option when the page is large

which was also my initial assumption—if you visit the test URL in Chrome iOS, the "Find in Page" option is greyed out in the menu. However, while I was reviewing the Chrome iOS source, I noticed that the option is disabled not because the page is large, but because Chrome iOS does not consider a plain text page (e.g. a response with `Content-Type: text/plain`) to be [searchable](https://chromium.googlesource.com/chromium/src.git/+/master/ios/chrome/browser/find_in_page/find_in_page_controller.mm#134).
