### ISSUE TITLE
support for Media Source Extensions API (MSE) on firefox for ios?

### ISSUE THREAD

**Issue by davidolen** [mozilla-mobile/firefox-ios#3520]
I'm trying to use html5 video tag to request Http Live Streamming (HLS) videos, which are simply video segments over http.

For server side authentication, I need to add an Authorization request header for every HLS http request.

But Firefox for IOS refused to add the request header for HLS requests.
(The Desktop version of Firefox does allow the request header to be added)

I know this requires Media Source Extensions API (MSE) to be enabled for the browser.

How to enable MSE on firefox for ios?

**Comment by ExE-Boss** [comment]
Firefox for iOS can’t support MSE unless Apple adds it to Safari for iOS, because Firefox for iOS is currently only a WebKit WebView with a custom UI and Firefox Accounts synchronisation functionality, same with every other iOS browser because of Apple’s App Store policies on web browsers, which have to be at most as good as Safari or inferior, which they enforce by waiting a few versions before allowing third party browsers access to functionality that Safari had access to for years (for example: content blocking/Tracking Protection), of course, the older, slower version of WebKit from iOS 6 that third party browsers can also use has content blocking APIs, which is how Firefox Focus was implemented before iOS 11.

**Comment by davidolen** [comment]
Thanks!
