### ISSUE TITLE
Bitrise should cache Carthage step

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#4856]
The build is quite slow due to the lack of caching of Carthage artifacts. Here is instructions how to add a cache for Carthage: https://discuss.bitrise.io/t/carthage-cache/8202/3

BB takes 22 mins for a normal build and test. After 20 mins, Bitrise is still not finished the Carthage step!

**Comment by isabelrios** [comment]
Yes, there are steps to cache. For some reason while working on the workflow I remove them, may be due to some issues, and I did not add them back, but I'm working on a new workflow to show the results better and I will add the cache steps :) Hopefully builds will run faster after that, I will check the new duration.

**Comment by isabelrios** [comment]
So now with master running the PushInMasterReport workflow, where I have added the cache, the build time has decreased from [40ish](https://app.bitrise.io/build/2b965a8a7b3e7078) mins to [25ish mins](https://app.bitrise.io/build/82f86479e09b446b). 
Closing this issue for now since it refers to cache Carthage while I find more ways to speed up the builds.
@garvankeeley  Feel free to reopen if it is not noticeable the difference...Thanks!
