### ISSUE TITLE
firefox.com needs built-in icon

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#5086]
The favicon background color detection doesn't work for the new icon. This should be an image resource in the app.

![IMG_4172E87C3D06-1 (1)](https://user-images.githubusercontent.com/5495083/58974177-d11e2e80-878f-11e9-8688-6a8d39052536.jpeg)Built

**Comment by wkornewald** [comment]
Also see gitlab.com or fiverr.com (should be a green circle, not square). The favicon is hardly recognizable in the history and top sites section because you pick a too similar background color, especially for favicons that contain lots of transparency. Such favicons implicitly assume that the background for their transparent areas will be a contrast color (most often white/light-grey or black/dark-grey). I don't think that it's a great idea to hard-code site-specific built-in favicons (like the Apple logo in my screenshot). There has to be a more generic solution that works fine for all sites.

![IMG_0237](https://user-images.githubusercontent.com/134387/61181177-0f6dff80-a612-11e9-99fe-574945e12e08.JPG)
