### ISSUE TITLE
Firefox for iOS should ship with a content blocker

### ISSUE THREAD

**Issue by pshirshov** [mozilla-mobile/firefox-ios#5198]
At the moment iOS Firefox has no content blocking capabilities similar to Android version where you may install uBlock Origin and other content blockers.

At the moment we have at least 3 iOS browsers supporting full scale content blockers:

1. Safari
2. Brave
3. Microsoft Edge

It's a real disadvantage for Firefox not to provide users proper content blocking. 

Related: #1271

Also filed as: https://bugzilla.mozilla.org/show_bug.cgi?id=1562041

**Comment by farhanpatel** [comment]
Firefox on iOS does have content blocking and it is turned on by default. Ads are blocked, including trackers and third party cookies. 

Default
![Simulator Screen Shot - iPhone X - 2019-06-27 at 15 08 18](https://user-images.githubusercontent.com/522281/60305857-eac81700-98f2-11e9-9074-d9e891d9f2fd.png)

With Tracking Protection off
![Simulator Screen Shot - iPhone X - 2019-06-27 at 15 47 45](https://user-images.githubusercontent.com/522281/60305867-f3b8e880-98f2-11e9-995b-28a82f861b4d.png)

**Comment by pshirshov** [comment]
It's true that some of the ads are blocked when tracking protection is on. Unfortunately it cannot compare even with ublock origin with standard filter set. Especially when you visit regional websites (russian for example).

**Comment by justindarc** [comment]
The issues you are seeing are likely due to discrepancies between the uBlock lists and the Disconnect blocklists. Our Tracking Protection feature is powered by the Disconnect blocklists: https://disconnect.me/trackerprotection

**Comment by bradfa** [comment]
I found this issue via googling to understand why my use of Firefox Focus as a content blocker for Safari as compared to normal Firefox on iOS 13 led to different ad blocking abilities.  Firefox Focus as a content blocker was much more effective in Safari as compared to the defaults in normal Firefox.

In normal iOS Firefox, the default tracking protection appears to have "Enhanced Tracking Protection" turned ON and the "PROTECTION LEVEL" set to "Standard (default)".  With these settings, some ads are blocked but definitely not all.  By changing the "PROTECTION LEVEL" to "Strict", the ad blocking performance of Firefox is, in my opinion, comparable to using Firefox Focus as a content blocker in Safari.

My observations are for Firefox version 21.0 installed from the App Store.  I am **not** asking that this issue should be reopened, I just wanted to document my findings for others if they arrive here through Googling, too.

**Comment by alexandru** [comment]
The Disconnect list, at the time of writing, has [5135 domain entries](https://disconnect.me/trackerprotection/blocked).

This is good, however [Easy List + Easy Privacy](https://easylist.to/) have around 25000 domain name entries for blocking, and at the time of writing I'm counting ~96,000 content blocking rules (including HTML and cookies). And this doesn't count language specific, or other third party lists.

On the desktop and on Android, we can install uBlock Origin, but we have no such luxury in Firefox for iOS.

To test how inadequate ads blocking protections are in Firefox for iOS, you could do so with a site such as: https://canyoublockit.com/ ; then install a decent content blocker for Safari, like [Wipr](https://giorgiocalderolla.com/wipr.html), compare and contrast - and note that content blocking in Safari is pretty dumb, and can be circumvented too, so this bar is pretty low.

Firefox for iOS fails that test and fails hard. Some ads on some websites are indeed blocked, but it's only those websites that play nice, and that use the well behaved ads exchanges.

Die-hard Firefox users such as myself are then left with DNS-level blocking, via Pi-hole / NextDNS, however these too are insufficient, and TBH I'm leaning towards just using Safari with content blockers.

I hope you reconsider adding actual ads blocking capabilities, especially in light of iOS 14, because otherwise for me Firefox for iOS will be just a bookmarks synchroniser.

**Comment by pshirshov** [comment]
It's lot easier to just use safari/edge/brave instead of trying DNS-level blocking on a mobile (!) device. I'm also wondering why iOS Firefox can't just use system-wide adblocker.

The only reason for me to use Firefox is TreeStyleTab addon for the desktop version, though seems like Edge is going to get some rudimentary support of vertical tabs soon. And TST is crippled now too and I have to apply `userChrome` patches.

 Firefox UX is getting worse and worse over the years. It's not like I'm paying anything for it, but I would be happy to pay for a user-friendly browser with a decent UX. Unfortunately I don't have such an option. Though we have Pocket.

**Comment by captn3m0** [comment]
Content blocking also goes beyond Ads. Time restrictions for example, when set, only work on Safari. Content blockers can be used to avoid distractions as a workaround, but Firefox doesn't support it.

**Comment by pshirshov** [comment]
Seems like noone actually cares. Though it works both ways and Firefox market share makes the best evidence.

**Comment by DarrenSchwartz** [comment]
I care.  I use Firefox exclusively on desktop.  I'm fully invested.  I cannot use it on ios without content blocking.  I begrudgingly use safari there.  I would really like to use Firefox across both platforms, mostly for the bookmark sync and the convenience of sending tabs back and forth.  

As mentioned earlier, tracking protection != content blocking.  There are many types of useless and annoying content on the web and it's getting worse by the day.  Just blocking tracking does not address this.  Would it be so hard to allow the user to select their filter lists?

**Comment by gagarine** [comment]
Why this is closed? Firefox should integrate with content blocker such as AdGuard that works on iOS Safari but not on Firefox. The built in Firefox blocker is not enough.

**Comment by SimonBasca** [comment]
@gagarine there is a different bug open for this discussion. #7374
