### ISSUE TITLE
"https://web.whatsapp.com/" redirects to "https://whatsapp.com/"

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#5295]
Build: 18.2 (15817)
Device: iPhone Xr
iOS: 12.2

Steps to reproduce:
1. Go to "https://web.whatsapp.com/"

Actual results: 
- "https://whatsapp.com/" is loaded.

**Comment by garvankeeley** [comment]
Is this related to Desktop mode? The bug doesn't mention that.

**Comment by SimonBasca** [comment]
@garvankeeley I think it is. Going to whatsapp.com, requesting desktop site and going to "https://web.whatsapp.com/" will load the page correctly. However in Safari going to "https://web.whatsapp.com/" will load the page correctly.

**Comment by canaltinova** [comment]
I was also using this STR to load the `https://web.whatsapp.com/`:
- Navigate to "https://web.whatsapp.com/"
- It redirects to "https://www.whatsapp.com/"
- Touch Three dots > "Request Desktop Site"
- It loads back the "https://web.whatsapp.com/"

Now that doesn't work. After touching "Request Desktop Site" button, it reloads "https://www.whatsapp.com/" and impossible to open the app(https://web.whatsapp.com).

**Comment by canaltinova** [comment]
Did `git bisect` and it looks like this is the commit that introduced this bug: f1a4efb62d416edb543b91011d2b423c4ef3418a

**Comment by farhanpatel** [comment]
@canaltinova what version of the app are you using?

**Comment by canaltinova** [comment]
@farhanpatel I’m using Firefox Beta version 18.0 (15690).

**Comment by garvankeeley** [comment]
To clarify, is there a way to login and use whatsapp web client on iOS in Safari? I just see a QR code that has to be scanned to login, not sure how one actually logs in to the web client on iOS.

**Comment by SimonBasca** [comment]
Just as an extra note. The way Chrome works is that after going to https://www.whatsapp.com/ and requesting desktop mode will redirect to https://web.whatsapp.com/

The way Firefox works, going to https://www.whatsapp.com/ and requesting desktop site will direct to https://www.whatsapp.com. However while desktop mode is active on the tab, manually typing the https://web.whatsapp.com/ will direct to the correct URL. 

This was the initial issue. Also as Garvin mentioned I also fail to see the use case for Web Whatapp in iOS.

**Comment by canaltinova** [comment]
> To clarify, is there a way to login and use whatsapp web client on iOS in Safari?

There is no Whatsapp app in iPad and your Whatsapp account is tied to your phone number. To use Whatsapp in iPad, there is a hack, and that is basically using "Watsapp Web" in iPad(with switching to desktop mode). Otherwise, there is no other way to use it. Currently you can use my STR above to enter whatsapp web with Chrome and Safari for iPad but not possible with Firefox. That is because it doesn't redirect me back to `web.whatsapp.com` anymore.

> I just see a QR code that has to be scanned to login, not sure how one actually logs in to the web client on iOS.

If you are seeing that QR code, that means you've successfully entered to Whatsapp Web. To enter it, you need to scan that code with your Whatsapp app in your phone("Settings > Whatsapp Web/Desktop > Scan QR code" inside the iOS app).

> However while desktop mode is active on the tab, manually typing the https://web.whatsapp.com/ will direct to the correct URL.

That will just add another step to STR which is writing the URL one more time. Which is just unnecessary. Especially when it was working before the commit that I mentioned before.

> Also as Garvin mentioned I also fail to see the use case for Web Whatapp in iOS.

I know it's not a very commonly used app in the U.S. and the STR is quite an effort. But if you search it online you'll see that this is the only way to use it in iPad currently([example](https://www.macworld.co.uk/how-to/iosapps/whatsapp-ipad-3636728/)). But in Europe, it's pretty popular app and lots of people use it as their primary messaging app. So I believe this is an important issue.

**Comment by SimonBasca** [comment]
Fixed by #5682
