### ISSUE TITLE
Data Collection: Is DeviceName really necessary?

### ISSUE THREAD

**Issue by lemeb** [mozilla-mobile/firefox-ios#5305]
Hi Mozilla, thanks for the amazing work that you're doing! 👋

I was looking at the [Mobile Marketing Automation](../blob/master/Docs/MMA.md) documentation, because it wasn't clear from the [privacy policy](https://www.mozilla.org/en-US/privacy/firefox/) that the data sent to Leanplum was totally anonymized. And there is a line that got my attention:

` "deviceName" -> "sdaswani-31710"       // System device name.`

This is sent every time the app is started, apparently. Is this really necessary? I mean, just googling the example string retrieves a Mozilla contributor, so I wouldn't say that the data passed to Leanplum is anonymized. 

I'm sure there might be a good explanation there, but I was a little startled when I saw this.

In any case, thanks so much for your work! Firefox on iOS is 🔥 :)

**Comment by farhanpatel** [comment]
you're right @lemeb it isnt really necessary. When we first integrated Leanplum we made sure that the device name was only sent when the app was in development mode because thats when we need it. We use the device name to send Leanplum push notifications to development devices so we can test notifications before sending them to everyone. Here is the PR from 2 years ago 
https://github.com/Leanplum/Leanplum-iOS-SDK/commit/bc692f4fbd2ee74571714e6a69687fb3e74a16f7 by one of our engineers.

To clarify, the behaviour listed in the doc here but is not collected for anyone except for a handful of developers on the project. 

Thanks for raising the concern and I'm happy you took the time to read the docs! Please feel free to open this issue up again if you feel the need to.
