### ISSUE TITLE
ETP: Change fingerprinting list from disconnect to mozilla curated

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#5559]
There is a special subset of the disconnect FP list that we should be using to align with desktop.

**Comment by athomasmoz** [comment]
Waiting on priv/sec team to provide the list.

**Comment by skim1102** [comment]
Please ping me when this information is needed. Or if there is a deadline you need the information by I can post the latest on that deadline. The list changes do not have a routine so if I provide one now there's a high likelihood you'll need them again closer the release. 

As a reference on how the file will be formatted, I attached a .txt file (because I can't upload .json file on GitHub) of the JSON formatted domains I have previously provided to @garvankeeley 
[base-fingerprinting-track.txt](https://github.com/mozilla-mobile/firefox-ios/files/3941741/base-fingerprinting-track.txt)

**Comment by garvankeeley** [comment]
@skim1102 I am working on code to handle this file now. When will this file be available in mozilla-services/shavar-prod-lists repo?

**Comment by skim1102** [comment]
@garvankeeley, this file should be available by the end of next week. When is the soft code freeze?

**Comment by skim1102** [comment]
Since we now have versioned lists and each versioned lists have different domains, the lists will have to be grabbed from the release branch of Firefox. Meaning, right now (Jan 3rd, 2020) the release is 71 but next week it will be 72. So whoever is releasing a new version of  Firefox iOS will have to change the [branch/path](https://github.com/mozilla-mobile/firefox-ios/blob/master/Cartfile#L16
Cartfile:16) to get the latest release branch on shavar-prod-lists. Let me know if you have any questions!

**Comment by garvankeeley** [comment]
filed as https://github.com/mozilla-mobile/firefox-ios/issues/5980
