### ISSUE TITLE
Label for Synced tabs is smaller than the other labels on Library panels view

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#5853]
Seen on latest beta **v21.x: 16860**

***Steps***
Go to Library panels view
Look at the Synchronized tabs

***Expected***
All labels have the same size

***Actual***
See screenshot:
![IMG_BFD3B1B73693-1](https://user-images.githubusercontent.com/1897507/70140369-d7d12400-1694-11ea-8344-7faa1b8d9842.jpeg)

In case this helps, if I set the device to another language, the label is not translated but it fits correctly:
![IMG_4549C54DFC7D-1](https://user-images.githubusercontent.com/1897507/70140533-372f3400-1695-11ea-8a50-4595867bf838.jpeg)

**Comment by athomasmoz** [comment]
Suggested fix:
* update the UK EN translation to be Synced Tabs (@Delphine Garvan made a recommendation for this in Pontoon, can you take a look?)
* Add ellipsis rather than shrink text

**Comment by Delphine** [comment]
Thanks for filing! There seem to be a few issues here, I'll try to capture it all.

So if we update the en-GB translation on Pontoon, that will only fix our en-GB version. But it won't fix the other problem, which is that many other languages will continue to truncate - and in some cases this means losing a lot of the sense of the "Synced tabs" string. I checked French for example, and like some other languages the text is cut off from the screen, which makes it hard to understand what this is about (granted, the sync arrow image helps understand - but still). 

I think it may be good to make sure that all locales are aware that there is very limited space for this string, in order for them to find a workaround (note the size of a localized string is in general up to 25% longer than in en-US, so with mobile, we unfortunately often reach this issue a lot).

In order to do this, you would have to add a specific recommendation in the localization comments for this string, asking to try and not exceed a certain number of letters if possible, because otherwise it will truncate. This will let localizers know they need to update their string and possibly abbreviate it - or even form it in a way that the sense of the words won't be lost, even if it truncates.

Concerning adding the recommendation in the localization notes, there are a few ways you can go about this:
* You can update the string ID now, add the comment, and send us a string export - and then get that work back in, for a v21 dot release. The risk here is that we may lose some of the existing localizations, since changing the string ID "kills" existing translations. I can send some comms out about this to spread the word as much as possible, which would probably ensure most of the "top locales" would be covered
* You could also live with this until the next release, and then update the string comment and string ID so localizers see it then.

I think how we go about this should be a Product decision.

(also, small nit: the proposed en-GB string in Pontoon reads "Synched" instead of "Synced". I can ping the localizer for an update though, once a decision on how to move forwards is reached ;) )

**Comment by garvankeeley** [comment]
I like the idea you had update the IDs and add a new comment on these strings that they need to be kept as short as possible.

**Comment by csuciu** [comment]
Verified as fixed on master 1c5d2186.

**Comment by dnarcese** [comment]
@Delphine is there an update on whether this communication went out to contributors or is there something more you are waiting for from our side? It looks like this is still an issue - see #6145
