### ISSUE TITLE
[FxA Upgrade] Debug: Error messageIncomplete notification when changing the FxA pass on desktop

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#6186]
1. Login with the same account on iOS and Desktop.
2. On desktop, go to the account management page and change the password.

Result: iOS receives the following notification:  Debug: Error messageIncomplete.

version: beta

**Comment by garvankeeley** [comment]
Dev note: Changing password notification is not supposed to arrive to the client https://github.com/mozilla/fxa/blob/52572ebece391051f1eb65970548851bde823d42/packages/fxa-auth-server/lib/push.js#L122-L162

**Comment by eoger** [comment]
<img width="83" alt="Screen Shot 2020-03-03 at 1 30 32 PM" src="https://user-images.githubusercontent.com/6424575/75807377-489ae180-5d53-11ea-877d-f71bde521f5a.png">

This is a device record from an iOS device using the OAuth flow. This would explain why the push filtering is not working.

@rfk how much work would it be to get these fields to be populated correctly? Alternatively we could deploy a quick fix to do the filtering with the `client_id` instead.

**Comment by rfk** [comment]
Ugh. Nice catch. This could get fiddly.

Are you able to tell from the device record whether or not is has a corresponding `sessionToken` attached? I feel like it *should* because you're using the webchannel flow, but perhaps my expectation is incorrect there.

> Alternatively we could deploy a quick fix to do the filtering with the client_id instead.

I think this would be a good approach, but I'm not sure how "quick" a fix it would be; the list of devices is fetched via `db.devices(uid)` which only uses the data from the auth-server database, so it knows whether the device record has an associated refresh token, but it doesn't look up the corresponding client_id (which lives in the oauth-server database).

Longer term, I wonder if we could have clients provide a list of the messages they're prepared to accept rather than guessing it based on UA info. But that would be a bigger project than we can take on in this issue.

**Comment by rfk** [comment]
@eoger ping me on slack tomorrow (my) morning if you'd like to brainstorm an approach here synchronously.

**Comment by garvankeeley** [comment]
closed by https://github.com/mozilla/application-services/issues/2758

**Comment by csuciu** [comment]
Verified as fixed on 23.1 (17435). There's no push notification received on iOS after changing the pass on desktop.
