### ISSUE TITLE
Crashes when trying to add account picture

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla-mobile/firefox-ios#6232]
**Build:**
iOS: FF Beta 23.1 (17361)
*EDIT*: Re-tested on 22.0(17157), crash on iPhone X(13.2.2) but not on iPhone x(12.4) 

**Device information:**
iPhone X(13.2.2)
iPhone 8 (13.2.3)

**Steps to reproduce:**
1. Either create an account or sign in with an account which has no picture added on Beta 23.1 (17361).
2. Go to Manage Account and Devices section and and tap to add an account picture. 
3.Tap to Upload picture.  

**Expected result:**
Methods of uploading the picture pop up. Tapping on any one of the (take a picture, upload from device) performs the appropriate action. 

**Actual results:**
Firefox browser stops working and crashes. 

![App-crash-when-trying-to-upload](https://user-images.githubusercontent.com/53306802/76087582-23121000-5fbf-11ea-9fce-236460671ea2.gif)

**Comment by csuciu** [comment]
Crash log:
[Client-2020-03-06-153043.ips.beta.zip](https://github.com/mozilla-mobile/firefox-ios/files/4298560/Client-2020-03-06-153043.ips.beta.zip)

**Comment by mirunacurtean** [comment]
Workaround: Sign in with account on Desktop or Android and add picture on one of them. After restarting the app on iOS the picture (avatar) will be added as well in iOS browser in Hamburger menu, Settings and Manage Account and Devices section.

**Comment by garvankeeley** [comment]
Does the current release work ok?

**Comment by mirunacurtean** [comment]
Yes, sorry, I did not notice I'd added the previous build id. But I re-tested in any case and it still occurs.  

![App-crash](https://user-images.githubusercontent.com/53306802/76099272-89a12900-5fd3-11ea-94aa-dfefb52fbfb1.gif)

**Comment by mirunacurtean** [comment]
Re-tested on 22.0(17157) with a new account and I could reproduce the issue still, on iPhone X(13.2.2) but not on iPhone x(12.4) so it points towards being software specific and not a regression.

**Comment by csuciu** [comment]
I was also able to reproduce the crash when trying to add a picture to a newly created account.
That happened on an iPhone 11 running iOS 13.3 and latest Beta 23.1

**Comment by abodea** [comment]
I was also, able to reproduce this issue but only once on the **Beta 24.0 (17528).** with the **iPhone X (13.3.1)**.

**Comment by RemakingEden** [comment]
I can reproduce this every time as long as the user freshly logs in. On the second attempt the app will no longer crash.

Device details:
* iPhone 8
* iOS 13.3.1
* Firefox iOS 24.0 (17560)

**Comment by garvankeeley** [comment]
Thanks for adding your repro steps. I have an iPhone 8 and changing the account picture after a fresh log in to FxA didn't crash.

**Comment by csuciu** [comment]
@garvankeeley This crash might occur only when sync is running. At least, that is what noticed in  the latest testing. Try signing in with a large account on a freshly installed build and change the picture while the initial sync is running.

I also get this in the debugger when the app is crashing:
2020-04-02 18:20:41.770843+0300 Client[22924:10410755] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIDocumentMenuViewController (<UIDocumentMenuViewController: 0x10dbf14b0>). In its current trait environment, the modalPresentationStyle of a UIDocumentMenuViewController with this style is UIModalPresentationPopover. You must provide location information for this popover through the view controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the view controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'
*** First throw call stack:
(0x1b2f8896c 0x1b2ca1028 0x1b694778c 0x1b6951c08 0x1b694f6cc 0x1b6a3faac 0x1b70804ac 0x1b706fad0 0x1b70a0d20 0x1b2f03524 0x1b2efe1c4 0x1b2efe774 0x1b2efdf40 0x1bd17b534 0x1b7076a60 0x10349ea6c 0x1b2d7ce18)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by garvankeeley** [comment]
Great find!! This is a big step forward in figuring this bug out, thanks.

**Comment by garvankeeley** [comment]
Related issue https://stackoverflow.com/questions/58164583/wkwebview-with-the-new-ios13-modal-crash-when-a-file-picker-is-invoked

That one is 100% repro, where this bug is lower repro. That bug is saying if the parent VC with the WKWebView is not fullscreen, the image picker will crash. But our seems to be fullscreen.

**Comment by garvankeeley** [comment]
Key STR step: *browse to Settings first, then show the FxA Account settings.*

Going to FxA settings from the app menu directly doesn't crash.

**Comment by nbhasin2** [comment]
There are multiple ways that we can achieve this but going with a simple full screen view controller modal. 

Below is another way that you can do if we want to keep the card view: 
https://medium.com/swlh/popover-menu-over-cards-containing-webkit-views-on-ios-13-a16705aff8af

**Comment by SimonBasca** [comment]
Verified fix in master f57c1903597. 
@nbhasin2  I don't see this uplifted to 25.x branch, should we consider doing a dot release for this issue?

**Comment by garvankeeley** [comment]
We have higher crashers than this would could fix and uplift, the rate on this is very low. But if we are doing a point release we should certainly uplift this one.
