### ISSUE TITLE
Spike: Glean

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6259]
**Vision**

Switching to Glean will give us a number of growth and usage dashboards (GUD) for free, and it fixes a lot of issues with legacy telemetry.  Also, Glean is going to be what all of Android and soon Desktop will be using.

----

**Acceptance Criteria**

* Tickets created for changes are needed on our side
* Determine any risks or blockers from Travis

**Comment by athomasmoz** [comment]
Risk/concern: this creates another dependency. Need to determine what's their plan for releases of the libraries and keeping up with the latest OS updates. SLA for that?

**Comment by kaylagalway** [comment]
In order to be compliant with the California Privacy Law with the June deadline, the following steps need to be completed:
- Add the Glean SDK to the product, as described here.
- File a bug for Glean pipeline to enable your application id.
- Update the telemetry documentation of your products to link to the docs automatically generated by the Glean SDK
- Add the legacy telemetry client id to the deletion request ping to comply with data protection regulations (e.g. GDPR, CCPA) by following the instructions for adding secondary ids to the deletion request ping.

There is already a [PR](https://github.com/mozilla-mobile/firefox-ios/pull/6441) open to add the Glean SDK to the product, which I will be reviewing. @travis79 is going to file the bug for the Glean pipeline to enable the application id. I'm going to update the telemetry documentation and then we are going to do the final step together.

After those steps above are complete, we will need about two weeks of data so that we can complete the final step of verifying that data for the baseline ping is flowing in. We are hoping we can do this on the sooner side through a beta release of the app. Will verify this is possible.

**Comment by AmyYLee** [comment]
@kaylagalway Hi, I see that I'm assigned to this item. Are there any UX requirements?

**Comment by kaylagalway** [comment]
> @kaylagalway Hi, I see that I'm assigned to this item. Are there any UX requirements?

Not that I know of! Glean is all behind the scenes work, so there shouldn't be any user facing changes.

**Comment by AmyYLee** [comment]
@kaylagalway Okay I'm removing myself from the assigned list if no UX is needed.

**Comment by kaylagalway** [comment]
@AmyYLee I am just realizing that you may have been assigned to this in case there needs to be any UI additions for deleting user usage data from Glean.  

I am going to confirm what the new California privacy law requires with the Glean team and see if we need to make any front end changes. I initially thought we would delete when a user toggles "Send Usage Data", but I am not 100% sure if that would be compliant or not.

**Comment by travis79** [comment]
No additions should need to be made.  Glean will hook up to the existing telemetry preference and trigger the deletion request when telemetry is disabled.  This means any existing UI should stay the same.

**Comment by kaylagalway** [comment]
Great, thanks @travis79 !

**Comment by kaylagalway** [comment]
The following tickets have been created for the Glean work: 
https://github.com/mozilla-mobile/firefox-ios/issues/6515
https://github.com/mozilla-mobile/firefox-ios/issues/6516
https://github.com/mozilla-mobile/firefox-ios/issues/6518
