### ISSUE TITLE
Pinned sites do not sync from iOS to desktop browser

### ISSUE THREAD

**Issue by Githubuxer** [mozilla-mobile/firefox-ios#6395]
Pinned sites do not sync from iOS browser to desktop browser.

(Edited post to correct ‘top sites’ to ‘pinned sites’)

**Comment by linacambridge** [comment]
Unfortunately, we don't currently support syncing Top Sites on mobile. There's limited support for syncing top sites between Desktop and Desktop, but the way it's done is a bit of a hack.

**Comment by Githubuxer** [comment]
> Unfortunately, we don't currently support syncing Top Sites on mobile. There's limited support for syncing top sites between Desktop and Desktop, but the way it's done is a bit of a hack.

Thanks for the info, so there is no plan to implement this? It’s not very convenient to have to maintain two independent sets of top sites, it significantly finishes the value of the feature.

What makes it so elusive? Isn’t it just syncing a series of urls to be populated in that space? If tabs can be synced, why not top sites?

**Comment by linacambridge** [comment]
> Thanks for the info, so there is no plan to implement this? It’s not very convenient to have to maintain two independent sets of top sites, it significantly diminishes the value of the feature.

Thank you for filing the ticket! 😊 I hear you, it definitely limits their usefulness, and it's surprising that we don't sync it! I think we'd like to do it eventually, but there's some work that needs to happen first, and we haven't prioritized it at all yet.

It's not that we'll never do it, but it hasn't been part of our plans yet, so there isn't a firm time commitment of when it'll happen.

> Isn’t it just syncing a series of urls to be populated in that space?

Basically, yes. I think the harder parts are all the layers above it:

* Do we sync them as a separate data choice, and add a new checkbox specifically for "Top Sites", or as part of something else like preferences?
* If we go with a new checkbox, will that add too much clutter, as Desktop already syncs 6 (8, if you toggle the prefs for addresses and credit cards) other data types? If part of preferences, how do we handle the types of preferences being completely different between iOS, Android, and Desktop?
* Do we sync just your pinned list, or everything?
* Syncing only pinned sites is simpler in some ways: title, URL, and image. But, how do we sync high-res favicons and preview images, given that they might expire, or not map well between platforms? For example, Desktop has thumbnails for top sites, but those scaled-down thumbnails might not look great on a phone...but could work on a tablet? Will these images overrun our storage quotas on the server? Can we just sync the preview image URLs instead? If we do that, there might be privacy concerns with fetching them in the background on other devices.
* If we sync pinned and non-pinned, we'll need to add plumbing to observe whenever the list changes. Currently, we only have to generate the list of top sites when you open a new tab, so we can query it from the database; if we wanted to sync changes, we'd also need to know when it changes in response to visits.
* Or, do we sync the information needed for determining top sites—signals like frecency, maybe dwell time in the future—and let each device reconstruct the list from the same set of data? If so, we'll need to extend history sync to support that, which has its own challenges: we don't sync your full set of history, for example, and adding fields to collections, especially churn-y ones like history, is tricky to do because of how Sync represents data on the server.
* Once we answer those questions, we'll also need to change how we store them, since Desktop and iOS currently use completely different storage backends for top sites, and finally write the sync glue.

None of those are show-stoppers on their own, and we can come up with something simpler that's good enough and covers the basics...and it would be better than what we have now, which is nothing at all. ☹️ But there's still a fair bit of product, engineering, and design work that has to go into it.

**Comment by Githubuxer** [comment]
Wow, thank you for the thorough response.

I realize I had muddled my words slightly, I’m only interested in syncing pinned sites. Just because using that as homepage/new tab is just such a great opener to be able to access the same pinned sites everywhere, but I supposed if it is only a few rows I’ll just do. Manually on every device I own.

Thanks for explaining the reasoning and breadth of everything required and I look forward to maybe one day Having synced ‘pinned’ tabs for efficiency on all devices.

**Comment by linacambridge** [comment]
> I realize I had muddled my words slightly, I’m only interested in syncing pinned sites.

No worries, thanks for bringing it up, and for clarifying! I saw you commented on Bugzilla also; I'll go ahead and file a separate bug there for you, and link to the discussion here. Thanks again!

**Comment by Githubuxer** [comment]
Many thanks! I went to delete the comment I made on the bugzilla thread that isn’t needed anymore but didn’t see a way to delete it.

**Comment by linacambridge** [comment]
> I went to delete the comment I made on the bugzilla thread that isn’t needed anymore but didn’t see a way to delete it.

Bugzilla doesn't have a way to delete comments, but it's not hurting anything being there. I appreciate your tidiness, though! ✨

> Should I close this issue now? I’m still a little confused on the overlap of GitHub and Bugzilla.

No problem, it's kind of different for each team, and even each project—our team uses a mix of Bugzilla and GitHub, too, and, if an issue isn't in the right place, someone will come along and move it. But, since it's tracked in a Bugzilla ticket now, yes, please feel free to close this issue.

Thank you!

**Comment by Githubuxer** [comment]
Great, thanks again! Thanks 🙏
