### ISSUE TITLE
FXIOS-361 ⁃ Firefox crashes when I try to access "Logins & Passwords"

### ISSUE THREAD

**Issue by user55** [mozilla-mobile/firefox-ios#6451]
## Steps to reproduce
1. Go to Menu
2. Tap "Logins & Passwords"
### Expected behavior
Show a "Logins & Passwords" Menu
### Actual behavior
Crash
### Device & build information
* Device: iPad Air 2 13.3.1
* Build version: 24.1 (17574)
### Notes
Attachments: 
Logs
[ffios.zip](https://github.com/mozilla-mobile/firefox-ios/files/4522552/ffios.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2358)

**Comment by garvankeeley** [comment]
Thanks for the report and the logs! I can't yet see anything in the logs indicating what the problem is. Can you reproduce this reliably?

**Comment by user55** [comment]
Yes, it happens every time I tap it.

**Comment by garvankeeley** [comment]
Ok thanks, I am trying to see if I can find your crash report in the system.

**Comment by SimonBasca** [comment]
@user55 can you try reproducing  with the latest  AppStore version v.25.0 (17803)?

**Comment by user55** [comment]
[logs.zip](https://github.com/mozilla-mobile/firefox-ios/files/4575790/logs.zip)

**Comment by garvankeeley** [comment]
Dev note, am seeing this on repeat runs of the app: `Did not find rustAccounts.syncAuthState in Keychain with label rustAccounts.syncAuthState.ACEF3E54-E346-49EC-8F67-46D2A33A63B2.` Not sure of the implications yet. That would affect sync, not sure if that could cause Logins view to crash.

**Comment by phyber** [comment]
I've been experiencing this crash for years. No idea which Firefox version it started on, but it's persisted across all Firefox and iOS updates since it began, even over iPhone/iPad restores.

I do use Firefox sync, so whatever the problem seems to persist via that. It doesn't crash my desktop Firefox, and there is nothing special in the logins and passwords when viewed on the desktop.

I don't actually use the feature, but it means I can't access the "ask if passwords should be saved" toggle in Firefox, resulting in useless prompts on iOS when logging into sites.

**Comment by dnarcese** [comment]
similar to #7712
