### ISSUE TITLE
The Mobile Site is displayed after Requesting Desktop site

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#6569]
## Steps to reproduce
1. Go to "Facebook.com" 
1. Open Page Action menu
1. Tap Request Desktop site
    1. Expected behavior

* Desktop version should load.
    1. Actual behavior
* The mobile version is displayed. 
    1. Device & build information
* Device: iPhone Xr
* Build version: 13.4
    1. Notes

1. Deleting the "m." characters from the URL while the Request desktop site blue indicator is displayed in the Page Action menu will load the Desktop version.
1. After note 2) requesting mobile site works.
1. Reproducible on v.24.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2410)

**Comment by jgtoriginal** [comment]
This is not a bug, because when you enter from a mobile device facebook redirects you from `www.facebook.com` to `m.facebook.com`. Now `m.facebook.com` looks the same on desktop than on mobile, it just shows a mobile styled site.
So if after tapping on `Request desktop site` you go to `www.facebook.com` you will see that facebook takes your request as a desktop request and doesn't redirect you to `m.facebook.com` but rather serves you the desktop version. This means that this feature is working as expected.

**Comment by karlcow** [comment]
Let's hijack this bug, because this is actually happening on other sites with responsive design. 

1. Go to https://www.honeycode.aws/
2. Request desktop site, and you get the same site

because of responsive design. But we could imagine that when the request the desktop version is activated, the viewport is being artificially set to 960px to simulate a desktop environment.
