### ISSUE TITLE
 Private tab loses cookies

### ISSUE THREAD

**Issue by qqvm** [mozilla-mobile/firefox-ios#6571]
## Steps to reproduce
Open first website and login in a private tab.
Open new tab and navigate to another site. Spend some time here.
Go back to the first. Session might be broken.
Also sometimes it happens when Firefox is minimized and other application is in focus for some time.
### Expected behavior
Tab has cookies and active session.
### Actual behavior
Private tab loses cookies almost every time when I switch to another tab and do some activity here.
### Device & build information
* Device: iPhone
* Build version: 25.0 (17803)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2411)

**Comment by jgtoriginal** [comment]
That's the expected behavior.
**Private Browsing -> Firefox won't remember any of your history or cookies, but new bookmarks will be saved.**
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-05-10 at 21 54 09](https://user-images.githubusercontent.com/1785392/81515044-9f4f0980-9308-11ea-943e-585c063e46cf.png)

**Comment by qqvm** [comment]
This is good but it should delete them after tab is closed. I don’t need loosing cookies when switching tabs. If I haven’t closed the tab means that I still need it and it’s data.
