### ISSUE TITLE
[Today Widget] Spike

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#6661]
Spike to research ideas for the today widget. 

- look at other app's today widgets
- determine different options of what features can be included
- explore user reviews
- document research and ideas in this ticket
- explore code relating to this feature ([TodayViewController](https://github.com/mozilla-mobile/firefox-ios/blob/master/Extensions/Today/TodayViewController.swift ))

**Comment by noorhashem** [comment]
- [X] Researching other browser apps widgets : 
* Chrome: 

**Quick Actions**
   1. make a new search by the default search engine in the browser
   2. make incognito search
   3. make voice search
   4. scan QR code
<img width="259" alt="chromeWidget" src="https://user-images.githubusercontent.com/11700198/82747026-b3c5e400-9d95-11ea-8bde-32f32f9403ca.jpg">


 **Suggested Sites**
      has the top most frequent sites the user visits.
<img width="259" alt="Screen Shot 2020-05-23 at 7 21 36 AM" src="https://user-images.githubusercontent.com/11700198/82747028-bd4f4c00-9d95-11ea-84d9-0b1ae422d612.png">
* Opera
doesn't have a today widget

- [X] Different features that can be added : 
1. Search with (pick search engine as in Mockups by Bram or the default search engine of the browser)
2. Voice Search 
3. Open Pocket List (quick access to pocket from the widget)
4. Save copied link to Pocket list, since there is a open copied link in the widget>
5. Copied link can be sent to any of the synced tabs
6. Open Synced tabs directly from widget
7. close all private windows/tabs from widget (I found this in chrome for Android, as a floating notification, and once clicked it closed all opened private tabs without need to go to browser and close them)
8. scan QR code
9. Open mobile bookmarks
10. Save copied link to mobile bookmarks of Firefox ( usecase: a link copied from any app and instead of opening it in the browser, you can directly bookmark it. similar to save to pocket suggested feature)

- [X] Explored code relating to Today Widget : 
* SnapKit constraints
* Different UIViews used

**Comment by brampitoyo** [comment]
@dnarcese @noorhashem Hi! Here are some easy, low-hanging fruit improvement that we can make to our current widget:

- Rename widget title: Firefox → Firefox – Search (this gives us more naming spaces when we build more widgets e.g. Top Sites)
- Rename button labels:
    - New Tab → Search – also change the icon from a plus to a magnifying glass
    - New Private Tab → Private Search – keep icon the same
- Improve colour contrast:
    - Text label colour: [`label`](https://developer.apple.com/documentation/uikit/uicolor/3173131-label) (this will switch dynamically between light and dark?).
    - Search
        - Icon colour: On-Light – Ink 80 `#20123a`
        - Icon background: Light Foundation – Light Grey 10 `#f9f9fb`
    - Private Search
        - Icon colour: On-Dark – Light Grey 5 `#fbfbfe`
        - Icon background: Private Gradient
`background-image: linear-gradient(45deg, #7529A7 0%, #492E85 50%, #383372 100%);
border-radius: 30px;`
- Question: is there a default value for the sizes of widget icon and text labels? If yes, is it possible to follow it?

I believe that we already have assets for both the search (magnifying glass) as well as the private browsing (mask) icons? Would you like me to re-link to SVG files, or would you be able to find it yourself?

The updated design looks a little something along these lines:

<img width="320" src="https://user-images.githubusercontent.com/51007/82963574-63f64f80-a017-11ea-8855-8cada2e65dc9.png"><img width="320" src="https://user-images.githubusercontent.com/51007/82963578-65c01300-a017-11ea-9361-ef965ca46f22.png">

What do you think?

-----

As a next project, @athomasmoz and I thought that working on Top Sites would be a great idea. Here’s an example of a Top Sites widget that shows the user’s 8 sites:

<img width="320" src="https://user-images.githubusercontent.com/51007/82962818-648de680-a015-11ea-87ef-a937b043de43.png"><img width="320" src="https://user-images.githubusercontent.com/51007/82962822-6788d700-a015-11ea-8703-f67beff44bef.png">

**Comment by noorhashem** [comment]
@brampitoyo Thank you for the improvements suggestions, I will check the assets and get back to you if anything is missing.

**Comment by noorhashem** [comment]
@brampitoyo  Hey Bram, can you provide me with the pdf files for the full buttons for search and private search as in the mockups? so they can be identical to your design. 

I only have the icons for the search lens and the mask in the assets and was trying to programmatically recreate the buttons.

**Comment by brampitoyo** [comment]
@noorhashem Sorry for my overdue reply! The PDF assets are attached here.

- [search.pdf](https://github.com/mozilla-mobile/firefox-ios/files/4796391/search.pdf)
- [private-search.pdf](https://github.com/mozilla-mobile/firefox-ios/files/4796392/private-search.pdf)
- [close-private-tabs.pdf](https://github.com/mozilla-mobile/firefox-ios/files/4796395/close-private-tabs.pdf) (relevant for #6794)
