### ISSUE TITLE
Drop In Sync Counts, May 26th

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6816]
From Ana:
Last week we noticed that there was a slight drop in Success Rate for our bookmarks sync engine, and we weren't exactly sure why this might be happening.

After some investigation, Vlad and I noticed that there was a steep drop in `Total Sync Counts` on iOS for all engines on May 29th, which coincided with the release of iOS V26. (https://sql.telemetry.mozilla.org/queries/71643#180397).

Given that the drop coincides with the release, we looked into the number of sync users on iOS, grouped by version. From the graph we could see that there were significantly fewer users signed into sync on the newest version (https://sql.telemetry.mozilla.org/queries/71967#180589). 

I spoke with Leif, and he has two potential hypotheses: that either the metrics implemented are not recording everything, or potentially users are being signed out during the upgrade.

### Device & build information
* Device: N/A
* Build version: v26

**Comment by garvankeeley** [comment]
All indications are that users are getting signed out, but I can't find any code change that would account for this.

**Comment by athomasmoz** [comment]
Could this be related to the durable sync update?

**Comment by garvankeeley** [comment]
I don't know anything about durable sync, @rfk and @eoger do you know anything about how that might have affected this issue?

**Comment by rfk** [comment]
I can't think of a plausible way in which durable sync would have affected this. Perhaps if there's an edge-case where durable sync rejects data that the existing sync server would accept, this would show up as more failed syncs. But I feel like we should be able to see the resulting errors somewhere explicitly in our metrics, rather than just as an absence of metrics.

**Comment by rfk** [comment]
One thing for us to try here, is to see if we can get a graph of "unique users per day from iOS" from the sync server-side telemetry. This should be a good check to understand whether less users are actually syncing, or if it's only their sync pings which are not being submitted.

(As mentioned in email thread, the graph that we thought was showing a drop in FxA DAU from iOS, was I think mostly reflecting a change in how DAU is calculated, ref https://analytics.amplitude.com/mozilla-corp/chart/nmvssqg)

**Comment by rfk** [comment]
>  I will reach out to the services ops folks to see what's possible.

I was able to get some access to the syncserver request logs. Here is a (redacted) graph of the number of unique userids seen by the sync servers each day since April 1st, showing the old python-based sync nodes (blue) and the new durable sync nodes (red) with a combined total (yellow):

![Capture](https://user-images.githubusercontent.com/34695/85494658-723a8a00-b61c-11ea-9c14-bc30774cd1b0.PNG)

This shows a slight drop in early June, but otherwise pretty steady (and you can see the gradual migration of users over to durable sync nodes).

It's all circumstantial, but I think this argues in favour of the sync ping drop being a metrics-submission bug of some kind.

**Comment by garvankeeley** [comment]
I'll recap a few things we know:
1) FxA is not a problem (as per Ryan's investigation)
2) v25 to v26 is not the problem: v26 rolled out progressively at 1% on may 28th, and only reached significant uptake by June 3rd, peaking by June 7th. The problem graph shows a steep drop on May 26th, essentially a week early and the sharp drop is inconsistent with progressive app rollout.
3)  The above comment suggests there is no problem with the client-to-syncservers communication based on user counts from the server logs.

All indications is there is a sync telemetry problem on the server side.

**Comment by garvankeeley** [comment]
Unless we can think of anything else we need to consider about the May 26th date on the iOS side (maybe iOS upgrade??), lets continue this on the app services side: https://github.com/mozilla/application-services/issues/3270, as I think the telemetry server-side teams needs to investigate what changed on that date.

**Comment by athomasmoz** [comment]
Determine if this is a reporting issue versus a user-facing bug. 
Next steps:
* Error reporting from telemetry to help identify issues (Garvan)
* Kickoff discussion with Leif (Jeremy)

**Comment by garvankeeley** [comment]
Looks like sync telemetry is the cause https://bugzilla.mozilla.org/show_bug.cgi?id=1642386
They started rejecting messages from iOS due to message formatting requirements.
