### ISSUE TITLE
Telemetry for New Tab Button on Nav

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6886]
### Vision

As a user viewing a webpage, I want a button to start a brand new search in a new tab so that I can quick start another search while keeping my current tab open for later

### Acceptance Criteria

* Tracking in place to measure success of the new tab button in landscape mode

### Success Metrics

This button will help users start new searches with less steps, leading to a workflow that feels faster. We can determine that this was successful if users open tabs through this button instead of the current 2-step process (open tab tray then open new tab)
* Note: we should not send an event to Amplitude every time this button is clicked as it will drastically increase event counts. This could be telemetry-only

### Not included

* This is landscape mode only

**Comment by nbhasin2** [comment]
![image](https://user-images.githubusercontent.com/8919439/88089300-c1130b00-cb59-11ea-85c0-bae8b6e9a92e.png)

**Comment by nbhasin2** [comment]
Should add a count event for the ➕ button
@nbhasin2 to follow-up with Travis

**Comment by nbhasin2** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?
Number of times user taps on the newly added ➕ (add new tab) the top right of the view url bar.

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

This in turn should increase the searches performed by the user as tapping the button takes user to open new tab also gets the focus directly to address bar where they can enter any url or a search query 

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

This is a new button and we don't have any metrics for it to measure.

4) Can current instrumentation answer these questions?

Not really as this button is just added so current instrumentation cannot determine the number of times user taps on the button. 

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>Legacy telemetry / Glean: add new tab button tap</td>
    <td>Category 2</td>
    <td>https://github.com/mozilla-mobile/firefox-ios/issues/6886</td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
N/A in the old doc but once approved it will get updated as a part of Metrics.yaml

https://github.com/mozilla/firefox-ios/blob/main/Client/metrics.yaml

7) How long will this data be collected?  Choose one of the following:
For the lifetime of the Firefox iOS application or until we have the new start search button in the app.

8) What populations will you measure?

All users

9) If this data collection is default on, what is the opt-out mechanism for users?

In Firefox iOS there is a preference for telemetry labeled "Send Usage Data" that will be used as the opt-out mechanism.

10) Please provide a general description of how you will analyze this data.

We will look at how many times user taps on the add new tab button and compare search traffic with v27 to upcoming v28.

11) Where do you intend to share the results of your analysis?

Mozilla internal channels with our PM 

12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?

No 3rd party tool

User responsible for collection of this event - @nbhasin2

**Comment by nbhasin2** [comment]
Tagging @chutten for Data review. 

Instead of requesting it in a PR I am doing it here in an issue. This way we can update the files (code / documentation etc.) in PR and attach it to this issue as reference.

**Comment by dnarcese** [comment]
Data-review R+

# Data Review Form

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Yes, documentation will be in `docs/telemetry.md`

2) Is there a control mechanism that allows the user to turn the data collection on and off? 

Yes, firefox iOS provides data controls in the app settings

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

This should be re-reviewed w/ @athomasmoz every 6mo

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Type 2

5) Is the data collection request for default-on or default-off?

Default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

No

7) Is the data collection covered by the existing Firefox privacy notice? 

Yes

8) Does there need to be a check-in in the future to determine whether to renew the data? (Yes/No) (If yes, set a todo reminder or file a bug if appropriate)**

Should review all probes for necessity every 6mo w/ @athomasmoz 

9) Does the data collection use a third-party collection tool? 

No
