### ISSUE TITLE
FXIOS-564 ⁃ Investigation: Run multiple A/B tests at once using Leanplum

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#6887]
**Vision**

As a Product Manager, I want to run multiple A/B tests at once using Leanplum to avoid potential bottlenecks

**Acceptance Criteria**

* Determination of whether running multiple A/B tests at a time with Leanplum is possible
* Estimated effort
* Potential limitations

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-564)

**Comment by nbhasin2** [comment]
**Google Doc:** https://docs.google.com/document/d/1Vnl3dBbZSZG-F25DT8eXenrmqnwesOwKfgiguhxYJ00/edit#

# A. Goal

1. Run multiple A/B test simultaneously
2. Measure the impact of each A/B test using Glean Experimentation Framework 

In order to achieve our goals we'll leverage Glean and Leanplum framework. These two frameworks will allow us to run multiple A/B test simultaneously.

# B. Leanplum

We'll use this framework to setup our multiple A/B tests.  This contains the following information. 
LP A/B Test: 

- abTestId: String
- abTestName: String
- name: String, Float, Dictionary, Boolean

Below is how we get an LP variant for a specific A/B test

```swift
lp variant Optional([{
    abTestId = 1234567890; 
    abTestName = "AB Test V2 Demo";
    id = 09876543211234567890;
    name = Overrides;
}])
```

An A/B Test can have one or many LP variable(s)

LP variable(s) associated with a single A/B test can have one or more variants depending on its type

- Bool: 2 (true or false)
- String: Many
- Float: Many
- Dictionary: Many (Is mainly good for sending different structures)

Once the A/B test is setup we with proper LP variable(s) and their variants we then need to listen to it in our Firefox iOS App. In our app we need to do certain things: 

- Define proper LPVar which is equivalent to LP variable(s) in the LP Dashboard
- Once LP finishes staring up all LPVar will sync with proper values from LP Dashboard
- Finally, we use the LPVar in the iOS app to update our app with proper values

    There are three main conditions we should check when updating iOS App

    1. Leanplum is disabled: Here we should use default value(s) 
    2. Leanplum server too slow: Again we should use default value(s)
    3. Received A/B test variables from leanplum server: We use the received variables 

# C. Glean

Glean offers simple way in which we can track LP Experiment and the condition under which our current App is in using the experimentation API 

As long as experimentId is unique we can track as many experiments (A/B test) as we like. This will feed the data directly to Amplitude and also our Mozilla internal telemetry. 

- experimentId: Needs to be unique and is of type String
- branch: Used to track variant that our experiment (A/B test) is under and is of type String
- extra: String Dictionary type and is used for any additional telemetry that we want to add

Link: [https://mozilla.github.io/glean/book/user/experiments-api.html](https://mozilla.github.io/glean/book/user/experiments-api.html)

```swift
// Annotate Glean pings with experiments data.
Glean.shared.setExperimentActive(
  experimentId: "abTestId",
  branch: "Overrides",
  extra: ["": ""] 
)
// After the experiment terminates, the annotation
// can be removed.
Glean.shared.setExperimentInactive(experimentId: "abTestId")
```

# D. Whats next

1. Update our current LP Experimentation Model in iOS app to support all these conditions for more than one test. 
2. Add support for tracking the LP A/B test using Glean Experimentation Telemetry

**Comment by nbhasin2** [comment]
Moving it to Done as above document shows how we can run multiple A/B test simultaneously in iOS Firefox App
