### ISSUE TITLE
captcha during registration not usable

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#6911]
## Steps to reproduce
1. Open zoom.us in browser
2. register
3. enter brithdate
4. click confirm

### Expected behavior
You can choose captcha

### Actual behavior
Captcha out of screen, you need to turn phone to landscape

### Device & build information
* Device: Apple iPod Touch Gen. 7 - iOS 13.4, Wi-Fi

* Build version: 22.0 (17157)
### Notes
Attachments: 

<img width="480" alt="Bug4510350_0E3670D6-247D-43CE-BB8D-3D01E31C74E9" src="https://user-images.githubusercontent.com/66958331/87003501-6fb36500-c1c4-11ea-903a-db2f76043c99.png">

**Comment by muhasturk** [comment]
Same issue happens on other websites even on Safari.

This issue is **not relevant** with any Firefox iOS source code. 

You should contact web site developer to adopt appropriate way to show captcha.

**On Safari**
![IMG_3277](https://user-images.githubusercontent.com/4077401/86947346-583c9380-c154-11ea-9568-cca5613ea549.PNG)

**Comment by athomasmoz** [comment]
Unfortunately this is an issue on the website itself. Closing as won't fix on our side.
