### ISSUE TITLE
 can not use app in landscape mode (iphone 11 pro iOS 13.5)

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#6920]
## Steps to reproduce
1. Open whattsapp.com
2. Turn phone to landscape3
3. Corona Pop up opens
### Expected behavior
you can close it via X
### Actual behavior
X is in iphone 11 pro area where you can not close it
### Device & build information
* Device: Apple iPhone 11 Pro - iOS 13.5
* Build version: 22.0 (15157)
### Notes
Attachments: 
![Bug4510485_Bildschirmfoto_2020-06-18_um_09 26 50](https://user-images.githubusercontent.com/66958331/86727574-377d1c80-c034-11ea-8a03-7547c3f00c54.png)

![Bug4510485_IMG_0184](https://user-images.githubusercontent.com/66958331/86727820-74491380-c034-11ea-9d45-71d6aef6b55e.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2486)

**Comment by athomasmoz** [comment]
Investigate if there's something we can do to inform websites that there's a notch

**Comment by nbhasin2** [comment]
Checked on latest version 28 on landscape and couldn't reproduce
Also, this seems like a whatsapp web issue and not particularly related to Firefox. 

![image](https://user-images.githubusercontent.com/8919439/90284640-4380a900-de40-11ea-8efb-1d12720ab9ea.png)

@SimonBasca could you also try and see if this happens.

**Comment by SimonBasca** [comment]
This issue is still reproducible on v34.0 (4795). The problem is that in Firefox we don't have a large safe are for the notch in landscape and because of this the banner cannot be dismissed. 

**Safari**
![Skype_Picture_2021_05_13T15_41_37_757Z](https://user-images.githubusercontent.com/32130829/118150465-40d8d180-b41b-11eb-8783-ec57e3a79b5d.jpeg)

**Firefox**
![Skype_Picture_2021_05_13T15_41_33_023Z](https://user-images.githubusercontent.com/32130829/118150482-46ceb280-b41b-11eb-8154-f57b0fe7f129.jpeg)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
