### ISSUE TITLE
FXIOS-601 ⁃ Include sync identifier in glean deletion-request ping

### ISSUE THREAD

**Issue by 6a68** [mozilla-mobile/firefox-ios#6933]
### Why/User Benefit/User Problem

When users are signed in to the browser, then opt out of data collection, the sync identifier should be included in the deletion request ping, so that data tied to the sync identifier can be deleted.

For reference, see the corresponding bugs to include the sync ID with deletion requests for [desktop](https://bugzilla.mozilla.org/show_bug.cgi?id=1604844) and for [android-components](https://github.com/mozilla-mobile/android-components/issues/7646).

### Acceptance Criteria (how do I know when I’m done?)

If the user was logged in to the browser, then opts out of data collection, the glean deletion-request ping should include the sync ID in the set of secondary IDs.

### Not included

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-601)

**Comment by jevans-mozilla** [comment]
Need sync identifier.  Will follow up to get details

**Comment by mdboom** [comment]
Cc: @travis79

**Comment by dnarcese** [comment]
Closed in https://github.com/mozilla-mobile/firefox-ios/pull/7629

**Comment by rfk** [comment]
Howdy folks, I cam across a link to this issue via the #glean slack channel. Unfortunately I don't think #7629 is the correct fix here, but the reasons why are pretty poorly documented so I'll try to add a bunch of context here.

The reason for including this identifier in the deletion ping is so that, if the user opts out of telemetry on the client, we can find and delete any [sync telemetry pings](https://github.com/mozilla-mobile/firefox-ios/blob/66cc02a96a944baa0755e8974b2aaed468cb366a/Sync/SyncTelemetryUtils.swift#L243) submitted by that client. For that to work we need to make sure the identifier being included in the deletion ping is the same as the one used by the sync ping.

For tedious historical reasons, there are several different notions of "device id" in the FxA client ecosystem, it looks like #7629 is not using the correct one.

The change in #7629 is using the `fxaDeviceId` field, which is the identifier assigned to this client by the FxA server. The sync ping does not use this value; instead it uses what we call the [`hashedDeviceID`](https://github.com/mozilla-mobile/firefox-ios/blob/66cc02a96a944baa0755e8974b2aaed468cb366a/Sync/SyncTelemetryUtils.swift#L258), which combines a client-managed guid and a server-provided userid in an attempt to make it more difficult to tie this identifier back to a specific user account.

I think you will need to do the same hashing logic here when setting the device identifier in the deletion-request ping, otherwise we won't be able to find the target sync pings in order to delete them.

**Comment by SimonBasca** [comment]
Verified fix on 30.0 (3279)
