### ISSUE TITLE
FXIOS-614 ⁃ Create breached login detail view

### ISSUE THREAD

**Issue by vphong** [mozilla-mobile/firefox-ios#6959]
- at the top of the LoginDetailViewController before content
- background colored red; rounded corners
- title must include:
  - breach icon
  - "Website Breach"
  - "Learn more": link to monitor.firefox.com/\<specific breach\>
- text must include:
  - "This breach occurred on \<date\>."
  - "Passwords were leaked or stolen since you last changed your password. To protect this account, log in to the site and change your password."
  - "`<a>`Go to \<website\>.`</a>`"

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-614)

**Comment by betsymi** [comment]
The string I have from desktop (see [Transvision](https://transvision.mozfr.org/?recherche=Passwords+were+leaked+or+stolen+from+this+website+since+you+last+updated+your+login+details.+Change+your+password+to+protect+your+account.&repo=gecko_strings&sourcelocale=en-US&locale=en-US&search_type=strings)) is: Passwords were leaked or stolen from this website since you last updated your login details. Change your password to protect your account.

**Comment by kaylagalway** [comment]
This text is based on the text from these desktop designs for breaches for consistency: https://mozilla.invisionapp.com/share/9DVFB5KQVSE#/screens

**Comment by SimonBasca** [comment]
Note from QA : Please consider also providing a login that is breached for testing purposes.

**Comment by vphong** [comment]
I've appended mock breached logins to the logins list, so it's testable without even logging into FxA. Let me know if there are any other cases you would like @SimonBasca 

Breaches:
https://github.com/mozilla-mobile/firefox-ios/blob/581bb46234cf31c4f32290ada305e58cbbe6c4dd/Client/Frontend/Login%20Management/BreachAlertsManager.swift#L56-L70

Logins:
https://github.com/mozilla-mobile/firefox-ios/blob/581bb46234cf31c4f32290ada305e58cbbe6c4dd/Client/Frontend/Login%20Management/LoginListViewModel.swift#L65-L66
