### ISSUE TITLE
Push Notifications aren't working - Leanplum 

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#7026]

**Comment by cbonacuse** [comment]
While performing QA on a campaign set to deploy on 7/24, I noted that my device (Leanplum ID: 06CE6EF2-7C11-46CB-A638-2DFF5B6DC80A) is showing "iOS push types: disabled". I had all notifications for Firefox turned on for my device (iPhone 11 Pro OS 13.5.1) and had never turned them off (and don't see a place to do so in the app itself). Because of this, I am not able to receive push notifications to my device.

Also to note, my location is off (Leanplum is showing me ~2 hours north of where I am) and I had not been to that location at all in recent history. The last time I checked, it had me correctly placed in Columbus, OH.

**Comment by athomasmoz** [comment]
This has been resolved by re-installing app. It was due to an id being previously disabled.
