### ISSUE TITLE
Add option to remove top sites

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7027]
### Why/User Benefit/User Problem

As a user, I want the option to remove top sites from the homepage to maintain privacy from others using my phone and seeing which sites I most often visit

### Acceptance Criteria (how do I know when I’m done?)

* There is a way to turn off top sites

### Notes

* There is already a setting to change the rows for top sites to 1-4. Maybe the simplest solution is to add an option in that page to fully remove?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2506)

**Comment by brampitoyo** [comment]
If I recall correctly, @topotropic has worked on top sites on Fenix, so I’m paging her for advice.

I know that Fenix has a context menu for each top sites item, which allows removal and opening in private tabs. So people is able to remove sites from the list, but only individually.

We also know, though, that Firefox for iOS top sites contains a combination of manually pinned and frequently visited sites. On Fenix, it consists solely of manually pinned sites. A different approach may be needed on iOS, or we can make it consistent with Fenix.

However, if the intent for this issue is the ability to customise the New Tab Page in a more extensive way (ie. I want to be able to add and remove sections as a whole), then perhaps @apbitner is the right person to ask for comment.

**Comment by athomasmoz** [comment]
Thanks @brampitoyo ! This came from our reviews and I think this one is more specific to the fact that we let you set the number of rows of top sites, but you can't choose 0. 
![image](https://user-images.githubusercontent.com/43346208/88941938-74f15600-d23e-11ea-8182-e234343e3d59.png)
![image](https://user-images.githubusercontent.com/43346208/88941955-791d7380-d23e-11ea-95d7-3de7b02150cd.png)

**Comment by brampitoyo** [comment]
Thanks, @athomasmoz. Firefox Home is @apbitner’s territory, so I will assign him for comments.

But since Firefox Home is managed from within Settings, I’d like to propose a solution to think about – which is by no means final.

A short-term solution – which could also be short-sighted – is to add a new row value called “Off”. “Off” means “don’t show Top Sites”.

-----

But if we think in a longer-term way, we could potentially think a bit more about how this Settings sub-page is organised, and have the opportunity to make it both more orderly and logical.

I saw a couple of issues with “Home” Settings sub-section:

- The difference between Settings → New Tab and Settings → Home is unclear. They contain the same heading called “Show”, but while it’s totally clear how to open new tabs, invoking home is a little less clear (I know that it involves going inside the main menu – do users know that?)
- “Trending on Pocket” is a line item under a heading called “Customize Top Sites”, even though Pocket is not at all a member of “Top Sites”. Whatever we call this toggle, it should probably follow the same nomenclature as the “Top Sites” toggle.
- “Your Library” is not customisable. If we want the ability to customise Firefox Home, we should probably think about the ability to at least turn this section ON and OFF.

-----

My strawman proposal seeks to clarify the separation between “the page that opens when you select x”, and “the content of this page”.

- “The page that opens when you select x” is managed under “Home and New Tabs”
- “The content of this page” is managed under “Firefox Home content”

<img width="360" src="https://user-images.githubusercontent.com/51007/89145398-bff3cc00-d5a4-11ea-907b-1abbed78347d.png">

-----

Under “Home and New Tabs”, we could have two separate headings: one for “Home”, and one for “New Tabs”.

Here, I thought it’s important to define what “Home” is and help users know how to access it. By doing this, we may reduce confusion between “Home” (the page itself) and “Firefox Home” (the content that opens on this page).

<img width="360" src="https://user-images.githubusercontent.com/51007/89145027-91c1bc80-d5a3-11ea-95ab-bff959d47fa7.png">

-----

The second sub-page is called “Firefox Home Content”. It deals only with the content of Firefox Home.

By making this sub-page exclusively dedicated to content management, we can turn each section into a heading. The toggle is much clearer this way.

In this example, you can turn “Top Sites”, “Your Library” and “Pocket” ON and OFF individually.  And when a section is turned ON, number of rows and perhaps other things may be modified. For example, when you turn ON “Your Library”, we can say “Do you want to show the Bookmarks icon, or not?”

<img width="360" src="https://user-images.githubusercontent.com/51007/89145144-ee24dc00-d5a3-11ea-8c85-ef2aef9a0538.png">

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Daniela Arcese Just confirming, is there an eng ticket for this already?

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Ashley Thomas yes, I just linked it https://mozilla-hub.atlassian.net/browse/FXIOS-3465 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3465|smart-link )

**Comment by lmarceau** [comment]
Closing since this was done, top sites can be toggle off and removed
