### ISSUE TITLE
FXIOS-688 ⁃ Search Focused - Quick Actions (Small)

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7064]
**Vision**

As an iOS 14 user, I want a shortcut from my homescreen to start searches and open URLs in Firefox

**Acceptance Criteria**

* Small size Firefox search quick actions widget offered to users
* Small widget allows you to choose which action to display
* Design & functionality matches [spec](https://share.goabstract.com/0557fb4f-7c11-40cf-a2af-49fd7be5ecc2)

**Not Included**

This ticket does not include the medium sized widget. It is covered in #7073

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-688)

**Comment by athomasmoz** [comment]
A few questions to consider:
* Can you add configuration for just a specific size of widget?
* Can you change the app name based on the configuration?

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

So yeah it sounds like the small widget can't have a different configuration than the medium or large size since you just define IntentConfiguration or StaticConfiguration for all sizes.

That being said, what we could do is:
 1 Small widget that IS configurable
 1 different Medium widget that is NOT configurable

The medium widget would just need a slightly different name / copy, but other than that it could look basically identical to the small ones in description!

More info ( https://developer.apple.com/forums/thread/653863 )

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Let's build the small widget in a way where the text, image, and deeplink are generic. That way we can swap them out if we want to in the future.

**Comment by SimonBasca** [comment]
Verified fix on beta 29.0 (2609)
