### ISSUE TITLE
FXIOS-694 ⁃ Spike: iOS 14 Widgets

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7070]
**Acceptance Criteria**

* Validated that the proposed design for the search widget is feasible
* Notes on anything particularly difficult called out

**Open Questions**

* Can you add configuration for just a specific size of widget?
* Can you change the app name based on the configuration?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-694)

**Comment by sblatz** [comment]
I've confirmed that it's not possible to change the text under the widget (this is a change from how "Today Widgets" worked) [more info](https://developer.apple.com/forums/thread/654054).

Still looking into whether or not we can do configuration just for a specific size, but my strong leaning right now is "no"

**Comment by sblatz** [comment]
So yeah it sounds like the small widget can't have a different configuration than the medium or large size since you just define `IntentConfiguration` or `StaticConfiguration` for all sizes.

That being said, what we could do is:
1 Small widget that IS configurable
1 different Medium widget that is NOT configurable

The medium widget would just need a slightly different name / copy, but other than that it could look basically identical to the small ones in description!

[More info](https://developer.apple.com/forums/thread/653863)
