### ISSUE TITLE
FXIOS-698 ⁃ Menu item in settings to set Firefox as default browser

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#7090]
**Vision**

As a Firefox for iOS user, I want to easily find the setting to make Firefox my default browser, so that I can use a single browser on the device for a consistent experience whether opening from the homescreen or through clicking on a link in another app

**Acceptance Criteria**

* A menu item added to Firefox app Settings that deep links into the Firefox OS level settings, where users can set Firefox as their default. This menu item appears underneath “Home”.
  * Menu item string: `Set as Default Browser`
* Setting is only visible to users on iOS 14+
* Design details
  * [Abstract](https://share.goabstract.com/c9be1dfc-5d1f-4329-ac5f-791a5ddfa150)

![](https://user-images.githubusercontent.com/51007/89357111-ae7d0200-d713-11ea-9e79-f622b0f9028b.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-698)

**Comment by brampitoyo** [comment]
Assigning @betsymi to acknowledge and double-check strings.

**Comment by nbhasin2** [comment]
@athomasmoz I have added this feature behind feature flag until we have confirmation on how iOS14 actually handles setting default browser. 

Feature is available when user has iOS14 on their device and are running Firefox Dev or Beta builds. 

Let me know if this is good otherwise I can remove feature flag?

**Comment by athomasmoz** [comment]
Thanks @nbhasin2 ! There's a ticket in the backlog #7133 to figure out that question. The goal is to ensure:
* Only eligible users (those on iOS 14+) would see it
* The functionality will be available as soon as iOS 14 comes out. In other words, we don't have to do a new release to get the menu item to users

**Comment by nbhasin2** [comment]
Thanks @athomasmoz, will follow-up in channel now for further discussion. Its easier to show this when iOS14 comes out. I am just not sure where iOS 14 will have this option.

**Comment by nbhasin2** [comment]
# Request for data collection review form 
1. What questions will you answer with this data?
How many users tap / engage with setting Firefox as their default browser using settings menu option?
How often is Set As Default Browser menu option is tapped?

2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:
As we get to know number of users who make iOS Firefox as their default browser it will help us in understanding better user retention and Firefox iOS usage.

3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
No alternative method to get this data.

4. Can current instrumentation answer these questions?
No.

5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki.

Measurement Description | Data Collection Category | Tracking Bug # |
| --- | ----- | ----- |
When the user taps settings menu option to set browser as default browser | 2 | https://github.com/mozilla-mobile/firefox-ios/issues/7151
		
6. How long will this data be collected? Choose one of the following:
6 months 

7. What populations will you measure?
All countries, locales, and channels that have data collection on.

8. If this data collection is default on, what is the opt-out mechanism for users?
Toggle switch for 'Send Usage Data' in the app settings.

9. Please provide a general description of how you will analyze this data.
By monitoring the count of how often users are performing these actions.

10. Where do you intend to share the results of your analysis?
With the mobile team.

11. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so:
No.

cc @dnarcese for data review

**Comment by dnarcese** [comment]
data review +

# Data Review Form

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Yes, the tab usage is documented in `docs/metrics.md`

2) Is there a control mechanism that allows the user to turn the data collection on and off? 

Yes, firefox iOS provides data controls in the app settings

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

This should be re-reviewed w/ @athomasmoz every 6mo

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Type 2

5) Is the data collection request for default-on or default-off?

Default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

No.

7) Is the data collection covered by the existing Firefox privacy notice? 

Yes

8) Does there need to be a check-in in the future to determine whether to renew the data? (Yes/No) (If yes, set a todo reminder or file a bug if appropriate)**

Should review all probes for necessity every 6mo w/ @athomasmoz 

9) Does the data collection use a third-party collection tool? 

No

**Comment by SimonBasca** [comment]
Verified fixed on iPhone XS (14.0b8), iPad Pro 11 inch (14.0b8) and iPhone Xr (13.6) on main-dev ec13f42830.
