### ISSUE TITLE
FXIOS-776 ⁃ Logins filtering gets dimissed when slightly pulling the logins page down

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#7131]
latest master/current release
iPhone 11 Pro (13.3)

1. Open the Logins view via Menu => Logins & Passwords.
2. Type something in the Filter field to filter the logins.
3. Slightly pull down the logins page.

Expected: The filtering and the virtual keyboard are not dismissed.

Actual: The filtering and the virtual keyboard are both dismissed. 

Note: This issue doesn't happen if entering Logins & Passwords via the Settings page.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2527)

**Comment by deepal15** [comment]
@csuciu If Navigate to Login & Password via Settings, it does not dismiss the virtual keyboard and filtering if slightly pull down the page.
If navigate to Login & Password via Menu, if slightly pull down it should not dismiss the screen. Is it the only expectation here?

**Comment by deepal15** [comment]
@csuciu  @athomasmoz

**Comment by athomasmoz** [comment]
@brampitoyo What are your thoughts on what the correct behaviour should be here? Basically, we have 2 ways to access the logins & passwords page. One opens the page as a slide-up which you can slide-down to dismiss and the other navigates to the page where you need to click back (to settings) to dismiss. Is it okay that they're different?

**Comment by brampitoyo** [comment]
@athomasmoz The keyboard shouldn’t be dismissed in both cases.

For Logins that’s accessible from inside the Main App Menu, you can only swipe down to dismiss (alternatively, tap “Done”)

For Logins that’s accessible from inside Settings --> Logins & Password, there should be two ways to dismiss it:

1. Swipe right or tap “Back”: go back to the root Settings page
2. Swipe down: close the entire Settings, and return to the current webpage

Currently, method 2 is not available because Settings is a separate page, not a sheet that slides up.

We want to change this. Settings should be a sheet, just like Your Library and Chrono Tab Tray are sheets.

**Comment by deepal15** [comment]
@brampitoyo, Just for the confirmation,
In the case of Settings --> Logins & Password, 
1. For the Dismiss of the "Login & Password" screen should Have "Done" button instead of the "Back" button
2. The present and dismiss behaviour of "Login & Password" screen should be same as when accessible from inside the Main App Menu. (like sheet)

**Comment by deepal15** [comment]
@brampitoyo 
If Main Settings would be "Sheet", then navigation through Settings would be presenting "Logins & Password" screen like sheet.
There would be "Back" button but also swipe down to dismiss would be default behaviour.
Should I go ahead and raise the PR for this?

**Comment by prsmahajan** [comment]
Hi, I would like to work on this issue, can anyone suggest me ways to get started?

**Comment by SimonBasca** [comment]
This issue is no longer reproducible on v34.2 (5301).
