### ISSUE TITLE
FXIOS-800 ⁃ Automation & Unit tests not working on Xcode 12

### ISSUE THREAD

**Issue by jevans-mozilla** [mozilla-mobile/firefox-ios#7210]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2534)

**Comment by nbhasin2** [comment]
We rely on KIF and EarlGrey and I see KIF has atleast tried to resolve issue. 

Next steps are i'll try their main branch and see if I can resolve resolve certain issue otherwise will just look into getting rid of it.

https://github.com/kif-framework/KIF/issues/1169

**Comment by nbhasin2** [comment]
Some more investigation revealed its not feasible to just fix it without making changes to following files. 
We'll need remove EarlGrey dependency as that is causing too much issue in building. KIF I was still able to build. Doing all this basically changes complexity of this task to a 5.

Steps: 
- Remove EarlGrey completely 
- Refactor following files and move all EarlGrey related actions to basic XCUitest where applicable. 

```
/NoImageModeTests.swift
/TrackingProtectionTests.swift
/EarlGrey.swift
/AuthenticationTests.swift
/BookmarksPanelTests.swift
/BrowserTests.swift
/ClearPrivateDataTests.swift
/DomainAutocompleteTests.swift
/Global.swift
/HistoryTests.swift
/LoginInputTests.swift
/LoginManagerTests.swift
/NavigationDelegateTests.swift
/ReadingListTest.swift
/SecurityTests.swift
/SessionRestoreTests.swift
/ToolbarTests.swift
/ReopenLastTabTests.swift
```
// This code
EarlGrey.selectElement(with: grey_accessibilityID("TabToolbar.menuButton")).perform(grey_tap())
// Becomes something like below 
app.button["TabToolbar.menuButton"].tap()
```

**Comment by isabelrios** [comment]
Adding my two cents here (sorry a bit late after PTO time)

The tests that use KIF or Early Grey are different than the XCUITests. Those tests are UI tests, more grey box tests while the XCUITest are black box tests. This means that those are something between unit and XCUI tests. There are some tests like loging tests in which we are injecting a lot of logins and then test the user interface as a user would do, scrolling up and down, removing a few logins and so, and the test takes about 1-2 minutes to run. That test for example could not be changed to XCUITests. 

There are some actions that does not work well with Earl Grey or KIF, that's why both frameworks are used, to use on or the other to get all the actions/interactions working. But as a first approach we could try to move everything to use KIF instead of Earl Grey.

In the past I worked to migrate all possible UI Tests to XCUITests but I can take a look and see if we can move even more tests to that framework.

So, I would suggest:
1-Change Early Grey calls to KIF
2-Try to migrate as much tests as possible to XCUITests (the disvantage here is that tests will take longer to run)

Hope that helps...

**Comment by isabelrios** [comment]
This should be closed once [PR](https://github.com/mozilla-mobile/firefox-ios/pull/7281) landed. But we can keep it open until we moved to Xcode 12/iOS 14 and verify that this solution still works (it has been tested under that environment, but just in case)
