### ISSUE TITLE
FXIOS-941 ⁃ [UX] Append - Continue typing off search suggestion

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7365]
**Vision**

As a user performing a search, I want to send the search suggestion to the search field but allow you to keep typing additional text before performing the search, so I can add something more specific to the suggestion

**Acceptance Criteria**

* Users can fill in the search bar with a suggestion and then add to it before the search is performed
* Current workflow of clicking a search suggestion to perform a search with that term remains the same
* Tracking in place to measure experiment results
* This will be set up as an experiment, so this needs to be behind a flag and the current version needs to also be supported
* [experiment plan with mocks](https://docs.google.com/document/d/16cXwOwi4H_6viiQJYK8X512Lj8CAj6bE8rI3MMMAd3c/edit#)

**Notes**

* This can be achieved right now through a long-press. This ticket is about finding a way that's more discoverable
* This is done on Safari and Fenix through an arrow

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2558)

**Comment by brampitoyo** [comment]
### Mockup

<img width="375" src="https://user-images.githubusercontent.com/51007/94761114-bea61a80-0400-11eb-9a96-f2b2163f85a5.png">

### Behaviour

- Adding an “Append” icon would require enough space around the search query – enough tappable space for people to accurately target the icon.
    - Therefore, we need to redesign the keyword suggestion area from an “inline blue pill” style, to one where each keyword suggestion takes up one line item. The “Append” icon could then appear to the right of each item.
- We’ll still show 4 different keyword suggestions, just as before:
    - The first item mirrors any character you’ve typed. It’s useful when address bar autocomplete takes over, and allow you to proceed with a search verbatim without needing to tap on the “Delete” key on the keyboard.
    - The 2nd, 3rd and 4th items are suggestions we get from the selected search provider
- In this mockup, a magnifying glass icon is shown next to each keyword suggestion. This is because the search provider icon is already shown in the address bar.
    - If we can’t show the search provider icon in the address bar, we can show it next to each suggestion – but I’d consider this a temporary solution.

### Assets

- [append.pdf](https://drive.google.com/file/d/1li7XWXkrQI-DvBbNIMfyKbKqPMTZcvG_/view)
- [append.svg](https://drive.google.com/file/d/1lofVEuabZ3J5jgRytRnBmY2NuBkYprxz/view)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Marking this as UX ticket and closing now that UX is complete. Engineering ticket created here https://jira.mozilla.com/browse/FXIOS-1493
