### ISSUE TITLE
Widgets' text truncates or doesn't wrap for many locales

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/firefox-ios#7442]
## Steps to reproduce
* Set your OS language to "French" (note that this happens in many other locales as well)
* Install Firefox widgets - both the "quick actions" and "quick view" ones

### Expected behavior
* Texts either properly wraps around, or doesn't truncate. 
Note: English also truncates for me, so I guess it's more the wrapping issue we can fix
* More specifically about wrapping: 
** Quick Actions widget: see how the "r" from "rechercher" ends up in the other line
** Quick View widget: see how the "er" from "rechercher" ends up in the other line too

### Actual behavior
* It doesn't wrap in some cases, and truncates in many cases

Note: I'd like to know if this happens just because I'm on a very small screen, aka an iPod. I don't have an iPhone and there are currently no screenshots to test l10n against for widgets (should arrive early next week), so I can't test on an actual phone.

### Device & build information
* Device: iPod Touch - seventh generation, iOS 14.0.1
* Build version: Firefox Beta (Daylight 29.0, 2740)
### Notes
Screenshots: 
![IMG-0003](https://user-images.githubusercontent.com/399020/94972059-3a659d00-04bd-11eb-9dcb-d5f07fc5d1b4.PNG)
![IMG-0002](https://user-images.githubusercontent.com/399020/94972064-3df92400-04bd-11eb-9346-57cbe6e16e72.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2568)

**Comment by brampitoyo** [comment]
@nbhasin2 @dnarcese @electricRGB First of all, I think the Small size widget text should be able to flow to the 3rd, 4th, etc. lines – as much as the text would fit. Instead of just keeping to 2 lines.

-----

Secondly, I wonder whether we can apply some sort of logic where, if the text truncates, we automatically downsize to the next smallest size available in system?

For example, the widget text isset to Body (17pt).

If the text truncates, try setting it to Callout (16pt) → Subhead (15pt) → Footnote (13pt) → Caption 1 (12pt) → Caption 2 (11pt).

-----

The alternative approach, which is less ideal, is to simply pick a smaller text size and go with it. I would recommend Subhead (15pt), which will give us more room, but isn’t the smallest size available to us.

**Comment by data-sync-user** [comment]
➤ Tiffanie Shakespeare commented:

Removing needs ux - bram already replied
