### ISSUE TITLE
FXIOS-1063 ⁃ "Add Tab" button displayed instead of refresh/reload button on a tab that has a website loaded

### ISSUE THREAD

**Issue by ksze** [mozilla-mobile/firefox-ios#7504]
## Steps to reproduce

1. Add a new tab;
2. Visit any website in the new tab;

### Expected behavior
See the refresh/reload button at the bottom of the screen.

### Actual behavior
See the "add tab" ("+") button at the bottom of the screen.

### Device & build information
* Device: iPhone XS Max
* Build version: Firefox Daylight 29.0 (2860)

### Notes
1. If I swipe to another app and come back, I often get back the refresh/reload button. I could then actually see the animation of the "add tab" button fading out and turning into the refresh button.
2. If I click the "tabs" button (the one that shows your tab count), and then pick any tab, I get the "add tab" button again instead of the refresh/reload button.

Attachment: 
![280BDFDA-9B77-4529-9B14-5BFF46A5463E](https://user-images.githubusercontent.com/381556/96226941-edf28500-0fc5-11eb-9a4d-53e1cc32a410.png)

Screen recording of the bug happening: https://imgur.com/a/0dSG0Tz

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1063)

**Comment by seaneshbaugh** [comment]
This appears to be intentional: #6847.

However, I gotta be honest, I strongly dislike this change. I actually exclaimed, out loud, "Oh no! They broke Firefox!" when I noticed the UI change this morning after accidentally opening a new tab. This change heavily disrupts how I browse the web on my phone. I am far more likely to refresh one of the 5 or 6 tabs I already have open than I am to need to open a new one (probably an 80 to 1 ratio if I had to guess). I'm not sure what the Firefox iOS policy is on UI feature toggles but this is something I would love to be able to revert with a setting somewhere. Refreshing a page is, to me, as crucial as forward and backward navigation.
