### ISSUE TITLE
Firefox doesn't remember/restore scroll position on page

### ISSUE THREAD

**Issue by tillrathmann** [mozilla-mobile/firefox-ios#7510]
## Steps to reproduce
1. Open a large website and scroll down to the middle or so.
1. Close Firefox (kill the app in the iOS task manager to force a restart).
1. Open the app again.

### Expected behavior
The scroll position of the pages is set to the last view position.

### Actual behavior
The scroll position of the pages is set to top. This is annoying when you read a long page or a page with lots of comments and want to continue there later.

### Device & build information
* Device: iPhone SE 1 (iOS 14.0.1)
* Build version: Firefox Daylight 29.0 (2860)
    1. Notes
Safari remembers the page scroll position.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2579)

**Comment by beefstew** [comment]
Scroll position is still not maintained while browsing back in history as of Firefox Daylight 101.1 (10346). I've been trying out Safari (i.e. will stop using Firefox for iOS) because of this missing feature. Navigating search results is exceedingly painful when you have to scroll down to where you were each after each step of forward navigate, go back to results list.

**Comment by markwendy** [comment]
Same here, fire-fox is losing users

**Comment by data-sync-user** [comment]
➤ Orla Mitchell commented:

For QA this will be fixed in v114 with the tab refactor feature flag enabled. I will follow up in this ticket with how to test that feature flag in general https://mozilla-hub.atlassian.net/browse/FXIOS-6395 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6395|smart-link )

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Blocked by https://mozilla-hub.atlassian.net/browse/FXIOS-6395 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6395|smart-link )

**Comment by data-sync-user** [comment]
➤ Andrei Bodea commented:

Verified as fixed on v9000 (31207) with iPhone 13 Pro (15.7.1).

But as mentioned in https://mozilla-hub.atlassian.net/browse/FXIOS-6395 ( https://mozilla-hub.atlassian.net/browse/FXIOS-6395|smart-link ) we still need to investigate. 
I was able to scroll down → force close → relaunch and the position was kept.

As mentioned in the previous ticket I will let this with the status QA Needed until we can get it into an official v114 build.
