### ISSUE TITLE
Blank tab is displayed after Firefox opens link in external app

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#7533]
## Steps to reproduce
1. Open the firefox (v29.0(2860) )
2. Go to netflix.com
3. Scroll down and tap Contact us
4 . Tap Download on the App store button
5. Tap cancel
### Expected behavior
The window will close and you can continue using the site
### Actual behavior
The window closed, but the site was not displayed, the Url bar was empty
### Device & build information
* Device:  Apple iPhone 6S - iOS 13.3.1
iphone 7 plus (ios 13.7)
* Build version: Firefox 29.0(2860)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2586)

**Comment by SimonBasca** [comment]
This issue is happening after Firefox opens a link in external app. 

- On iPhone tapping on "Contact us" will display a blank tab and a prompt to open link in external app. 
- On iPad  tapping on "Contact us" will display a prompt to open the app in external link and the page in the screenshot. 

![Skype_Picture_2020_11_03T14_42_55_274Z](https://user-images.githubusercontent.com/32130829/97999803-75c4f580-1df4-11eb-9eeb-12cddd8af715.jpeg)

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
