### ISSUE TITLE
Breach login icon not displyed for breached login

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7552]
## Steps to reproduce
1. Go to https://monitor.firefox.com/
2. Type "simon.basca@gmail.com" -> Email appears as breached
3. Go to login screen on iOS and check the login
### Expected behavior
- Login should appear breached
### Actual behavior
- Breach login icon not displyed for breached login
### Device & build information
* Device: iPhone Xr
* Build version: 29.0 (2860)
### Notes
Attachments: 
![Picture_2020_10_26T17_20_23_177Z](https://user-images.githubusercontent.com/32130829/97205616-5c062b80-17c0-11eb-8da7-4d8b3ce205ac.jpeg)
![Picture_2020_10_26T17_20_27_597Z](https://user-images.githubusercontent.com/32130829/97205624-5e688580-17c0-11eb-854b-5d9154170855.jpeg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2594)

**Comment by athomasmoz** [comment]
May be fixed on 29.1

**Comment by SimonBasca** [comment]
Tested on v29.1 (3022). No breach login icon is displayed for simon.basca@gmail.com

**Comment by SimonBasca** [comment]
Also note that when I tap to reset password on myfitnesspal.com, no email is sent. Might be an issue with monitor.firefox.com reporting a false breach.

**Comment by isabelrios** [comment]
My two cents here... I would like to add that we had to disable the [unit test](https://github.com/mozilla-mobile/firefox-ios/blob/7cea3a9eae08f9176d0bd07905ccfb7e0067bef0/ClientTests/BreachAlertsTests.swift#L67)that was implemented for this feature since it started to fail, see [issue](https://github.com/mozilla-mobile/firefox-ios/issues/7411). When investigating this by garvan and myself looked like the breached data was not correctly retrieved/fetched from the BreachAlertsClient end point

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
