### ISSUE TITLE
Zoom smaller than 100%

### ISSUE THREAD

**Issue by eroldru** [mozilla-mobile/firefox-ios#7596]
I find myself switching to Safari more often than not, because the text size on Firefox is just too big. I use an iPhone 7 Plus and use Safari normally at 50-75% text size. 

Is this feature even considered in the timeline? This is the only thing right now stopping the complete switch.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2618)

**Comment by cantonalex** [comment]
Second this

**Comment by eroldru** [comment]
I have tested lots of other browsers and have not found any way to select a smaller than 100% zoom level. It is possible that it’s an iOS limitation. That’d be a shame tho. It’s the only thing stopping me from using FF as my default browser on my iPhone.

**Comment by SimonBasca** [comment]
@eroldru could you please provide a comparison example? On what page is the text bigger in Firefox than Safari?

**Comment by eroldru** [comment]
![6F1DF7CD-5944-4633-8B43-9E212EE0A7A8](https://user-images.githubusercontent.com/16373057/102061424-bf413100-3df3-11eb-9e7f-1937aa26395f.png)
![BAC7BEC9-E95D-4C71-A69C-11957910854F](https://user-images.githubusercontent.com/16373057/102061435-c23c2180-3df3-11eb-8755-9f1d8695bb83.png)

Please see the attached screenshots for reference.

**Comment by k-kruglov** [comment]
Yes, please, add this feature to Firefox. Some pages are unusable without it and desktop mode doesn't help.

**Comment by cantonalex** [comment]
Any update on this? I would switch from safari on iOS if this feature was present.

**Comment by dnarcese** [comment]
@brampitoyo do you have any mocks for adding this feature? We have a contributor patch for it and would appreciate feedback.

**Comment by brampitoyo** [comment]
@dnarcese Sorry, I don’t have any mockup for this feature off the top of my head.

Safari’s zoom feature is a good place to start, because we probably want our implementation to look and work like theirs:
<img width="320" src="https://user-images.githubusercontent.com/51007/118058732-fa678080-b3e2-11eb-90c0-762bdd50a600.jpeg">

There is precedent for this design in our own Reader Mode Type Controls:
<img width="320" src="https://user-images.githubusercontent.com/51007/118058751-06534280-b3e3-11eb-835f-1d469d0ef978.jpeg">

I think it would be worth investigating, if we implement a menu item with 3 segments, like so:
| – | 100% | + |
| --- | --- | --- | 

Would it be possible to have horizontal segments within the iOS native menu, or would we need to build our own custom one? I’m leaning towards using the iOS native menu, with no custom element if possible. So we may need to suit our Zoom UI design, so it works within the native menu’s capabilities.

**Comment by q2r5** [comment]
Unfortunately I don’t believe there’s a native horizontal menu item currently. This is what I currently have in place for my implementation.
![6398F3A6-0EC1-47CF-ACCD-EDAEABC421CC](https://user-images.githubusercontent.com/650804/118066263-dc4e4180-b34a-11eb-8c4b-dc758e027efa.jpeg)

**Comment by cantonalex** [comment]
Where are we at with this?

**Comment by k-kruglov** [comment]
Also waiting very much for this to happen someday.

**Comment by brampitoyo** [comment]
@dnarcese Is it confirmed that we can’t have a native horizontal menu a la Safari for this feature? Because if we can, then our solution could look similar, only we’d swap their small `ᴀ` and large `A` symbols with `-` and `+`, respectively. And no need for the word `Zoom` in the menu item itself.

We’ll use the same symbols that are already used in Desktop menu item for Zoom, so we also align there.

**Comment by dnarcese** [comment]
@brampitoyo horizontal menu should be doable.

**Comment by q2r5** [comment]
It's implementable with the custom menu views that are currently implemented in app, but it doesn't seem possible in a `UIMenu`; which is what I was thinking of when 'native' was said.

**Comment by k-kruglov** [comment]
Sorry for pinging here, any news on that?

**Comment by lmarceau** [comment]
@k-kruglov We have some other priorities this sprint, but we'll get to this PR as soon as we can 👍 Thanks for pinging us about it!

**Comment by moranbw** [comment]
In Safari you can set page zoom "globally" in the settings, not just a per-site basis. I think this would be very useful on iPhones with smaller screens like the SE.

Not sure if what has been implemented by @q2r5 persists through the page you apply the setting on?

**Comment by k-kruglov** [comment]
Brave on iOS recently implemented this feature. Would be great to have it in Firefox as well.

**Comment by k-kruglov** [comment]
Well, I lost hope by this time.

**Comment by Fail-Safe** [comment]
Hard to believe this is not yet implemented. Is there any hope for this feature in the near future?

**Comment by rmvpress** [comment]
Please add this soon lol

**Comment by bpsib** [comment]
I think this feature is crucial. Far too many websites omit information that I consider essential on the mobile layout. Even on the GitHub website as it hides comment numbers on list of issues making it a headache for me. There's also websites that have tables that get cropped off and can't scroll horizontally to see the rest. So being able to zoom smaller than 100% is essential and I find it unbelievable that this feature is still not available.

**Comment by perbeatus** [comment]
Just switched from Android to ios and I just can't use FF normally. Everything is just too big for my taste ;(

**Comment by eroldru** [comment]
Two and a half years later and this issue is still open. Don’t think it will happen in the near future. Last update from the devs is from Nov 21.

**Comment by dnarcese** [comment]
This feature is coming in v114!

**Comment by valch85** [comment]
Well done. Thank you
