### ISSUE TITLE
Crash when opening (synchronized) login and password data

### ISSUE THREAD

**Issue by kianimo** [mozilla-mobile/firefox-ios#7712]
## Steps to reproduce
* Open Firefox mobile
* Sync with firefox account
* Open settings -> login and passwords

Obviously, the bug depends on the login data stored in firefox lockwise.
I could figure out that the crash was caused by an old entry. It contained only a password but no URL was set. After I removed that entry using Firefox on a computer and synchronized again, the crash doesn't appear anymore.
I don't know how to exactly reproduce. Firefox lockwise prevents creating entries without an URL, but old entries may exist, as in my case.

### Expected behavior
Stored login data is displayed.

### Actual behavior
App crashes, it closes without any error message.
Furthermore the stored logins are not provided in any login form.

### Device & build information
* Device: Apple iPhone X, iOS 14.2
* Build version: Firefox Daylight 29.2 (3120), and earlier versions

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2651)

**Comment by dnarcese** [comment]
@SimonBasca can you investigate how often this will happen? If there is no way in the new password management system to not enter a url then this will be lower priority. But if we are still able to create the issue then it would be higher.

**Comment by SimonBasca** [comment]
I couldn't find a use case for this issue. In the current version of Firefox desktop and iOS the user is unable to add login and password data without a URL. Also you cannot import logins without a URL address.

This issue would have been possible only by syncing users and password without URL address from very early Firefox version when this would be allowed.

**Comment by phyber** [comment]
Since this is probably not being fixed any time soon, I actually just managed to fix it myself.
Anyone wanting to fix this will need to be quick, because Firefox Lockwise is being retired soon.

If you login to Lockwise and sync your logins, you should see all of the problem entries. In my case, it was around 100 or so entries all with the same password, and no username or URL. Clearly not something anyone would do, and I've never used Firefox for storing passwords, so probably the outcome of some past Firefox bug.

I then deleted each of these entries, and allowed Lockwise to sync. Afterwards I synced Firefox on iOS, and clicked on the "Logins & Password" setting, which now works correctly. No more crash, I can see my empty "Saved Logins" list and finally toggle the option to make Firefox stop asking me to "Save Logins".

I hope this helps someone, since there doesn't seem to be a way to resolve this from any other Firefox UI.
