### ISSUE TITLE
[iPad] Top Tabs bar does not hide when scrolling with hardware mouse

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7860]
## Steps to reproduce
1. Go to Youtube. com
1. Scroll the page with mouse
### Expected behavior

* Top Tabs bar should hide when scrolling on the page. When scrolling with swipe gesture the Top Tabs bar hides.
### Actual behavior
* Top Tabs bar should does not hide when scrolling on the page
### Device & build information
* Device: iPad Pro (14.0) with magic mouse 2
* Build version: 30.0 (3279) and main cdef06
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2699)

**Comment by dnarcese** [comment]
Does this also happen with a trackpad?

**Comment by westerlind** [comment]
It does hide sometimes, but most of the time it doesn't. At least for me.
The biggest problem with this is in my opinion that when it does hide, either because it's simply one of those time that it works so far, or because it got hidden when touch-scrolling, it never unhides when scrolling up with a mouse or trackpad as it does when touch-scrolling, which means that there is no natural way to get the tabs back if you are using the iPad more laptop-style at the moment.

**Comment by SimonBasca** [comment]
Similar reports with trackpad: #8868
