### ISSUE TITLE
Add to Photos is not a menu option when Firefox is only given Add Photos Only permissions

### ISSUE THREAD

**Issue by ctozlowski** [mozilla-mobile/firefox-ios#7888]
## Steps to reproduce
In iOS settings, give Firefox "Add Photos Only" permissions. Press and hold on any photo.

### Expected behavior
Add to Photos should be a menu option like in Safari or when Firefox has "All Photos" permissions.

### Actual behavior
Add to Photos is missing from the menu. Instead only Share and Copy are options.

### Device & build information
* Device: iPhone X
* Build version: 30.0

### Notes
The menu option shows up when All Photos is selected, but I would prefer to only give Firefox permission to add photos. This seems like an oversight.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2711)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

In order to save photos we allow basic saving. When user tries to save a photo from web we ask permission that adds it to photos. We can add new PHPickerview support for iOS14 if to allow adding and saving to specific places but that should not stop the user to upload or save photos to their `Photos` album.

**Comment by lmarceau** [comment]
Since only `data-sync-user` has commented on the issue after the `Stalebot` GitHub action (which triggered the removal of the `stale` label) I’ll close this issue for now. Please let us know if you think this issue needs to be reopened, we'll gladly do so. Thank you!
