### ISSUE TITLE
FXIOS-1439 ⁃ Firefox crashes after tapping close all tabs

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#7893]
## Steps to reproduce
1. Have a large number of tabs opened ~ 300
2. Open tabs tray or chronological tabs
3. Tap "Close all tabs" button
### Expected behavior
- All tabs should be closed
### Actual behavior
- Firefox is unresponsive for a couple of seconds and eventually crashes
### Device & build information
* Device: iPhone Xr (14.3)
* Build version: 31.0 (3467)
### Notes
Attachments: 
[Client-2021-01-26-162128.ips.beta.zip](https://github.com/mozilla-mobile/firefox-ios/files/5873915/Client-2021-01-26-162128.ips.beta.zip)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1439)

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

[~irios@mozilla.com] Can you help us with quickly getting 300+ tabs open

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Timebox to a 3

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Investigating issue with close all tabs crashing app with 300 tabs. This doesn't happen on the simulator but it does slow it down and the reason for that is we are not just closing 300 tabs but also saving them for that undo button to restore these tabs. Saving 300+ tabs is an expensive disk operation even if you do it in an async thread because we also save screenshots of those 300+ tabs too. All this combined causes app to slow down and sometimes crash when iOS system deems is unresponsive.

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

https://github.com/mozilla-mobile/firefox-ios/pull/7920 ( https://github.com/mozilla-mobile/firefox-ios/pull/7920 ) - Have made preliminary PR for this issue where close all tabs all will no longer show undo.

I am going to test it out on a device with multiple tabs and see if I put a limit of 100. This way if user has under 100 tabs then show undo otherwise skip showing unto button.

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

If the user has more than 100 tabs and decides to close them all

Part A) Close tabs < 100 with undo button. No issues here.

Part B) Close all tabs > 100 with no undo button 
Reason: Crash happens or could happen depending upon what device you have

  * They open tab tray 
  * Tap on delete button 
  * Close All Tabs action sheet button comes 
  * User taps on action sheet button

Few options:

1. Tabs are closed without undo

2. Warn user and give them option in action sheet to close all tabs that are 
Older than Yesterday
Older than 1 week
Older than 1 month
Close all

3. Another option I can is to give user an illusion of closing all tabs i.e. instead of actually closing tabs we hide these tabs and present option to undo for the time snackbar exist. If user selects not to undo we can remove all these unwanted tabs in the background while user keeps browsing the app. This way we won't change the any UX functionality.

4. Lastly we try to optimize our code and close tabs over 100. This is also possible but will take longer to implement and more investigation.

[~athomas@mozilla.com] [~bpitoyo@mozilla.com]  ^ Let me know how do you feel about these options. I am option to suggestions or any other UX improvement.

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Thank you for the detailed comment. I'm personally okay with #1 because it's already 2-steps to close all tabs.

**Comment by data-sync-user** [comment]
➤ Bram Pitoyo commented:

[~nbhasin@mozilla.com] I agree with [~athomas@mozilla.com]. Although option #2 is clearer and less destructive, option #1 will be easier to implement.

Question: is it possible to keep the “last 100 opened tabs” in the undo queue? This means that we erase tabs that are >100.

This way, people can still undo, but not all the way. We are relying on the fact that they will probably forget/don’t care about the content of tabs that are too old – so these tabs can safely be erased from the undo queue without upsetting expectation.

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

[~bpitoyo@mozilla.com] It should be doable and might take slightly longer to implement. Its a modified version of option #2 but here I'd ask if someone has 100> tabs then how often are they even going to look at their last 10~50 tabs (on phone). Unfortunately we don't have any data for this but its food for thought.

Another suggestion would be to do option #1 for now and in next to next release we do something like modified version of option #2

Ultimately both options are doable and can be implemented in a timely manner.

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

[~bpitoyo@mozilla.com] [~athomas@mozilla.com] 

Tagging both on what are your thoughts about the suggestion above?

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

I am on board with option 1.

**Comment by data-sync-user** [comment]
➤ Bram Pitoyo commented:

[~nbhasin@mozilla.com] I am also on board with option 1, but let’s make sure that we implement option 2 at some point in the future – as closing many tabs without undo/warning is not generally a good idea.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v32.0 (3823). Tapping Close all tabs > 100 does not display the "undo" button. For tabs number under 100 the "Undo" button is displayed.
