### ISSUE TITLE
FXIOS-1469 ⁃ Investigation: Switch to Pull-Down Menus

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#7955]
**Vision**

Goal is to estimate how much work it would be to switch some ofour menus to native pull down menus to help with scoping MR1

**Acceptance Criteria**

* LOE to switch applications menu from custom menu to system-native Pull-Down Menu ([spec](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=51%3A11841))
* LOE to switch page actions menu from custom menu to system-native Pull-Down Menu ([spec](https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=66%3A23))
* Call-out of any risks / questions / considerations
* What will happen on older iOS versions

**Notes**

* Estimate should include iPad and iPhone

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2725)

**Comment by boek** [comment]
My first approach to this was to wrap the PhotonActionSheetProtocol  and see if we could just show the pull down menu on iOS 14. This become a little tricky due to the fact that pull down menus are attached directly to a UIButton using `UIButton.menu` and `UIButton.showsMenuAsPrimaryAction`. In the process I also noticed there is a strong dependency to an object that holds a `TabManager` and `Profile`. My recommendation is not to bring that baggage forward as the new menus don't require any custom UI for FxA.

I think we could create a new lightweight ui component that can handle the backwards compatibility and replace all of the existing implementations of the PhotonActionSheet when used as a menu between a 3 and a 5.
