### ISSUE TITLE
Add ProtonMail to mail client list

### ISSUE THREAD

**Issue by lucasjohnson** [mozilla-mobile/firefox-ios#7968]
### Why/User Benefit/User Problem
If you are a user of the Privacy focused email service Proton Mail, you cannot select it as your default mail client in Firefox iOS. 

### Acceptance Criteria (how do I know when I’m done?)
User can select Proton Mail as there default mail client 

### Not included

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2729)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FXIOS-2729

**Comment by rylancole** [comment]
**Work Around**

iOS 14 allows users to set a default mail service for their device which will also apply to Firefox

1. Open iOS Settings
2. Settings > ProtonMail > Default Mail App > "ProtonMail"

**Note**

This does not close the issue since some users may want to set Default Mail App local to the Firefox iOS App, however this is a working solution for users okay with a global setting

**Comment by jrusinek** [comment]
The workaround with global setting is not a workaround at all.

### Given

- iOS 16.x
- Apple Mail app not installed
- Proton Mail installed and set as default

### When

you click a `mailto:` link in a website

### Then

1. Firefox asks for permission to open an external app.
2. The system asks to restore Apple Mail app
3. Default e-mail client is not opened

**Comment by jrusinek** [comment]
It seems this one has been addressed: https://github.com/mozilla-mobile/firefox-ios/pull/12735

**Comment by jrusinek** [comment]
When is this going to be released? It didn't seem to appear in Jan 17 release.

**Comment by thatswinnie** [comment]
@jrusinek this will be in the next release (110).
