### ISSUE TITLE
Crash on 31.0 after logging into Firefox Accounts

### ISSUE THREAD

**Issue by kelimuttu** [mozilla-mobile/firefox-ios#8006]
## Steps to reproduce
* Download the app from App Store
* Log in to Firefox Account

### Expected behavior
It should work

### Actual behavior
Crashing

### Device & build information
* Device: iPhone XS Max iOS 14.4
* Build version: 31.0

### Notes
This is based on some support questions on SUMO: 

* https://support.mozilla.org/en-US/questions/1325928
* https://support.mozilla.org/en-US/questions/1325958
* https://support.mozilla.org/en-US/questions/1325596
* https://support.mozilla.org/en-US/questions/1325582

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2736)

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Ref: This directly ties with us getting unsymbolicated symbols for Sync crashes.

https://jira.mozilla.com/browse/FXIOS-1149 - Symbolicated crash since v29

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

!image-2021-02-23-13-47-03-651.png!

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

Since this crash is around login, I am going to add some sentry events in that area as we don't really get anything in our XCode reports.

Related crashes from sentry: 

1) [RUST][logins::ffi] Sync error Error(The operation was interrupted.)
https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-320/issues/726036/ ( https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-320/issues/726036/?query=is%3Aunresolved )

2) [RUST][glean_core] Duplicate ping named 'metrics'
https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-310/issues/626463/ ( https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-310/issues/626463/ ) 

3) [RUST][places::ffi] Unexpected sync error: Error(Error synchronizing: HTTP storage error: ServerError { route: "/1.5/158270557/info/collections", status: 503 })
https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-320/issues/730032/ ( https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-320/issues/730032/ ) 

4) [RUST][logins::ffi] Sync error Error(HTTP storage error: ServerError { route: "/1.5/158270557/info/configuration", status: 503 })
https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-320/issues/745483/ ( https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-320/issues/745483/ )

**Comment by rfk** [comment]
Taking a look at some of the linked sentry errors, they feel like they're supposed to be informational error logs rather than crashes.

For example, `[RUST][logins::ffi] Sync error` seems to correspond to [this point the Rust code where we call `log::error!`](https://github.com/mozilla/application-services/blob/6d1a35845982601aa1febf07a6c6629240c2bfad/components/logins/src/ffi.rs#L58). Specifically, the `[logins::ffi]` prefix on the message looks like the sort of thing that gets added automatically by Rust's logging infrastructure. Note that it's not a fatal error at that point, it's just logging the fact that an error occurred and then surfacing it to the calling code.

Similarly, the `[RUST][glean_core] Duplicate ping` message corresponds to a logging call in the Glean code [here](https://github.com/mozilla/glean/blob/69a93da680a651063d924d31637580863e292794/glean-core/src/lib.rs#L707). It's currently at debug level, but it [used to be logged at error level](https://github.com/mozilla/glean/pull/1228) until quite recently. AFAICT this doesn't even surface as an error to the calling code, Glean just logs the message for informational purposes and carries on with what it was doing.

So, I think that the firefox-ios app must be capturing Rust logs at `error` level and piping them through to Sentry.

Indeed, if you look at the "Tags" section of the sentry report (in the right-hand side bar) it says "tag: RustLog", which suggests they are coming from [this sentry logging integration in firefox-ios](https://github.com/mozilla-mobile/firefox-ios/blob/ca2f5c98dd25b8f3026b2bd976450edff1853172/Providers/Profile.swift#L243).

@nishant2718 is it possible that these are being mis-categorized as "crashed: yes" in Sentry, but are not actually crashing the app? Alternately, is it possible that Sentry is actually terminating the app here because it thinks it's logging a fatal exception?

Of course, there is an actual crash in here somewhere, because users are observing an actual crash. But I suspect the linked sentry errors may be red herrings, incorrectly logged as crashers when they are intended as informational reports. (Maybe we should not be logging such things at `error` level at all, but that's a separate discussion).
