### ISSUE TITLE
FXIOS-1700 ⁃ [XCUITests] Fix tests on iPad for the full test plan

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/firefox-ios#8322]
After fixing the smoketest, let's focus now on fixing the rest of tests for iPad device.
Looking at this [scheduled build](https://app.bitrise.io/build/fa91a1c3643d5a4c#?tab=log), the test suites affected are:
- ActivityStreamTest (some tests)
- BookmarkingTests
- ClipBoardTests
- DesktopModeTestsIpad
- DomainAutocompleteTest
- DownloadFilesTests (some tests)
- DragAndDropTestIpad
- FindInPageTests
- HistoryTests (some tests)
- LibraryTestsIpad
- NavigationTest (some tests)
- NightModeTests
- PrivateBrowsingTest
- PrivateBrowsingTestIpad
- ReaderViewTest
- SaveLoginTest (some tests)
- ScreenGraphTest (some tests)
- SearchTests (some tests)
- SyncUITests (some tests)
- ToolbarTests
- TopTabsTest
- TopTabsTestIpad (some tests)
- TrackingProtectionTests (some tests)

Please use the iPad Pro (12.9-inch) (4th generation) to fix the tests as it will be the one used by Bitrise. We have seen that iPad Air (3rd generation) is less reliable than that one. Thanks

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2834)

**Comment by SimonBasca** [comment]
After looking at the test run, I saw that most of the tests are failing because of this line:

`file:///Users/vagrant/git/XCUITests/FxScreenGraph.swift:CharacterRangeLen=0&EndingLineNumber=958&StartingLineNumber=958 - Failed to synthesize event: Failed to scroll to visible (by AX action) TextField, identifier: 'url', label: 'Address Bar', placeholderValue: 'Search or enter address', error: Error kAXErrorCannotComplete performing AXAction 2003 on element AX element pid: 5542, elementOrHash.elementID: 140624653584896.182. (Underlying Error: Error kAXErrorCannotComplete performing AXAction 2003 on element AX element pid: 5542, elementOrHash.elementID: 140624653584896.182)`

These are the test failing due to the mentioned issue: 


- testTopSitesRemoveAllExceptPinnedClearPrivateData

- testBookmarkingUI()
- testUndoDeleteBookmark()

- testClipboard()

- testLongPressReload()

- test4EnsureSchemeIncludedAutocompletion()
- test5NoMatches()

- testDeleteDownloadedFile()
- testDownloadBLOBFile()
- testDownloadFileContextMenu()
- testDownloadMoreThanOneFile()
- testLongPressOnDownloadedFile()
- testShareDownloadedFile()

- testDragAndDropHomeTab()
- testRearrangeTabs()
- testRearrangeTabsPrivateMode()
- testRearrangeTabsTabTrayIsKeptinTopTabs()

- testBarDissapearsWhenOpeningTabsTray()
- testBarDissapearsWhenReloading()
- testFindFromSelection()
- testFindInLargeDoc()
- testFindInPageResultsPageShowHideContent()
- testFindInPageTwoWordsSearch()
- testFindInPageTwoWordsSearchLargeDoc()
- testQueryWithNoMatches()

- testAllOptionsArePresent()
- testLongTapOptionsRecentlyClosedItem()
- testOpenInNewPrivateTabRecentlyClosedItem()
- testOpenInNewTabRecentlyClosedItem()
- testPrivateClosedSiteDoesNotAppearOnRecentlyClosed()
- testRecentlyClosedOptionAvailable()

- testCopyLink()
- testCopyLinkPrivateMode()
- testDownloadLink()
- testLongPressLinkOptionsPrivateMode()
- testLongPressOnAddressBar()
- testNavigation()
- testShareLink()
- testShareLinkPrivateMode()

- testNightModeUI()

- testSendToDeviceFromPageOptionsMenu()
- testShareOptionIsShown()
- testShareSheetOpenAndCancel()
- testShareSheetSendToDevice()

- testClearIndexedDB()
- testClosePrivateTabsOptionClosesPrivateTabs()
- testPrivateTabDoesNotTrackHistory()
- testTabCountShowsOnlyNormalOrPrivateTabCount()
- testClosePrivateTabsOptionClosesPrivateTabsShortCutiPad()
- testiPadDirectAccessPrivateModeBrowserTab()

- testAddToReadingListFromPageOptionsMenu()
- testAddToReadingListPrivateMode()
- testMarkAsReadAndUnreadFromReadingList()
- testMarkAsReadAndUreadFromReaderView()
- testOpenSavedForReadingLongPressInNewTab()
- testRemoveFromReadingList()
- testRemoveFromReadingView()
- testRemoveSavedForReadingLongPress()

- testDeleteLogin()
- testDoNotSaveLogin()
- testSavedLoginSelectUnselect()
- testSearchLogin()

- testSearchWithFirefoxOption()

**Comment by isabelrios** [comment]
Closed as there is #8343
