### ISSUE TITLE
FXIOS-1786 ⁃  [Bug] "Ba..rds" displayed in "Library" view while having the locale set to English (Australia) or English (UK) 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-ios#8447]
## Steps to reproduce
1.  Open Bookmarks
2. Open any default folder
3. Check the upper left side of the Bookmarks View

### Expected behavior
Step3: ⬅️ "back" button should be displayed

### Actual behavior
Step3: "Ba..rds" button displayed

### Device & build information
* Device: iPhone X (13.4)
* Build version: 34.0 (4722) 

### Notes
► Screenshot
![rsz_screenshot_2021-05-14_at_003343](https://user-images.githubusercontent.com/51314259/117283592-9be45480-ae6e-11eb-8496-2e94d989411c.png)

## Alternative Steps to reproduce
1. From the home screen tap the ☰ button
2. Tap Reading list
3. Check the upper left side of the Bookmarks View

### Expected behavior
Step3: ✖️ "close" button should be displayed

### Actual behavior
Step3: **Unusable** "Ba..rds" button displayed

### Device & build information
* Device: iPhone X (13.4)
* Build version: 34.0 (4722) 

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1786)

**Comment by electricRGB** [comment]
This is two bugs, a localization one, and a Library Panel state one. Let's keep this ticket for the localization aspect. I'll address the functionality aspect in #8453

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

Let's change the size of the Back button so the word won't truncate. This will be fixed in #8453

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

To address this issue, we should change the translation in Pontoon to be "Back" instead of "Backwards"

**Comment by SimonBasca** [comment]
Note:
This issue will still be visible for other locales (e.g. Dutch).

![IMG_6749](https://user-images.githubusercontent.com/32130829/117417368-ef17df00-af22-11eb-8a57-b389e75377af.PNG)

**Comment by electricRGB** [comment]
I think this issue is really a design issue at heart. Patching fixes in won't really be helpful until we come up with a way to deal with this totally. Generally, when I think of designing things that have text, I try to use double length strings. If it works for those, it'll work for... most languages.

My recommendation here is this: we change the size of the button's frame - and left/right align text as required - to allow for larger words. But we also implement a minimum font size, so that larger words, if they don't fit, will shrink to a minimum size we specify. This will allow us to keep the same translations in Pontoon, and fix the problem, albeit at the sacrifice of some accessibility for really long words.

@brampitoyo how do you feel about this?

**Comment by brampitoyo** [comment]
@electricRGB @AndiAJ This is a really interesting problem.

I checked our en-GB locale, and found that “Back” was translated to “Backwards”. This is odd. I set my iOS language to en-NZ (which is similar to en-AU and en-GB), and have never seen “Backwards” used anywhere. Instead, I always see “Back”.

For English locales, I think the right solution is to use “Back”, which is just as understandable in almost every context as “Backwards”. If nothing else, this is evident in the usage of “Back” instead of “Backwards” everywhere else in iOS.

What would happen if the page title is so long, that it overrides both `< Back` and `Done` items?

Let’s start with `< Back`. When overridden, the `Back` string should be hidden in favour of showing only the `<` symbol. You can see the same approach at work under “Exposure Notifications” and inside “Active Region”.

<img width="320" src="https://user-images.githubusercontent.com/51007/117595595-589f2400-b195-11eb-97f0-1112055d360e.jpeg"> <img width="320" src="https://user-images.githubusercontent.com/51007/117595599-5b017e00-b195-11eb-9b44-6324e1615b12.jpeg">

What would happen to the `Done` item? Unlike the `Back` string, the word `Done` should never be hidden. Instead, the page title string should cut off with an ellipsis. You can see this approach when you create a bookmark folder with a very long name in Safari.

![IMG_12931BD875CC-1](https://user-images.githubusercontent.com/51007/117595981-512c4a80-b196-11eb-9ff8-949b6b210c77.jpeg)

Hope this helps?

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Sounds like we have 2 steps to the solution:

  * Change the copy to "Back" instead of "Backwards" from EN locales
  * Update the button sizing to accommodate longer words (described above)

Is this ticket being fixed for this release?

**Comment by data-sync-user** [comment]
➤ Ashley Thomas commented:

Solution is to remove text and only show backwards arrow.

**Comment by SimonBasca** [comment]
Verified fix on v 34.0 (4847).
