### ISSUE TITLE
FXIOS-1860 ⁃ v34 - Tabs grid Segmented Control gets clipped when narrow split

### ISSUE THREAD

**Issue by gutley** [mozilla-mobile/firefox-ios#8545]
## Steps to reproduce
On an iPad, open up the Tabs view when Firefox is in the narrowest split on a split screen.

The [Tabs|Private|Synced] segmented control gets clipped on the right. Also the Trash and + buttons go offscreen completely.

### Acceptance Criteria
We should use the iPhone view with the icons on the segmented controls, and toolbar on the bottom. This has been confirmed with Bram.

### Actual behavior
![](https://user-images.githubusercontent.com/11432165/122102704-b56caa80-cde3-11eb-93c0-1e4d6cfa47cd.png)

### Device & build information
* Device: 5th Gen iPad (Simulator)
* Build version: Local build, using 0347f2fba077ef80292b8ea1ccdd0548b20dd61c
  1. Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2056)

**Comment by SimonBasca** [comment]
Verified fix on 3b9c2d558f0.

**Comment by gutley** [comment]
This isn't a very good fix as it's only valid if the screen is already split when showing the tabs grid. If the screen is split when the tabs grid is already on screen then the view is still messed up.

Ie. It doesn't react to changes while already shown.

**Comment by SimonBasca** [comment]
@gutley you are correct. After following the STR i am reproducing the issue

STR:
1. Open note
2. Open Firefox in the largest split on a split screen.
3. Open Tabs Tray
4. Resize Firefox to the narrowest split screen view.

Video: 
- [video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6732028/video.mp4.zip)

@electricRGB what do you think? Should we re-open the issue or log a new one?

**Comment by gutley** [comment]
This is actually a common problem throughout Firefox. Often, it never adapts properly to live changes to traits. It just does it once when views are shown based on the current traits. With iOS 15 making split views much easier to manage this is going to become more prevalent.

Maybe we need another ticket for all the cases this happens and when we have spotted them all have a plan for a consistent fix across the whole app.

**Comment by electricRGB** [comment]
@SimonBasca So, the way the tab tray screen is set up, simply redrawing based on resizing is not possible because we're currently using size classes to determine which setup to use when the screen is called: ipad or iphone, because these are two different designs. And because they have different implementations, redrawing won't really work. to do this, you'd have to rework a significant chunk of the tab tray screen - which can certainly be done. The question is, how high a priority do we think resizing the tab tray screen is? 

Either way, I'd argue this would be a new ticket as the fix addresses the issue when the tab tray is opened. We could have a ticket to make the resizing of the tab tray.

@gutley This is a design issue, in terms of the whole app. We don't really have a design system in place, which means that there's different implementations for different screens for different size classes based on whatever the design at the time was. While we can tackle this issue progressively as we're reworking screens, doing it for the whole app will take quite a lot of engineering/design work. The big issue is that, often, iPad vs iPhone designs are different enough that simply redrawing the screen isn't enough to adapt to new stuff isn't enough.

**Comment by SimonBasca** [comment]
I've created #8804 to keep track of the issue but I agree with @electricRGB and don't think this is a high priority issue.

**Comment by SimonBasca** [comment]
Verified fix on 35.0 (5448).
