### ISSUE TITLE
FXIOS-1862 ⁃ Sync not working on China app version

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-ios#8547]
We have received multiple reports recently in app store reviews of sync not working in China app version

A couple quotes:

"The reason why the synchronization fails is because of the download channel. You can find a way to change the store ID to another country before downloading the application, and finally switch using the international account! "

"Please provide the normal version. This cn version cannot be synchronized "

"Tabs are no longer synced...Even if you install the US client, as long as you change the phone language to simplified Chinese, your account will definitely be automatically switched to the country, unless you log in again to change it. Regarding the synchronization of international accounts, be sure to log in in the settings menu when logging in, and never open the "local synchronization service" button! ! ! If it is turned on, it is the domestic server synchronization! ! !"

These reports were from users on v33 of the app, however, it's unclear how long this has been an issue

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1862)

**Comment by mhammond** [comment]
We discussed this in slack - I learned there's no "China app version" for iOS (there is for Android and Desktop, but not iOS) - Firefox for iOS changes its settings based on the device's locale - if the locale is set to `zh_CN` it will use the servers in China, otherwise it will use the "global" servers. This has the following impact:

* If the user changes their locale to or from `zh_CN`, their servers will change, meaning they might be surprised about what is synced, and which other devices are able to sync (eg, a non-chinese Desktop build with an iOS device set to that locale will be syncing to different servers)
* If the user is outside of China but uses that locale, or is inside China and does not use that locale, they are highly unlikely to be able to reach any sync servers.

It's not clear to me if any of the reports above can be explained by this, but hopefully it provides enough info to dig deeper.

**Comment by bli-mozbj** [comment]
On our side, everything works fine.  Sign in flow is OK, and Bookmarks/History/Tabs can be synced.

The "local synchronization service" option will be shown and enabled as default only when the following **two conditions are met**:
1. Region is **China mainland** 
2. Language is **Simplified Chinese**

Users can switch that off. When this option is off, sync service will be the standard one.

To better understand the situation, could you please share the original reviews with me?

**Comment by LarkAnspach** [comment]
Please suggest how to proceed

**Comment by athomasmoz** [comment]
Thank you for testing this out. I tried the steps on my side too with iPhone 11 on iOS 14.5.1 and I had to "sync now" a few times, but the tabs did eventually show up. Let's close this ticket for now and I will continue to monitor reviews
