### ISSUE TITLE
Undo closing Private Tabs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8818]
Current Behaviour
1. Click trash can on private tabs
2. close tab tray
3. observe snackbar and click Undo
The tabs do not get restored.

This might be an expected feature that we do not want to restore private tabs. If that is the case, then we should remove the Undo button from the toast.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2936)

**Comment by isabelrios** [comment]
This might be a regression..that toas button was not shown for the Private Tabs before. Also, if you look at the number of tabs to restore, it matches the number of regular tabs no the private tabs. Clicking on Undo it adds the same regular tabs that you have to the regular tabs. So the undo feature for private tabs that should not be shown, it is introducing a bug now. 
I will add the bug label so that this is somehow prioritazed and removed.

**Comment by SimonBasca** [comment]
Confirming that this is a regression. We didn't show the "Undo Closed Tabs" toast in Private Browsing in v33.1 (4629). The first bad build is 34.0 (4551).

**Comment by SimonBasca** [comment]
In my case after this is what happens.
### Preconditions:
- Have 3 tabs opened in Normal Browsing: "digi.ro", "beatport.com", "google.com"
- Have 1 tab opened in Private Browsing : support.mozilla.org
### STR:
1. Go to Private Browsing
2. Tap "Close all tabs" button
3. Swipe down to dismiss tabs tray
4. Tap "Undo" button

### Actual results:
- After tapping "Undo" tow tabs from Normal browsing are restored although they were not closed. Also the UI in tabs tray shows that I am in normal browsing but the colors show the Private browsing theming. 

Video of the issue  : [video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6808833/video.mp4.zip)

**Comment by SimonBasca** [comment]
Seems similar to #8794
