### ISSUE TITLE
document.documentElement.clientHeight (and 100vh) changes on address bar hide (page scroll)

### ISSUE THREAD

**Issue by theodore-earnin** [mozilla-mobile/firefox-ios#8819]
## Steps to reproduce
```javascript
window.on('resize', () => {
   console.log(window.document.documentElement.clientHeight)
})
```

or create a 0-width element with 100vh and log it's height on window resizing.

### Expected behavior
For most other mobile browsers (as far as I can tell at least, tested on Safari/Chrome/Firefox on Android), this size remains constant even when the address and bottom bar hide on navigation, and only changes on actual window resizing/reorientation. 

### Actual behavior
The height of 100 vh (and document.documentElement.clientHeight) changes (increases) as the address bar shrinks and bottom bar hides after scrolling on the page. This makes it more difficult to build interoperable websites without having a consistent and easy-to-use way of determining the dimensions of the visible view on page load. What I'm experiencing doesn't seem like desired behavior, especially if other webpages rely on similar assumptions.

### Device & build information
* Device: iPhone 12
* Build version: Firefox Daylight 34.2 (5301)
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2937)

**Comment by hiaselhans** [comment]
I can confirm this bug.
On ios safari & chrome don‘t show this behavior while firefox does…

**Comment by johannesodland** [comment]
Can confirm the same bug. Firefox on iOS is inconsistent with most browsers here, and are causing web compat issues. Most browsers stopped resizing vh since [chrome stopped in 2016](https://developer.chrome.com/blog/url-bar-resizing/). 

It is possible to use [David Bookans test page](https://bokand.github.io/demo/urlbarsize.html) to replicate the issue.
This page tests the [new viewport units lvh, dvh and svh](https://www.w3.org/TR/css-values-4/#viewport-relative-lengths) as well.

The new units are supported in webkit since Safari 15.4, and can be supported in WKWebView from iOS 16 on I believe: https://developer.apple.com/documentation/webkit/wkwebview/3974127-setminimumviewportinset

**Comment by johannesodland** [comment]
Related: https://github.com/mozilla-mobile/firefox-ios/issues/11574
