### ISSUE TITLE
Website data is not correctly cleared

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8854]
## Steps to reproduce
1. Go to Settings -> Data Management ->  Website Data
2. Tap on the Filter field.
3. Type one letter that bring one results
4. Select one result
5. Tap "Clear" button
### Expected behavior
- The result should be cleared.
### Actual behavior
- The result is cleared only after clearing the filer field. 
Device & build information
* Device: iPhone Xr (14.5)
* Build version: 35.0 (5448)
* Notes
Attachments: 
[Video.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6815958/Video.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2961)

**Comment by data-sync-user** [comment]
➤ Daniela Arcese commented:

From the video, it looks like it disappeared slightly before you cleared the search field. Can you check whether it is just taking a few seconds to clear?

**Comment by SimonBasca** [comment]
In the video the results get cleared because I tapped on the search field. So either tapping on the search field or clearing it will cleared the results after they are deleted.

**Comment by Jsdemonsim** [comment]
I'm running Firefox for iOS ( Firefox Daylight 39.0 (6519) ) on an iPad Air 2.  I also can't clear Website Data if I search for a specific website using the Filter Sites field.

However, in my case, when I follow the steps in the OP above and then clear out the Filter Sites field, it does **not** clear the result.  When I try to select a filtered site by tapping the circle to the left of the site, a check mark is displayed for a split second but then disappears when I let go of the screen.  As you can see in my screenshot, it says "Clear Items: 2" (I selected the first 2 sites, but the check marks disappeared), but none of the sites are shown as selected.  If I tap "Clear Items: 2", it asks for confirmation, I select OK, but then the sites are not cleared.

I think what's happening is that when I select a site in the filtered list, it's actually selecting a different site from the complete list of sites.  For example, if there are 3 sites in the filtered list, and I select the 2nd one, what's actually selected is the 2nd site in the complete list of sites (which is why the check mark disappears).  If I clear out the filter search keyword, then I can see that the 2nd site of the entire list is selected, which isn't the same as the one I selected from the filtered list.

![IMG-2769](https://user-images.githubusercontent.com/8776534/142511123-99652c4d-3f67-4a24-ad81-3402d140c6db.PNG)

**Comment by lmarceau** [comment]
Brought this as QA Needed as part of the https://github.com/mozilla-mobile/firefox-ios/pull/10147/files PR bugfix

**Comment by SimonBasca** [comment]
Verifying as fix on main 9ecd93a5be10df8d663feebcd3cce14378a4e551.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main 9ecd93a5be10df8d663feebcd3cce14378a4e551.
