### ISSUE TITLE
Unable to autofill login on google login page

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8939]
Preconditions:

* Enable Fennec as auto fill in iOS settings
  1. Steps to reproduce

1. Go to a google.accounts.com login page
1. Tap on the user field
  1. Expected behavior

* The "passwords: button should b displayed like in Safari
  1. Actual behavior
* The "passwords" button is not displayed above the keyboard
  1. Device & build information
* Device: iPhone Xr (14.5.1)
* Build version: b17e7f53d929
  1. Notes
* After manually typing the login and the password field is displayed, the user is able to auto fill the password.
Attachments: 
[Video1.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6917821/Video1.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3020)

**Comment by alvarokrn** [comment]
Also happening on playstation.com which also only shows the username field and you have to click on next to put the password.

I think is an annoying bug which happens a lot since Google is one of the most visited websites and it is a way of asking credentials which websites are introducing more and more

**Comment by n-martynova** [comment]
Is there any new information about this bug? Still reproduceable in Firefox 108.1 (24234)
