### ISSUE TITLE
Firefox Sync 'Device Name' Changes on iOS not Reflected on Other Devices

### ISSUE THREAD

**Issue by emaraszek** [mozilla-mobile/firefox-ios#8944]
### Steps to Reproduce
1. Sign in to Firefox Sync on an iOS device
2. Change the Firefox Sync 'Device Name' to something other than the default name
3. Sync the device
4. View the connected devices from another device (desktop, second iOS device, etc.)

### Expected Results
- 'Device Name' for iOS device is changed and displays correctly on all other connected devices

### Actual Results
- 'Device Name' for iOS device displays as the default name for the device ("Firefox on iOS Device Name") on all other connected devices

### Notes
- 'Device Name' IS updated on Firefox Account page and on the individual iOS device
- Manually initiating a sync on the affected device does not address the issue
- Removing and re-adding the device does not address the issue
- Issue is reproducible on both iPhone and iPad, running iOS/iPadOS 14.6 with latest Firefox version available in app store (Daylight 35.0 5448)

### Device Information
- Tested on Windows 10 (Firefox 90.0.2 64-bit), Ubuntu 20.04 (Firefox 90.0 64-bit), iPhone 11 Pro/iOS 14.6 (Firefox Daylight 35.0 5448), and iPad Air 2/iPadOS 14.6 (Firefox Daylight 35.0 5448)

### Screenshots
Name changed on iPhone:
![20210802_IMG_0969](https://user-images.githubusercontent.com/7446498/127915818-33ce173c-4d49-4b0a-851c-1448399b421e.png)

Name changed on iPad:
![20210802_IMG_0012](https://user-images.githubusercontent.com/7446498/127915843-99351660-8400-4909-93e2-c144687b8487.png)

Name change reflected on Firefox Accounts page:
![Screenshot 2021-08-02 152556](https://user-images.githubusercontent.com/7446498/127915868-df7989a4-5ff2-4cc1-ad8c-fb9cb8994223.png)

Name changes not reflected on desktop browser:
![Screenshot 2021-08-02 153902](https://user-images.githubusercontent.com/7446498/127915924-1c65f079-8e8c-46eb-b18f-7c6514ba13a7.png)

iPad name change not reflected on iPhone:
![20210802_IMG_0970](https://user-images.githubusercontent.com/7446498/127915970-8f256d7f-e503-4a99-b2ad-db51dd5f8e91.png)

iPhone name change not reflected on iPad:
![20210802_IMG_0013](https://user-images.githubusercontent.com/7446498/127918655-30426eb7-7f3c-4899-9348-eecaae734837.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3024)

**Comment by mhammond** [comment]
> Name change reflected on Firefox Accounts page:

This means that the rename correctly happened in the FxA world - and FxA is supposed to be the canonical source of the name, but it's sadly a bit more complicated than that for tabs.

The name is also stored in the "clients" collection in Sync. In theory these should always be up to date, but that might not be the case for iOS. There's an [addon for Desktop firefox](https://addons.mozilla.org/en-US/firefox/addon/about-sync/) that might help here - if you find the "clients" collection in that addon, then find the record that corresponds to the iOS device where the name was changed, it would be great to know if that is the old name or the new name. In particular, it might even be the case that the names are different until the app restarts.

These names being different would probably explain the wrong name being used on mobile (both Android and iOS)

For desktop in particular, even if the names are different in the "clients" collection, it should always use the FxA name (which the screenshots above show is as expected) - however, Desktop may cache the external device names for up to 2 hours. So this might explain the Desktop behaviour - this caching is in memory, so I'd expect to see this also be fixed by a restart.

**Comment by emaraszek** [comment]
Hi @mhammond,

I installed the extension and it appears to show the old name for both iOS devices. There also appear to be duplicates for each device:
![Screenshot 2021-08-09 194410](https://user-images.githubusercontent.com/7446498/128788022-6e657588-e7be-44d5-821e-3b7f49940e51.jpg)

> For desktop in particular, even if the names are different in the "clients" collection, it should always use the FxA name (which the screenshots above show is as expected) - however, Desktop may cache the external device names for up to 2 hours. So this might explain the Desktop behaviour - this caching is in memory, so I'd expect to see this also be fixed by a restart.

I have also tried restarting Firefox and the PC, but neither have helped

**Comment by mhammond** [comment]
Re desktop, I just discovered [this comment](https://searchfox.org/mozilla-central/rev/f71cb98fc35da418d2cb9ce31a0416d532dc9d69/services/sync/modules/engines/clients.js#410) which might explains this. Does that device have a value for `fxaDeviceId`?

**Comment by emaraszek** [comment]
Yes, all of those name records have a unique fxaDeviceId associated with them

**Comment by mhammond** [comment]
So yeah, I did misread desktop's code yesterday - it uses that client record. It would be relatively easy to fix that on desktop - however, I believe Android will still use that client record (via application-services) and that's trickier to change. So the biggest impact we can have is probably to ensure iOS makes them consistent.

Best I can tell, the name in the "clients" collection is managed via the `PrefClientName` pref [here](https://github.com/mozilla-mobile/firefox-ios/blob/191a36c6e852686b3b4452e4637d39527d652f08/Sync/State.swift#L587). I'm not familiar enough with the iOS code to know for sure, but I *think* the FxA device name is `localName` [here](https://github.com/mozilla-mobile/firefox-ios/blob/main/Providers/Profile.swift) - but I can't see how it is updated - but however that happens, I think we'd also need to make sure that `State.swift` link above is also told. I'm happy to discuss this more.

**Comment by mhammond** [comment]
We fixed desktop in bug 1702492, so I think this can be closed.
