### ISSUE TITLE
User-Agent Header at iPhone and iPad contains Mac OS X string instead of iPhone

### ISSUE THREAD

**Issue by kyberorg** [mozilla-mobile/firefox-ios#8946]
## Steps to reproduce
* Visit any site that reports User-Agent. 
* Get current User-Agent in reply 
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
```

### Expected behavior
I expect that User-Agent string contains "iPhone" word.

### Actual behavior
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
```

### Device & build information
* Device: iPhone 7 with iOS 14.4.2/iPad with iOS 14.7.1
* Build version: Firefox Daylight 35.0 (5448)
### Notes
Attachments: 
![66690](https://user-images.githubusercontent.com/4687253/128026451-48be2319-8f53-47bd-bf2c-b8b64aba50fe.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3026)

**Comment by ksy36** [comment]
Thanks for the report @kyberorg. 

I can't reproduce the issue on an iPhone (Firefox Daylight 35.0 5448, iOS 4.6).
<img src="https://user-images.githubusercontent.com/1303908/128548294-433d154c-0223-429b-ba87-be78f1b73466.PNG" width="300">

It should only return Safari Mac OS X desktop UA on an iPhone if "Request desktop site" option is enabled (three dots menu -> Request Desktop site).  If it's on, you'll see "Request mobile site" and it's possible to flip the property. 
Note that mobile is the default mode on an iPhone.

For the iPad, it's the opposite and we have desktop mode by default, so the UA string that you're getting is expected. We use a desktop Safari UA at the moment because there were a number of reports with sites showing browser out-of-date warnings for Firefox iPad UA. More info on this issue  https://github.com/mozilla-mobile/firefox-ios/issues/6310

**Comment by kyberorg** [comment]
@ksy36 you are right. In my case "Request desktop site" option was enabled. Without this Firefox gives correct UA (with iPhone words inside).

Thanks for pointing this up. 
Closing this issue as it is local configuration issue.
