### ISSUE TITLE
Tabs counter is not updated in tabs tray after closing a tab

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#8955]
## Steps to reproduce
1. Open a few tabs
1. Open tabs tray
1. Close one tab
1. Check the tabs counter in tabs tray
    1. Expected behavior

* Tab counter should be updated
    1. Actual behavior
* Tabs counter is not updated. Only after closing tabs tray the tabs counter is correctly updated.
    1. Device & build information
* Device: iPhone Xr (14.5)
* Build version: 36.0 (5718)
    1. Notes
Attachments: 
[video1.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/6930305/video1.mp4.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3036)

**Comment by isabelrios** [comment]
We have an [automated test ](https://github.com/mozilla-mobile/firefox-ios/blob/main/XCUITests/TopTabsTest.swift#L92)that verifies closing a tab from tab tray, but the tab counter is not being checked currently. I think we had that and was removed for some reason, but worth investigating to add that check again since this is not the first regression around this. I will open a task for that

**Comment by kcome** [comment]
A [PR](https://github.com/mozilla-mobile/firefox-ios/pull/9032) to fix this issue is created. UI test is not added though.
