### ISSUE TITLE
Reload button not showing up on phones in landscape mode & iPads

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#9052]
v37.0 (5922)
iPhone 12 Pro (14.6)

**Case 1:**
1. While in portrait, visit a page that supports reader mode.
2. Switch to landscape.

   Actual 1: The Reload button is not displayed in the URL bar

3. Tap on the reader mode button

   Actual 2: The Reload button shows up in the URL bar

**Case 2:**
1. While in landscape, open a new tab and visit a page that doesn't support reader mode.

  Actual 1: The Reload button is not displayed

2. in the same tab visit a page that supports reader mode

   Actual 2: Both buttons - Reload & reader mode - are displayed correctly

**Case 3:**
The Reload button doesn't show at all on iPads

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3120)

**Comment by nishant2718** [comment]
Hey @csuciu , I can't reproduce Case 2, step 2. For me, the reload icon appears OR (on wikipedia for example), the icon stays as the Stop icon. 

Using an iPhone 12 mini on landscape. 

As far as iPads, the reload icon shouldn't appear in the URLBar right? Since it appears as part of the toolbar to the left?

**Comment by data-sync-user** [comment]
➤ Nishant Patel commented:

A PR for this https://github.com/mozilla-mobile/firefox-ios/pull/9065 ( https://github.com/mozilla-mobile/firefox-ios/pull/9065|smart-link ) .

**Comment by SimonBasca** [comment]
@nishant2718 confirming that Case 2, step 2 the reload icon appears as the Stop icon for iPhone 12 Pro. On iPhone Xr the icon is not displayed, but long pressing on the empty space will open the long press on refresh button 

![image](https://user-images.githubusercontent.com/32130829/132221632-d7b7b0a9-132d-4186-b1cb-3ac00ec20abe.png)

On iPad there are no designs mentioning the reload button but after tapping on it, the page goes to the Home instead of reloading. (See #9053)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on v37 (5917)

**Comment by data-sync-user** [comment]
➤ Catalin Suciu commented:

Hey Nishant Patel . This happens on the latest TF build on iPhone 12 Pro https://github.com/mozilla-mobile/firefox-ios/issues/9092 ( https://github.com/mozilla-mobile/firefox-ios/issues/9092|smart-link ) . Isabel also noticed this issue on latest master.
