### ISSUE TITLE
Check SSL certs for lock icon

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9086]
From [https://github.com/mozilla-mobile/firefox-ios/issues/9082](https://github.com/mozilla-mobile/firefox-ios/issues/9082|smart-link)

As a user, I want to know if the website I am visiting has a valid SSL certification. When I see “Connection is secure” I understand that to mean it is https and has a valid cert.

* The lock icon shows if the website is https and the ssl certification is valid
* If the site is http or the ssl cert is expire, revoked, or untrusted, the lock icon with a slash through it will show

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3143)

**Comment by kcome** [comment]
I created a [PR](https://github.com/mozilla-mobile/firefox-ios/pull/9104) for this issue. Hope it fixes the issue.

@dnarcese @SimonBasca

**Comment by electricRGB** [comment]
@kcome There is some information missing in this ticket. I've updated it. We need to check the cert itself for whether it's expired/revoked/untrusted or valid.

**Comment by kcome** [comment]
@electricRGB From the source code, I see in memory CertStore is only used for storing invalid certificate because there is only one call of `addCertificate` in [ErrorPageHelper.swift](https://github.com/mozilla-mobile/firefox-ios/blob/041c85483b1aa4a4e357d8bd9419550e4f20347a/Client/Frontend/InternalSchemeHandler/ErrorPageHelper.swift#L304).

If `CertStore` is also storing other valid certificate, surely we will add validity check.

**Comment by electricRGB** [comment]
@kcome Because we're looking to do a few things with SSL certs such as inspecting the issuer as well as using it for the lock, we're going to need a way to inspect the SSL cert that's more than just checking if it's an invalid cert in the `CertStore`.
