### ISSUE TITLE
Page gets refreshed when "pinch to zoom out"

### ISSUE THREAD

**Issue by csuciu** [mozilla-mobile/firefox-ios#9174]
v38.0 (6122)
iPhone 12 Pro (iOS 15)

1. Visit a webpage.
2. Scroll the page to the top.
3. Pinch to zoom out the page.

Expected: The page is not refreshed.

Actual: The page is refreshed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3207)

**Comment by data-sync-user** [comment]
➤ Roux Buciu commented:

So, I've done some investigating on this. My findings: the page gets refreshed when "pinch to Zoom out" because it's an artefact of pull to refresh feature. In fact, Safari has the exact same behaviour. And it only refreshes if you zoom out to where the pull to refresh would trigger - on both Fx and Safari.

**Comment by csuciu** [comment]
Closing per previous comment.
