### ISSUE TITLE
Failing tests on main

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#9234]
The test cases below are failing on main

Ref: https://app.bitrise.io/build/4bedca05-5a4a-4252-af2f-e489963d0f08#?tab=log

---

XCUITests.AuthenticationTest
  testPromptPassCodeUponReentry, Cannot get from PasscodeSettings to SetPasscodeScreen. See /Users/vagrant/git/XCUITests/FxScreenGraph.swift:748
  /Users/vagrant/git/XCUITests/AuthenticationTest.swift:47
  ```
        navigator.nowAt(NewTabScreen)
        navigator.performAction(Action.SetPasscode)
        navigator.goto(SettingsScreen)
  ```
XCUITests.HomePageSettingsUITests
  testJumpBackIn, XCTAssertTrue failed
  /Users/vagrant/git/XCUITests/HomePageSettingsUITest.swift:203
  ```
        app.buttons["jumpBackInSectionMoreButton"].swipeUp()
        XCTAssertTrue(app.cells.collectionViews.staticTexts["Example Domain"].exists)
        // Swipe down to be able to click on Show all option
  ```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3241)

**Comment by data-sync-user** [comment]
➤ Isabel Rios Escobar commented:

The Authentication test is failing because the menu to go to Passcode Settings is down in the Settings list and so it is not clickable. I have a PR to fix that. 

The other test has been disabled as that menu does not appear on simulator first time a site is visited. Investigating if that could be a real issue
