### ISSUE TITLE
Send Tab to Device unresponsive when started from share sheet

### ISSUE THREAD

**Issue by rghedin** [mozilla-mobile/firefox-ios#9265]
## Steps to reproduce
* In any app, open the share sheet.
* Select Firefox app.
* Tapping “Send to device” in the popup list (see image attached; it's “Enviar para dispositivo” option, in Portuguese) doesn't work at first. Sometimes I need to tap several, more than ten times to it work.

### Expected behavior
* “Send to device” option in Firefox's share sheet work at first tap.

### Actual behavior
* “Send to device” option in Firefox's share sheet only work after several taps.

### Device & build information
* Device: iPhone 8, running iOS 15. The issue was present in iOS 14.x.
* Build version: Firefox 38.1

### Notes
Attachments:

![IMG](https://user-images.githubusercontent.com/19216581/136389922-e6269968-6642-4675-8ece-ced660695cab.PNG)UNITO-UNDERSCORE!7451!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3260)

**Comment by nhoizey** [comment]
I also have the issue on an iPhone when the connection is not good.

Based on past discussions on Twitter (I can't find the link, sorry), it could be because the list of devices is fetched live, before being shown, to make sure it's accurate. Some devices could have been removed or added since last sync. I don't if this is true, just reporting what I've read in the past.

If this is true, I think a really short timeout for this live fetch would mitigate the issue.
