### ISSUE TITLE
Facebook app is launched when trying to reload "Facebook.com"

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9561]
## Preconditions:
* Have facebook app installed.
  1. Steps to reproduce

1. Disconnect internet connection
1. Go to "facebook.com"
1. Tap on "Try again"
    1. Expected behavior

* The page should reload.
    1. Actual behavior
* The Facebook app is launched.
    1. Device & build information
* Device: iPhone 12 Pro 15.1.1
* Build version: 40.0 (6631)
    1. Notes
Attachments:

https://user-images.githubusercontent.com/32130829/143474452-bd5a4c87-c9e7-49bb-b053-163dd306507a.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3471)

**Comment by gutley** [comment]
I've not tested it, but I suspect the same would happen for any app that supports deep linking that also has an app on the phone.

I wonder if this can be fixed by changing the action button script below to set the scheme of the url to one of the internal firefox schemes (via URL.mozPublicScheme) and letting the url roll through the Navigation router ???

`        var actions = "<script>function reloader() { location.replace((new URL(location.href)).searchParams.get(\"url\")); }" +
                    "</script><button onclick='reloader()'>\(tryAgain)</button>"
`
E.g firefox://m.facebook.com or firefox-internal://m.facebook.com
