### ISSUE TITLE
Open Tabs - Switching interruption

### ISSUE THREAD

**Issue by BigSamSampson** [mozilla-mobile/firefox-ios#9630]
## Steps to reproduce
1. Click on the Home icon
1. Open "Open tabs"
1. Change Private and normal mode
    1. Expected behavior
The transition between the selection (white rectangle) will be smoothly carried out
    1. Actual behavior
The transition between the selection (white rectangle) transitions with a hover
    1. Device & build information

* Device: Apple iPhone 7 Plus - iOS 15.1, Wi-Fi
* Build version: Firefox daylight 39.0(6519)
    1. Notes
Attachments: 

https://user-images.githubusercontent.com/66958331/145992213-59a99d22-e8f6-4b8b-a459-5c0ea8fb066a.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3517)

**Comment by junbio** [comment]
Seems like the hitch is due to the call to snapshotView in GridTabViewController.didTogglePrivateMode since it doesn't occur when there aren't any private tabs. It's hard to come up with a fix not knowing if it's a bug in iOS or expected behavior though.

On a related note, there is a call to layoutSubviews which is incorrect since it is not supposed to be directly called, per Apple documentation. Maybe it should be replaced with layoutIfNeeded?
