### ISSUE TITLE
Fx Homepage long press gesture doesn't behave correctly

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#9659]
Currently, the logic for the long press gesture context menu only happens to work because of screen ordering. But, if screen ordering is changed, what the logic is returning becomes wrong.

In order to implement the new header on the Homepage, this must be fixed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3539)

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verified fix on main 552d8a87a. I’ve tested that deleting website shortcuts via the long press context menu displays the websites in the correct order. Also checked that all the website shortcuts can be deleted and also checked that all the context menu options are functional.

Roux Buciu do you think there is any other use case to test here?

**Comment by electricRGB** [comment]
Heeeey. So. Funny story. This fix won't actually be testable until the Firefox Logo makes it into beta. Or, if you build this locally, you could test it then. 

Basically, if the shortcuts section is the first section on the homepage, it'll behave exactly before. However, if the Shortcuts section is not first (ie, in the case where we add the Firefox Logo as a section above it in the future), then the context menu wouldn't appear because the index calculation was wrong. But it was wrong in such a way that, if Shortcuts was first, it was accidentally right. Basically, the index calculation always returned `IndexPath(section: 0, row: X)`, even if it should have returned `IndexPath(section: 1, row: X)` (where `X` was the correctly returned row in both cases).

It's a bit confusing but I hope that makes sense.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Thanks for the information Roux. I’ve tested this on latest main build locally 627116c214 and everything seems to be working Ok. The context menu is correctly displayed and all the options from the context menu are functional. 

Marking as verified fix.
