### ISSUE TITLE
The stop loading page button is not working correctly

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-mobile/firefox-ios#9667]
## Steps to reproduce
1. Set network connection to "very bad network" in order to make the issue more visible
2.  Visit a page e.g "github.com"
3. Tap on the "X" icon
### Expected behavior
- The page should stop loading.
### Actual behavior
- After the page starts to load, the button is not functional. If the "X" button is tapped while the hompage is still displayed, the URL will be erased and the page stops loading.
### Device & build information
* Device: iPhone Xr (15.1)
* Build version: 40.2 ()
### Notes
- Issue was also reproducible on older builds
Attachments: 
https://user-images.githubusercontent.com/32130829/146774059-c15c9dfd-36f8-4eb2-9e33-7293f13529f0.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3543)

**Comment by lmarceau** [comment]
This will be ready to test after https://github.com/mozilla-mobile/firefox-ios/pull/9809 is merged.

**Comment by data-sync-user** [comment]
➤ Simion Basca commented:

Verifying as fix on main  c6d17c95da56477529f3bc3a1bd0dbf50d2717a5. This issue is no longer reproducible after following the STR.

Note: While testing I’ve found 2 other issue that might be related.

  * https://mozilla-hub.atlassian.net/browse/FXIOS-3654 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3654|smart-link ) 
  * https://mozilla-hub.atlassian.net/browse/FXIOS-3655 ( https://mozilla-hub.atlassian.net/browse/FXIOS-3655|smart-link )
