### ISSUE TITLE
The user is not redirected to the newly opened tab

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-ios#9951]
## Steps to reproduce
1. Launch Firefox and open https://mypay.dfas.mil/#/.
1. The unsupported message is displayed for the mypay.dfas.mil.
1. Let the prompt open and multitask to Gmail.
1. Open a new link from Gmail.
    1. Expected behavior
A new tab is opened in Firefox for iOS and the user is redirected to the newly opened tab.
    1. Actual behavior
The user is not redirected to the newly opened tab.
    1. Device & build information

* Device: iPhone 13 Pro max (15.1)
* Build version: Latest 9000 (7840)
    1. Notes
This is a regression from https://github.com/mozilla-mobile/firefox-ios/issues/9541.
Note that I tried this on Safari, and it works accordingly, the new tab is opened and the user is redirected there.
Attachments: 

https://user-images.githubusercontent.com/42831109/152539406-71ebe90f-fcce-4175-a127-98ac3735d81e.mov

https://user-images.githubusercontent.com/42831109/152539412-688fd7b7-9cad-4918-8db3-c66473cc837e.mov

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3721)

**Comment by lmarceau** [comment]
I believe it was decided that to fix https://github.com/mozilla-mobile/firefox-ios/issues/9541 the tab is opened in the background (and the user keep seeing the popup window). So we're not switching to the new tab. 

This solution was the simplest due to how we show the unsupported message - to support having the same behavior as Safari we need to change how we present that view.

**Comment by yoanarios** [comment]
Yes the implementation avoid dismissing the alert that was causing the crash and add the tab "on background" but doesn't switch to the new tab,  the user has to manually dismiss the alert and switch tab
